#!/usr/bin/env Rscript

# ==============================================================================
# Baseline and activated EBV TCR integration/clustering
# ==============================================================================
#
# Purpose:
#   This script runs the split downstream integration and clustering analyses for:
#     1. baseline EBV TCR object, and
#     2. activated/counterpart EBV TCR object.
#
#   It starts from the publication-ready TCR RDS objects generated by
#   9_TCR_multimer_QC.R:
#     - 1_EBV_baseline_TCR.rds
#     - 1_EBV_LCL_activated_TCR.rds
#
#   It performs:
#     - run/batch annotation,
#     - SCTransform,
#     - Harmony integration,
#     - clustering and UMAP,
#     - marker detection,
#     - contaminant cluster removal,
#     - illegitimate tetramer/sample filtering,
#     - re-integration after filtering,
#     - cluster reannotation,
#     - marker average-expression export, and
#     - module scoring for the baseline object.
#
# Notes:
#   - Paths are intentionally generic for GitHub.
#   - Update the config block before running.
#   - The baseline illegitimate tetramer filter is rule-based and writes the
#     flagged barcodes to disk. The activated workflow then removes the same
#     barcodes if present.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(stringr)
  library(readr)
  library(ggplot2)
  library(harmony)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  
  # Inputs from 9_TCR_multimer_QC.R
  baseline_input_rds = "path/to/Publication_RDS/1_EBV_baseline_TCR.rds",
  activated_input_rds = "path/to/Publication_RDS/1_EBV_LCL_activated_TCR.rds",
  
  # Output directories
  publication_rds_dir = "path/to/Publication_RDS",
  baseline_output_dir = "path/to/Publication_data/EBV_baseline/Clustering",
  activated_output_dir = "path/to/Publication_data/EBV_activated/Clustering",
  
  # Baseline outputs
  baseline_initial_rds = "path/to/Publication_RDS/2_baseline_EBV_filtered.rds",
  baseline_post_tetramer_filter_rds = "path/to/Publication_RDS/3_baseline_EBV_filtered.rds",
  baseline_clustered_rds = "path/to/Publication_RDS/3_baseline_EBV_clustered.rds",
  baseline_module_scored_rds = "path/to/Publication_RDS/4_baseline_EBV_module_scored.rds",
  baseline_final_rds = "path/to/Publication_RDS/Baseline_EBV_integrated_seurat.rds",
  
  # Activated outputs
  activated_final_rds = "path/to/Publication_RDS/Activated_EBV_integrated_seurat.rds",
  
  # Shared QC outputs
  flagged_illegitimate_cells_csv = "path/to/Publication_RDS/flagged_illegitimate_tetramer_cells.csv",
  flagged_illegitimate_barcodes_txt = "path/to/Publication_RDS/flagged_illegitimate_tetramer_barcodes.txt",
  
  session_info_file = "path/to/Publication_RDS/sessionInfo_split_baseline_activated_integration.txt",
  
  # Metadata columns
  batch_col = "batch",
  run_col = "run",
  cluster_col = "harmony_clusters",
  new_cluster_col = "new_cluster",
  matched_cluster_col = "matched_cluster",
  celltype_col = "celltype",
  celltype_new_col = "celltype_new",
  tetramer_col = "tetramer",
  sample_col = "sample",
  
  # Integration parameters
  assay = "RNA",
  sct_assay = "SCT",
  vars_to_regress = c("S.Score", "G2M.Score", "percent.mt"),
  harmony_group = "run",
  dims_use = 1:30,
  graph_name = "harmony_snn",
  umap_name = "umap.harmony",
  
  # Marker settings
  marker_min_log2fc = 0.5,
  top_marker_min_log2fc = 1,
  top_n_markers = 30,
  remove_marker_regex = "^RPS|^RPL|^MT-",
  
  verbose = TRUE
)


# ----------------------------- #
# 2. Dataset-specific settings
# ----------------------------- #

baseline_cfg <- list(
  dataset_id = "baseline",
  input_rds = config$baseline_input_rds,
  output_dir = config$baseline_output_dir,
  
  sct_return_only_var_genes = FALSE,
  
  # First pass: identify obvious contaminant cluster.
  initial_resolution = 0.4,
  initial_contaminant_clusters = c("5"),
  
  # Second pass after contaminant removal.
  second_resolution = 0.5,
  
  # Final pass after illegitimate tetramer removal.
  final_resolution = 0.5,
  
  initial_top30_csv = file.path(config$baseline_output_dir, "top30_cluster_markers_initial.csv"),
  post_contaminant_top30_csv = file.path(config$baseline_output_dir, "top30_cluster_markers_post_contaminant_removal.csv"),
  final_top30_csv = file.path(config$baseline_output_dir, "top30_cluster_markers_post_subset.csv"),
  avg_marker_csv = file.path(config$baseline_output_dir, "avg_expression_markers_by_cluster.csv"),
  
  elbow_prefix = file.path(config$baseline_output_dir, "baseline"),
  
  final_cluster_to_new_cluster = c(
    "2" = "0",
    "0" = "1",
    "1" = "2",
    "3" = "3",
    "4" = "4",
    "6" = "5",
    "5" = "6"
  ),
  
  final_cluster_to_celltype = c(
    "2" = "Naive/early TCM",
    "4" = "CD69+ early activated T",
    "6" = "innate-like T",
    "0" = "TEM",
    "1" = "Late TEM",
    "5" = "CD69+ TEM",
    "3" = "CTL"
  ),
  
  marker_genes = c(
    "BACH2", "LTB", "CCR7", "CD55", "GZMK", "TC2N", "CXCR3", "EPHA4",
    "GZMH", "NKG7", "HLA-DRB1", "HLA-DPB1", "GNLY", "GZMB", "FGFBP2",
    "PRF1", "TPM4", "CD69", "ACTB", "GBP1", "KLRB1", "CEBPD", "CCR6",
    "SLC4A10", "CCL4", "CCL4L2", "IFNG", "TNF"
  )
)


activated_cfg <- list(
  dataset_id = "activated",
  input_rds = config$activated_input_rds,
  output_dir = config$activated_output_dir,
  
  sct_return_only_var_genes = TRUE,
  
  initial_resolution = 0.5,
  initial_contaminant_clusters = c("8"),
  final_resolution = 0.5,
  
  initial_top30_csv = file.path(config$activated_output_dir, "top30_cluster_markers_initial.csv"),
  final_top30_csv = file.path(config$activated_output_dir, "top30_cluster_markers_post_subset.csv"),
  avg_marker_csv = file.path(config$activated_output_dir, "avg_expression_markers_by_cluster.csv"),
  
  elbow_prefix = file.path(config$activated_output_dir, "activated"),
  
  harmony_to_matched_cluster = c(
    "0" = "0",
    "1" = "2",
    "2" = "1",
    "3" = "7",
    "4" = "3",
    "5" = "5",
    "6" = "6",
    "7" = "4",
    "8" = "8"
  ),
  
  matched_to_new_cluster = c(
    "2" = "0",
    "0" = "1",
    "8" = "8",
    "1" = "2",
    "3" = "3",
    "4" = "4",
    "6" = "5",
    "7" = "7",
    "5" = "6"
  ),
  
  matched_to_celltype = c(
    "0" = "Naive/early TCM",
    "1" = "TEM",
    "8" = "TEM",
    "7" = "T activated EM",
    "4" = "T activated CM",
    "6" = "T activated EM",
    "2" = "T Late EM",
    "3" = "CTL",
    "5" = "T innate-like"
  ),
  
  marker_genes = c(
    "BACH2", "LTB", "CCR7", "CD55", "GZMK", "TC2N", "CXCR3", "EPHA4",
    "FLNA", "MYADM", "FOSB", "IL2RB", "GZMH", "NKG7", "HLA-DRB1",
    "HLA-DPB1", "ISG15", "IFIT1", "STAT1", "GNLY", "GZMB", "FGFBP2",
    "PRF1", "TPM4", "CD69", "ACTB", "GBP1", "KLRB1", "CEBPD", "CCR6",
    "SLC4A10", "MIR155HG", "TNFRSF9", "FABP5", "CD82", "RGS1", "FAS",
    "CD70", "IL32", "CCL4", "CCL4L2", "IFNG", "TNF", "IL2RA"
  )
)


# ----------------------------- #
# 3. Illegitimate tetramer/sample map
# ----------------------------- #

# These tetramers were only legitimately stained in the samples listed here.
# If another sample is called with one of these tetramers, it is flagged and
# removed before final baseline re-integration.

allowed_tetramer_sample_map <- tribble(
  ~tet_core, ~sample,
  "LPRR", "C246",
  "LPRR", "C287",
  "RPQG", "C246",
  "RPQG", "C287",
  "ELRS", "MS359",
  "ELRS", "MS394",
  "QEIR", "MS173",
  "LPFE", "C339",
  "LPFE", "MS069",
  "RYGF", "MS045",
  "RYGF", "MS136",
  "LEKA", "MS358",
  "LEKA", "MS173"
)


# ----------------------------- #
# 4. Helper functions
# ----------------------------- #

create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}


create_parent_dir <- function(path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
}


load_seurat <- function(path) {
  
  if (!file.exists(path)) {
    stop("Input RDS does not exist: ", path)
  }
  
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS does not contain a Seurat object: ", path)
  }
  
  obj
}


join_layers_if_possible <- function(obj, assay_name) {
  
  if (!assay_name %in% Assays(obj)) {
    stop("Assay not found: ", assay_name)
  }
  
  obj[[assay_name]] <- tryCatch(
    {
      JoinLayers(obj[[assay_name]])
    },
    error = function(e) {
      message("JoinLayers skipped for assay ", assay_name, ": ", e$message)
      obj[[assay_name]]
    }
  )
  
  obj
}


assign_run <- function(obj, cfg, include_activated = FALSE) {
  
  batch <- as.character(obj@meta.data[[cfg$batch_col]])
  
  run <- case_when(
    batch %in% c("GEMA", "GEMB") ~ "1",
    batch %in% c("GEM1", "GEM2") ~ "2",
    batch %in% c("GEM3", "GEM4") ~ "3",
    batch %in% c("GEM5", "GEM6") ~ "4",
    batch %in% c("GEM7", "GEM8") ~ "5",
    batch %in% c("GEM9", "GEM10") ~ "6",
    batch %in% c("GEM11") ~ "7",
    batch %in% c("GEM13") ~ "8",
    batch %in% c("GEMEBV1") ~ "9",
    batch %in% c("GEMEBV2", "GEMEBV3") ~ "10",
    batch %in% c("GEMEBV4", "GEMEBV5") ~ "11",
    include_activated &
      batch %in% c(
        "EBVLCL1DEX", "EBVLCL2DEX",
        "EBVLCL1CD8", "EBVLCL2CD8",
        "EBVLCL1CD4", "EBVLCL2CD4"
      ) ~ "12",
    TRUE ~ NA_character_
  )
  
  obj@meta.data[[cfg$run_col]] <- factor(run)
  
  if (any(is.na(obj@meta.data[[cfg$run_col]]))) {
    missing_batches <- unique(batch[is.na(obj@meta.data[[cfg$run_col]])])
    warning(
      "Some cells have batches that were not assigned to a run: ",
      paste(missing_batches, collapse = ", ")
    )
  }
  
  obj
}


run_sct_harmony_clustering <- function(
    obj,
    cfg,
    dataset_cfg,
    resolution,
    stage_label
) {
  
  message("\nRunning SCT/Harmony clustering: ", dataset_cfg$dataset_id, " | ", stage_label)
  
  include_activated <- dataset_cfg$dataset_id == "activated"
  
  obj <- assign_run(
    obj = obj,
    cfg = cfg,
    include_activated = include_activated
  )
  
  DefaultAssay(obj) <- cfg$assay
  
  obj <- join_layers_if_possible(obj, cfg$assay)
  obj[[cfg$assay]] <- split(obj[[cfg$assay]], f = obj@meta.data[[cfg$run_col]])
  
  vars_to_regress <- intersect(cfg$vars_to_regress, colnames(obj@meta.data))
  
  obj <- SCTransform(
    object = obj,
    assay = cfg$assay,
    new.assay.name = cfg$sct_assay,
    vars.to.regress = vars_to_regress,
    return.only.var.genes = dataset_cfg$sct_return_only_var_genes,
    verbose = cfg$verbose
  )
  
  DefaultAssay(obj) <- cfg$sct_assay
  
  obj <- RunPCA(
    object = obj,
    assay = cfg$sct_assay,
    verbose = cfg$verbose
  )
  
  elbow_file <- paste0(dataset_cfg$elbow_prefix, "_", stage_label, "_elbow.jpeg")
  
  p_elbow <- ElbowPlot(obj)
  
  ggsave(
    filename = elbow_file,
    plot = p_elbow,
    height = 5,
    width = 20,
    dpi = 300,
    limitsize = FALSE
  )
  
  obj <- join_layers_if_possible(obj, cfg$assay)
  
  obj <- RunHarmony(
    object = obj,
    group.by.vars = cfg$harmony_group,
    assay.use = cfg$sct_assay,
    verbose = cfg$verbose
  )
  
  obj <- FindNeighbors(
    object = obj,
    reduction = "harmony",
    dims = cfg$dims_use,
    graph.name = cfg$graph_name
  )
  
  obj <- FindClusters(
    object = obj,
    resolution = resolution,
    graph.name = cfg$graph_name,
    cluster.name = cfg$cluster_col
  )
  
  obj <- RunUMAP(
    object = obj,
    reduction = "harmony",
    dims = cfg$dims_use,
    reduction.name = cfg$umap_name
  )
  
  obj
}


save_basic_umaps <- function(obj, cfg, dataset_cfg, stage_label) {
  
  cluster_plot <- DimPlot(
    obj,
    reduction = cfg$umap_name,
    group.by = cfg$cluster_col,
    label = TRUE
  ) +
    ggtitle(paste(dataset_cfg$dataset_id, stage_label, "clusters"))
  
  ggsave(
    filename = file.path(dataset_cfg$output_dir, paste0(stage_label, "_umap_clusters.jpeg")),
    plot = cluster_plot,
    width = 8,
    height = 6,
    dpi = 300
  )
  
  if (cfg$batch_col %in% colnames(obj@meta.data)) {
    batch_plot <- DimPlot(
      obj,
      reduction = cfg$umap_name,
      group.by = cfg$batch_col
    ) +
      ggtitle(paste(dataset_cfg$dataset_id, stage_label, "batch"))
    
    ggsave(
      filename = file.path(dataset_cfg$output_dir, paste0(stage_label, "_umap_batch.jpeg")),
      plot = batch_plot,
      width = 8,
      height = 6,
      dpi = 300
    )
  }
}


find_and_save_markers <- function(obj, cfg, output_csv) {
  
  DefaultAssay(obj) <- cfg$sct_assay
  
  prep <- PrepSCTFindMarkers(
    object = obj,
    assay = cfg$sct_assay
  )
  
  cluster_markers <- FindAllMarkers(
    object = prep,
    only.pos = TRUE,
    assay = cfg$sct_assay,
    slot = "data"
  )
  
  markers_filtered <- cluster_markers %>%
    group_by(cluster) %>%
    filter(avg_log2FC > cfg$marker_min_log2fc) %>%
    ungroup() %>%
    filter(!grepl(cfg$remove_marker_regex, gene))
  
  top30 <- markers_filtered %>%
    group_by(cluster) %>%
    filter(avg_log2FC > cfg$top_marker_min_log2fc) %>%
    slice_head(n = cfg$top_n_markers) %>%
    ungroup()
  
  readr::write_csv(top30, output_csv)
  
  invisible(list(
    all_markers = cluster_markers,
    filtered_markers = markers_filtered,
    top_markers = top30
  ))
}


save_average_marker_expression <- function(obj, cfg, dataset_cfg) {
  
  DefaultAssay(obj) <- cfg$sct_assay
  
  genes_present <- intersect(dataset_cfg$marker_genes, rownames(obj))
  genes_missing <- setdiff(dataset_cfg$marker_genes, genes_present)
  
  if (length(genes_missing) > 0) {
    message(
      "Missing marker genes for ",
      dataset_cfg$dataset_id,
      ": ",
      paste(genes_missing, collapse = ", ")
    )
  }
  
  if (length(genes_present) == 0) {
    warning("No marker genes found for average-expression export.")
    return(invisible(NULL))
  }
  
  avg <- AverageExpression(
    obj,
    assays = cfg$sct_assay,
    features = genes_present,
    group.by = cfg$cluster_col,
    slot = "data",
    verbose = FALSE
  )[[cfg$sct_assay]]
  
  avg_df <- as.data.frame(avg)
  avg_df$gene <- rownames(avg_df)
  
  readr::write_csv(avg_df, dataset_cfg$avg_marker_csv)
  
  invisible(avg_df)
}


remove_contaminant_clusters <- function(obj, clusters_to_remove, cfg) {
  
  if (length(clusters_to_remove) == 0) {
    return(obj)
  }
  
  subset(
    obj,
    subset = !(harmony_clusters %in% clusters_to_remove)
  )
}


extract_tetramer_core <- function(tetramer) {
  
  tetramer <- as.character(tetramer)
  
  # Handles values like "B07_LPRR", "LPRR", "RPQK*".
  core <- str_extract(tetramer, "[A-Z]{4}\\*?$")
  core <- str_replace(core, "\\*$", "")
  
  core
}


flag_illegitimate_tetramer_cells <- function(obj, cfg, allowed_map) {
  
  required_cols <- c(cfg$tetramer_col, cfg$sample_col)
  missing_cols <- setdiff(required_cols, colnames(obj@meta.data))
  
  if (length(missing_cols) > 0) {
    stop(
      "Cannot run illegitimate tetramer filter. Missing metadata columns: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  meta <- obj@meta.data %>%
    rownames_to_column("cell_barcode") %>%
    mutate(
      tet_core = extract_tetramer_core(.data[[cfg$tetramer_col]])
    )
  
  tetramers_to_check <- unique(allowed_map$tet_core)
  
  bad_cells <- meta %>%
    filter(tet_core %in% tetramers_to_check) %>%
    anti_join(allowed_map, by = c("tet_core", cfg$sample_col)) %>%
    select(
      cell_barcode,
      all_of(cfg$sample_col),
      all_of(cfg$tetramer_col),
      tet_core
    )
  
  readr::write_csv(
    bad_cells,
    cfg$flagged_illegitimate_cells_csv
  )
  
  readr::write_lines(
    bad_cells$cell_barcode,
    cfg$flagged_illegitimate_barcodes_txt
  )
  
  bad_cells
}


remove_barcodes <- function(obj, barcodes) {
  
  barcodes_present <- intersect(barcodes, colnames(obj))
  
  if (length(barcodes_present) == 0) {
    return(obj)
  }
  
  subset(
    obj,
    cells = setdiff(colnames(obj), barcodes_present)
  )
}


annotate_baseline_clusters <- function(obj, cfg, dataset_cfg) {
  
  clusters <- as.character(obj@meta.data[[cfg$cluster_col]])
  
  obj@meta.data[[cfg$new_cluster_col]] <- unname(
    dataset_cfg$final_cluster_to_new_cluster[clusters]
  )
  
  obj@meta.data[[cfg$new_cluster_col]] <- factor(
    obj@meta.data[[cfg$new_cluster_col]],
    levels = as.character(0:6)
  )
  
  obj@meta.data[[cfg$celltype_new_col]] <- unname(
    dataset_cfg$final_cluster_to_celltype[clusters]
  )
  
  obj
}


annotate_activated_clusters <- function(obj, cfg, dataset_cfg) {
  
  harmony_clusters <- as.character(obj@meta.data[[cfg$cluster_col]])
  
  obj@meta.data[[cfg$matched_cluster_col]] <- unname(
    dataset_cfg$harmony_to_matched_cluster[harmony_clusters]
  )
  
  matched_clusters <- as.character(obj@meta.data[[cfg$matched_cluster_col]])
  
  obj@meta.data[[cfg$new_cluster_col]] <- unname(
    dataset_cfg$matched_to_new_cluster[matched_clusters]
  )
  
  obj@meta.data[[cfg$new_cluster_col]] <- factor(
    obj@meta.data[[cfg$new_cluster_col]],
    levels = as.character(0:8)
  )
  
  obj@meta.data[[cfg$celltype_col]] <- unname(
    dataset_cfg$matched_to_celltype[matched_clusters]
  )
  
  obj
}


add_cytotoxicity_score <- function(obj, cfg) {
  
  cytotoxicity_genes <- c(
    "GZMB", "GZMH", "GZMK", "GZMA", "GZMM",
    "PRF1", "GNLY", "NKG7", "FGFBP2", "CTSW",
    "KLRD1", "KLRB1", "KLRK1",
    "TBX21", "EOMES", "ZEB2", "ID2",
    "IFNG", "IFITM1", "IFITM2", "IFITM3",
    "CX3CR1", "S100A4", "S100A10"
  )
  
  genes_present <- intersect(cytotoxicity_genes, rownames(obj))
  
  if (length(genes_present) == 0) {
    warning("No cytotoxicity genes found in object. Skipping module score.")
    return(obj)
  }
  
  DefaultAssay(obj) <- cfg$sct_assay
  
  obj <- AddModuleScore(
    object = obj,
    assay = cfg$sct_assay,
    features = list(Cytotoxicity = genes_present),
    name = "Cytotoxicity"
  )
  
  obj@meta.data <- obj@meta.data %>%
    rename(Cytotoxicity_score = Cytotoxicity1)
  
  obj
}


add_experiment_column <- function(obj, cfg) {
  
  batch <- as.character(obj@meta.data[[cfg$batch_col]])
  
  obj@meta.data <- obj@meta.data %>%
    mutate(
      experiment = case_when(
        grepl("^GEMEBV", batch) ~ "enriched_baseline",
        grepl("LCL", batch) ~ "post_stimulation",
        grepl("^GEM", batch) & !grepl("EBV", batch) ~ "global_baseline",
        TRUE ~ NA_character_
      )
    )
  
  obj
}


# ----------------------------- #
# 5. Baseline workflow
# ----------------------------- #

run_baseline_workflow <- function(cfg, dataset_cfg, allowed_map) {
  
  message("\n========================================")
  message("Running baseline integration workflow")
  message("========================================")
  
  create_dir(dataset_cfg$output_dir)
  
  obj <- load_seurat(dataset_cfg$input_rds)
  
  # Initial integration to identify contaminant cluster.
  obj_initial <- run_sct_harmony_clustering(
    obj = obj,
    cfg = cfg,
    dataset_cfg = dataset_cfg,
    resolution = dataset_cfg$initial_resolution,
    stage_label = "initial"
  )
  
  save_basic_umaps(obj_initial, cfg, dataset_cfg, "initial")
  find_and_save_markers(obj_initial, cfg, dataset_cfg$initial_top30_csv)
  
  # Remove contaminant cluster and re-integrate.
  obj_no_contam <- remove_contaminant_clusters(
    obj = obj_initial,
    clusters_to_remove = dataset_cfg$initial_contaminant_clusters,
    cfg = cfg
  )
  
  obj_second <- run_sct_harmony_clustering(
    obj = obj_no_contam,
    cfg = cfg,
    dataset_cfg = dataset_cfg,
    resolution = dataset_cfg$second_resolution,
    stage_label = "post_contaminant_removal"
  )
  
  save_basic_umaps(obj_second, cfg, dataset_cfg, "post_contaminant_removal")
  find_and_save_markers(obj_second, cfg, dataset_cfg$post_contaminant_top30_csv)
  
  saveRDS(obj_second, cfg$baseline_initial_rds)
  
  # Flag and remove illegitimate tetramer/sample combinations.
  bad_cells <- flag_illegitimate_tetramer_cells(
    obj = obj_second,
    cfg = cfg,
    allowed_map = allowed_map
  )
  
  obj_clean <- remove_barcodes(
    obj = obj_second,
    barcodes = bad_cells$cell_barcode
  )
  
  # Final re-integration after tetramer QC.
  obj_final <- run_sct_harmony_clustering(
    obj = obj_clean,
    cfg = cfg,
    dataset_cfg = dataset_cfg,
    resolution = dataset_cfg$final_resolution,
    stage_label = "post_illegitimate_tetramer_removal"
  )
  
  save_basic_umaps(obj_final, cfg, dataset_cfg, "post_illegitimate_tetramer_removal")
  find_and_save_markers(obj_final, cfg, dataset_cfg$final_top30_csv)
  save_average_marker_expression(obj_final, cfg, dataset_cfg)
  
  obj_final <- annotate_baseline_clusters(
    obj = obj_final,
    cfg = cfg,
    dataset_cfg = dataset_cfg
  )
  
  saveRDS(obj_final, cfg$baseline_post_tetramer_filter_rds)
  saveRDS(obj_final, cfg$baseline_clustered_rds)
  
  obj_final <- add_cytotoxicity_score(
    obj = obj_final,
    cfg = cfg
  )
  
  saveRDS(obj_final, cfg$baseline_module_scored_rds)
  saveRDS(obj_final, cfg$baseline_final_rds)
  
  message("Baseline final object saved to: ", cfg$baseline_final_rds)
  
  invisible(list(
    object = obj_final,
    bad_cells = bad_cells
  ))
}


# ----------------------------- #
# 6. Activated workflow
# ----------------------------- #

run_activated_workflow <- function(cfg, dataset_cfg) {
  
  message("\n========================================")
  message("Running activated integration workflow")
  message("========================================")
  
  create_dir(dataset_cfg$output_dir)
  
  obj <- load_seurat(dataset_cfg$input_rds)
  
  # Remove the same illegitimate baseline tetramer cells, if present.
  if (file.exists(cfg$flagged_illegitimate_barcodes_txt)) {
    bad_barcodes <- readr::read_lines(cfg$flagged_illegitimate_barcodes_txt)
    obj <- remove_barcodes(obj, bad_barcodes)
  } else {
    warning("Flagged barcode file not found. Activated object will not remove baseline-flagged cells.")
  }
  
  # Initial integration to identify contaminant cluster.
  obj_initial <- run_sct_harmony_clustering(
    obj = obj,
    cfg = cfg,
    dataset_cfg = dataset_cfg,
    resolution = dataset_cfg$initial_resolution,
    stage_label = "initial"
  )
  
  obj_initial <- add_experiment_column(obj_initial, cfg)
  
  save_basic_umaps(obj_initial, cfg, dataset_cfg, "initial")
  find_and_save_markers(obj_initial, cfg, dataset_cfg$initial_top30_csv)
  
  # Remove contaminant cluster and re-integrate.
  obj_no_contam <- remove_contaminant_clusters(
    obj = obj_initial,
    clusters_to_remove = dataset_cfg$initial_contaminant_clusters,
    cfg = cfg
  )
  
  obj_final <- run_sct_harmony_clustering(
    obj = obj_no_contam,
    cfg = cfg,
    dataset_cfg = dataset_cfg,
    resolution = dataset_cfg$final_resolution,
    stage_label = "post_contaminant_removal"
  )
  
  obj_final <- add_experiment_column(obj_final, cfg)
  
  save_basic_umaps(obj_final, cfg, dataset_cfg, "post_contaminant_removal")
  find_and_save_markers(obj_final, cfg, dataset_cfg$final_top30_csv)
  save_average_marker_expression(obj_final, cfg, dataset_cfg)
  
  obj_final <- annotate_activated_clusters(
    obj = obj_final,
    cfg = cfg,
    dataset_cfg = dataset_cfg
  )
  
  saveRDS(obj_final, cfg$activated_final_rds)
  
  message("Activated final object saved to: ", cfg$activated_final_rds)
  
  invisible(obj_final)
}


# ----------------------------- #
# 7. Run full pipeline
# ----------------------------- #

create_dir(config$publication_rds_dir)
create_dir(config$baseline_output_dir)
create_dir(config$activated_output_dir)

create_parent_dir(config$baseline_initial_rds)
create_parent_dir(config$baseline_post_tetramer_filter_rds)
create_parent_dir(config$baseline_clustered_rds)
create_parent_dir(config$baseline_module_scored_rds)
create_parent_dir(config$baseline_final_rds)
create_parent_dir(config$activated_final_rds)
create_parent_dir(config$flagged_illegitimate_cells_csv)
create_parent_dir(config$flagged_illegitimate_barcodes_txt)
create_parent_dir(config$session_info_file)

baseline_result <- run_baseline_workflow(
  cfg = config,
  dataset_cfg = baseline_cfg,
  allowed_map = allowed_tetramer_sample_map
)

activated_result <- run_activated_workflow(
  cfg = config,
  dataset_cfg = activated_cfg
)

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Baseline dataset configuration:",
    capture.output(str(baseline_cfg)),
    "",
    "Activated dataset configuration:",
    capture.output(str(activated_cfg)),
    "",
    "Illegitimate tetramer/sample map:",
    capture.output(print(allowed_tetramer_sample_map)),
    "",
    "Baseline final object:",
    paste0("Cells: ", ncol(baseline_result$object)),
    paste0("Flagged illegitimate cells removed: ", nrow(baseline_result$bad_cells)),
    "",
    "Activated final object:",
    paste0("Cells: ", ncol(activated_result)),
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nSplit baseline and activated integration workflows complete.")
message("Baseline final RDS: ", config$baseline_final_rds)
message("Activated final RDS: ", config$activated_final_rds)
message("Session info: ", config$session_info_file)