#!/usr/bin/env Rscript

# ==============================================================================
# Baseline and activated EBV TCR composition figures
# ==============================================================================
#
# Purpose:
#   Generate publication-ready composition analyses from the final baseline and
#   activated EBV TCR Seurat objects.
#
#   This script reproduces the following analyses:
#     1. Baseline EBV vs non-EBV cluster composition, excluding RPQG cells.
#     2. Baseline paired donor EBV vs non-EBV cluster proportions by cohort.
#     3. Baseline EBV latency class x cluster composition, excluding RPQG cells.
#     4. Activated baseline-latent vs stimulated-latent cluster composition.
#     5. Activated paired donor baseline-latent vs stimulated-latent proportions.
#     6. Activated tetramer x matched-cluster distribution heatmaps.
#     7. Activated stimulated-minus-baseline tetramer redistribution heatmaps.
# #
# Inputs:
#   - Baseline final RDS generated by split integration/clustering:
#       5_baseline_EBV_cluster_reannotated.rds
#   - Activated final RDS generated by split integration/clustering:
#       3_activated_EBV_reannotated.rds
#
# Notes:
#   - Paths are intentionally generic for GitHub.
#   - Update only the config block before running.
#   - The activated object is expected to contain baseline GEMEBV cells and
#     stimulated EBVLCL cells.
#   - If matched_cluster/new_cluster/celltype annotations are missing from the
#     activated object, they are reconstructed from harmony_clusters.
#
# ==============================================================================


# ----------------------------- #
# 0. Packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(stringr)
  library(ggplot2)
  library(scales)
  library(readr)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  # Final RDS objects
  baseline_rds = "path/to/Publication_RDS/Baseline_EBV_integrated_seurat.rds",
  activated_rds = "path/to/Publication_RDS/Activated_EBV_integrated_seurat.rds",
  
  # Output directories
  baseline_output_dir = "path/to/Publication_data/EBV_baseline/Clustering",
  activated_output_dir = "path/to/Publication_data/EBV_activated/Clustering",
  
  # Metadata columns
  sample_col = "sample",
  cohort_col = "cohort",
  batch_col = "batch",
  virus_col = "virus",
  lifecycle_col = "lifecycle",
  latency_col = "latency",
  tetramer_col = "tetramer",
  baseline_celltype_col = "celltype_new",
  activated_cluster_col = "new_cluster",
  activated_matched_cluster_col = "matched_cluster",
  
  # Analysis settings
  exclude_tetramer_regex = "RPQG",
  min_paired_samples = 3,
  global_alpha = 0.05,
  tile_alpha = 0.05,
  min_delta_percent = 15,
  
  # Output format settings
  png_dpi = 300,
  heatmap_dpi = 600,
  save_pdf = TRUE,
  verbose = TRUE
)


# ----------------------------- #
# 2. Shared plotting settings
# ----------------------------- #

celltype_colour_and_order <- c(
  "#D89000" = "Naive/early TCM",
  "#4DAFE8" = "TEM",
  "#009A70" = "Late TEM",
  "#E6D800" = "CTL",
  "#006FB0" = "CD69+ early activated T",
  "#D84A00" = "innate-like T",
  "#C76AA3" = "CD69+ TEM"
)

celltype_order <- unname(celltype_colour_and_order)
celltype_cols <- setNames(names(celltype_colour_and_order), celltype_order)

cluster_cols <- c(
  "0" = "#D89000",
  "1" = "#4DAFE8",
  "8" = "#c599ef",
  "2" = "#009A70",
  "3" = "#E6D800",
  "5" = "#D84A00",
  "4" = "#006FB0",
  "7" = "#9acd84",
  "6" = "#C76AA3"
)

cluster_order <- names(cluster_cols)

latency_order <- c("Lytic", "Latency III", "Latency II", "Latency I/0")
latency_test_order <- c("Lytic", "Latency I/0", "Latency II", "Latency III")

tetramer_order <- c(
  "RPPI", "FLRG", "QAKW", "YPLH*", "AVFD*", "LLDF", "YLQQ",
  "SSCS*", "CLGG", "FLYA", "RPQK*", "YNLR*", "HPVG"
)

matched_cluster_order <- c("2", "0", "8", "1", "3", "6", "4", "7", "5")

custom_cols <- colorRampPalette(c(
  "#011f4b", "#03396c", "#005b96", "#6497b1", "#b3cde0",
  "#ffefea", "#fbd9d3", "#ffb09c", "#fe5757", "#cb2424", "#900000"
))(100)


# ----------------------------- #
# 3. Helper functions
# ----------------------------- #

create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}

check_file_exists <- function(path) {
  if (!file.exists(path)) {
    stop("Input file does not exist: ", path)
  }
}

load_seurat <- function(path) {
  check_file_exists(path)
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("RDS does not contain a Seurat object: ", path)
  }
  
  obj
}

require_metadata_columns <- function(obj, cols, object_name = "object") {
  missing_cols <- setdiff(cols, colnames(obj@meta.data))
  
  if (length(missing_cols) > 0) {
    stop(
      "Missing required metadata columns in ", object_name, ": ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  invisible(TRUE)
}

format_p <- function(p) {
  case_when(
    is.na(p) ~ "NA",
    p < 0.001 ~ "<0.001",
    TRUE ~ sprintf("%.3f", p)
  )
}

clean_cohort <- function(x, ms_label = "MS") {
  x_clean <- str_to_lower(str_trim(as.character(x)))
  
  case_when(
    x_clean %in% c("ms", "pwms", "multiple sclerosis", "rrms", "ppms", "spms") ~ ms_label,
    x_clean %in% c(
      "control", "controls", "healthy control", "healthy controls",
      "hc", "nms", "non-ms", "non_ms", "non ms"
    ) ~ "Control",
    TRUE ~ as.character(x)
  )
}

clean_virus <- function(x) {
  x_clean <- str_to_lower(str_trim(as.character(x)))
  
  case_when(
    x_clean == "ebv" ~ "EBV",
    x_clean %in% c("negative", "neg", "non-ebv", "non_ebv", "non ebv") ~ "Negative",
    TRUE ~ as.character(x)
  )
}

clean_condition_from_batch <- function(batch) {
  batch_clean <- str_to_upper(str_trim(as.character(batch)))
  
  case_when(
    str_detect(batch_clean, "^GEMEBV") ~ "Baseline",
    str_detect(batch_clean, "^EBVLCL") ~ "Stimulated",
    TRUE ~ NA_character_
  )
}

add_stim_status <- function(obj, cfg) {
  require_metadata_columns(
    obj,
    c(cfg$batch_col, cfg$lifecycle_col),
    object_name = "activated object"
  )
  
  obj@meta.data <- obj@meta.data %>%
    mutate(
      batch_clean = str_to_upper(str_trim(as.character(.data[[cfg$batch_col]]))),
      lifecycle_clean = str_to_lower(str_trim(as.character(.data[[cfg$lifecycle_col]]))),
      stim_status = case_when(
        str_detect(batch_clean, "^GEMEBV") & lifecycle_clean == "latent" ~ "Baseline_latent",
        str_detect(batch_clean, "^EBVLCL") & lifecycle_clean == "latent" ~ "Stimulated_latent",
        TRUE ~ "Other"
      ),
      stim_status = factor(
        stim_status,
        levels = c("Baseline_latent", "Stimulated_latent", "Other")
      )
    )
  
  obj$stim_status <- obj@meta.data$stim_status
  obj
}

save_plot <- function(plot, filename, width, height, dpi = 300, bg = "white") {
  ggsave(
    filename = filename,
    plot = plot,
    width = width,
    height = height,
    dpi = dpi,
    bg = bg
  )
}

save_plot_with_pdf <- function(plot, filename_base, width, height, dpi = 300, bg = "white", save_pdf = TRUE) {
  save_plot(
    plot = plot,
    filename = paste0(filename_base, ".png"),
    width = width,
    height = height,
    dpi = dpi,
    bg = bg
  )
  
  if (isTRUE(save_pdf)) {
    ggsave(
      filename = paste0(filename_base, ".pdf"),
      plot = plot,
      width = width,
      height = height,
      bg = bg
    )
  }
}

run_paired_wilcox <- function(x, y, min_n = 3) {
  ok <- !is.na(x) & !is.na(y)
  
  if (sum(ok) < min_n) {
    return(NA_real_)
  }
  
  if (all((x[ok] - y[ok]) == 0)) {
    return(1)
  }
  
  wilcox.test(
    x[ok],
    y[ok],
    paired = TRUE,
    exact = FALSE
  )$p.value
}

annotate_activated_clusters_if_needed <- function(obj, cfg) {
  harmony_to_matched_cluster <- c(
    "0" = "0",
    "1" = "2",
    "2" = "1",
    "3" = "7",
    "4" = "3",
    "5" = "5",
    "6" = "6",
    "7" = "4",
    "8" = "8"
  )
  
  matched_to_new_cluster <- c(
    "2" = "0",
    "0" = "1",
    "8" = "8",
    "1" = "2",
    "3" = "3",
    "4" = "4",
    "6" = "5",
    "7" = "7",
    "5" = "6"
  )
  
  matched_to_celltype <- c(
    "0" = "Naive/early TCM",
    "1" = "TEM",
    "8" = "TEM",
    "7" = "T activated EM",
    "4" = "T activated CM",
    "6" = "T activated EM",
    "2" = "T Late EM",
    "3" = "CTL",
    "5" = "T innate-like"
  )
  
  if (!cfg$activated_matched_cluster_col %in% colnames(obj@meta.data)) {
    require_metadata_columns(obj, "harmony_clusters", object_name = "activated object")
    obj@meta.data[[cfg$activated_matched_cluster_col]] <- unname(
      harmony_to_matched_cluster[as.character(obj@meta.data$harmony_clusters)]
    )
  }
  
  if (!cfg$activated_cluster_col %in% colnames(obj@meta.data)) {
    matched <- as.character(obj@meta.data[[cfg$activated_matched_cluster_col]])
    obj@meta.data[[cfg$activated_cluster_col]] <- unname(matched_to_new_cluster[matched])
  }
  
  if (!"celltype" %in% colnames(obj@meta.data)) {
    matched <- as.character(obj@meta.data[[cfg$activated_matched_cluster_col]])
    obj@meta.data$celltype <- unname(matched_to_celltype[matched])
  }
  
  obj@meta.data[[cfg$activated_cluster_col]] <- factor(
    as.character(obj@meta.data[[cfg$activated_cluster_col]]),
    levels = cluster_order
  )
  
  obj@meta.data[[cfg$activated_matched_cluster_col]] <- factor(
    as.character(obj@meta.data[[cfg$activated_matched_cluster_col]]),
    levels = matched_cluster_order
  )
  
  obj
}


# ----------------------------- #
# 4. Baseline EBV vs Negative composition, excluding RPQG
# ----------------------------- #

run_baseline_ebv_vs_negative <- function(obj, cfg) {
  message("\nRunning baseline EBV vs Negative composition analysis")
  
  require_metadata_columns(
    obj,
    c(
      cfg$sample_col,
      cfg$cohort_col,
      cfg$tetramer_col,
      cfg$virus_col,
      cfg$baseline_celltype_col
    ),
    object_name = "baseline object"
  )
  
  outdir <- cfg$baseline_output_dir
  create_dir(outdir)
  
  meta_clean <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("cell") %>%
    mutate(
      patient_id = as.character(.data[[cfg$sample_col]]),
      cohort = clean_cohort(.data[[cfg$cohort_col]], ms_label = "MS"),
      cohort = factor(cohort, levels = c("Control", "MS")),
      tetramer_clean = str_to_upper(str_trim(as.character(.data[[cfg$tetramer_col]]))),
      virus = clean_virus(.data[[cfg$virus_col]]),
      virus = factor(virus, levels = c("Negative", "EBV")),
      celltype_new = factor(.data[[cfg$baseline_celltype_col]], levels = celltype_order)
    ) %>%
    filter(
      !str_detect(coalesce(tetramer_clean, ""), cfg$exclude_tetramer_regex),
      virus %in% c("Negative", "EBV"),
      !is.na(celltype_new),
      !is.na(patient_id)
    )
  
  rpqg_check <- meta_clean %>%
    summarise(
      remaining_excluded_tetramer_cells = sum(
        str_detect(coalesce(tetramer_clean, ""), cfg$exclude_tetramer_regex)
      ),
      total_cells_after_exclusion = n()
    )
  
  write_csv(
    rpqg_check,
    file.path(outdir, "baseline_EBV_vs_negative_RPQG_exclusion_check.csv")
  )
  
  plot_df <- meta_clean %>%
    count(virus, celltype_new, name = "n") %>%
    group_by(virus) %>%
    mutate(prop = n / sum(n)) %>%
    ungroup()
  
  p_bar <- ggplot(plot_df, aes(x = virus, y = prop, fill = celltype_new)) +
    geom_col(width = 0.65, colour = "white", linewidth = 0.25) +
    scale_fill_manual(values = celltype_cols, drop = FALSE) +
    scale_x_discrete(labels = c("Negative" = "Non-EBV", "EBV" = "EBV")) +
    scale_y_continuous(labels = percent_format(accuracy = 1), expand = c(0, 0)) +
    labs(
      x = NULL,
      y = "Proportion of cells",
      fill = "Cell type"
    ) +
    theme_classic(base_size = 14) +
    theme(
      axis.text.x = element_text(size = 13, colour = "black"),
      axis.text.y = element_text(size = 12, colour = "black"),
      axis.title.y = element_text(size = 14, colour = "black"),
      legend.title = element_text(size = 12),
      legend.text = element_text(size = 11)
    )
  
  save_plot_with_pdf(
    p_bar,
    file.path(outdir, "stacked_barplot_EBV_vs_negative_excluding_RPQG"),
    width = 8,
    height = 6,
    dpi = cfg$png_dpi,
    bg = "transparent",
    save_pdf = cfg$save_pdf
  )
  
  write_csv(
    plot_df,
    file.path(outdir, "stacked_barplot_EBV_vs_negative_excluding_RPQG.csv")
  )
  
  patient_prop_df <- meta_clean %>%
    filter(
      cohort %in% c("Control", "MS"),
      !is.na(patient_id)
    ) %>%
    count(patient_id, cohort, virus, celltype_new, name = "n") %>%
    complete(
      nesting(patient_id, cohort),
      virus = factor(c("Negative", "EBV"), levels = c("Negative", "EBV")),
      celltype_new = factor(celltype_order, levels = celltype_order),
      fill = list(n = 0)
    ) %>%
    group_by(patient_id, cohort, virus) %>%
    mutate(
      total_cells = sum(n),
      prop = if_else(total_cells > 0, n / total_cells, NA_real_)
    ) %>%
    ungroup()
  
  prop_wide <- patient_prop_df %>%
    select(patient_id, cohort, virus, celltype_new, prop, total_cells) %>%
    pivot_wider(
      names_from = virus,
      values_from = c(prop, total_cells),
      names_sep = "_"
    ) %>%
    filter(
      total_cells_Negative > 0,
      total_cells_EBV > 0
    )
  
  stats_df <- prop_wide %>%
    group_by(cohort, celltype_new) %>%
    summarise(
      n_patients = sum(!is.na(prop_Negative) & !is.na(prop_EBV)),
      median_negative = median(prop_Negative, na.rm = TRUE),
      median_ebv = median(prop_EBV, na.rm = TRUE),
      median_difference = median(prop_EBV - prop_Negative, na.rm = TRUE),
      p_value = run_paired_wilcox(prop_EBV, prop_Negative, min_n = cfg$min_paired_samples),
      .groups = "drop"
    ) %>%
    group_by(celltype_new) %>%
    mutate(FDR = p.adjust(p_value, method = "BH")) %>%
    ungroup() %>%
    mutate(
      p_label = paste0("FDR=", format_p(FDR)),
      significance = case_when(
        is.na(FDR) ~ "NA",
        FDR < 0.001 ~ "***",
        FDR < 0.01 ~ "**",
        FDR < 0.05 ~ "*",
        TRUE ~ "ns"
      ),
      celltype_new = factor(celltype_new, levels = celltype_order)
    ) %>%
    arrange(cohort, celltype_new)
  
  write_csv(
    stats_df,
    file.path(outdir, "EBV_vs_negative_celltype_proportion_stats_paired_wilcox_by_cohort_excluding_RPQG.csv")
  )
  
  write_csv(
    prop_wide,
    file.path(outdir, "EBV_vs_negative_celltype_proportion_sample_by_cohort_excluding_RPQG.csv")
  )
  
  scatter_df <- patient_prop_df %>%
    filter(!is.na(prop)) %>%
    semi_join(
      prop_wide %>% distinct(patient_id, cohort),
      by = c("patient_id", "cohort")
    ) %>%
    mutate(
      celltype_new = factor(celltype_new, levels = celltype_order),
      cluster_col = unname(celltype_cols[as.character(celltype_new)]),
      point_fill = if_else(virus == "EBV", cluster_col, "white"),
      point_outline = cluster_col,
      virus = factor(virus, levels = c("Negative", "EBV"))
    )
  
  plot_one_celltype <- function(ct) {
    df_ct <- scatter_df %>% filter(celltype_new == ct)
    
    stat_ct <- stats_df %>%
      filter(celltype_new == ct) %>%
      mutate(
        star_label = if_else(significance == "ns", "", significance),
        y_pos = 0.98
      )
    
    celltype_colour <- unname(celltype_cols[as.character(ct)])
    
    ggplot(df_ct, aes(x = virus, y = prop, group = patient_id)) +
      geom_line(colour = scales::alpha(celltype_colour, 0.35), linewidth = 0.5) +
      geom_point(
        aes(fill = point_fill, colour = point_outline),
        shape = 21,
        size = 3.2,
        stroke = 0.9,
        alpha = 1
      ) +
      geom_text(
        data = stat_ct,
        aes(x = 1.5, y = y_pos, label = star_label),
        inherit.aes = FALSE,
        size = 12,
        fontface = "bold",
        vjust = 1
      ) +
      facet_wrap(~ cohort, nrow = 1) +
      scale_fill_identity() +
      scale_colour_identity() +
      scale_x_discrete(labels = c("Negative" = "Non-EBV", "EBV" = "EBV")) +
      scale_y_continuous(
        limits = c(0, 1),
        breaks = seq(0, 1, by = 0.2),
        labels = percent_format(accuracy = 1),
        expand = expansion(mult = c(0, 0.02))
      ) +
      labs(
        title = as.character(ct),
        x = NULL,
        y = "Proportion of cells"
      ) +
      theme_classic(base_size = 14) +
      theme(
        plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.text.x = element_text(size = 14, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.title.y = element_text(size = 15, colour = "black"),
        legend.position = "none"
      )
  }
  
  pdf(
    file.path(outdir, "paired_scatter_EBV_vs_negative_celltype_proportions_by_cohort_excluding_RPQG_one_page_per_celltype.pdf"),
    width = 7,
    height = 5
  )
  
  for (ct in celltype_order) {
    if (any(scatter_df$celltype_new == ct, na.rm = TRUE)) {
      print(plot_one_celltype(ct))
    }
  }
  
  dev.off()
  
  invisible(list(
    meta_clean = meta_clean,
    stacked_bar = plot_df,
    paired_stats = stats_df,
    paired_sample_proportions = prop_wide
  ))
}


# ----------------------------- #
# 5. Baseline latency x cluster composition, excluding RPQG
# ----------------------------- #

run_baseline_latency_cluster_composition <- function(obj, cfg) {
  message("\nRunning baseline latency x cluster composition analysis")
  
  require_metadata_columns(
    obj,
    c(
      cfg$tetramer_col,
      cfg$virus_col,
      cfg$latency_col,
      cfg$baseline_celltype_col
    ),
    object_name = "baseline object"
  )
  
  outdir <- cfg$baseline_output_dir
  create_dir(outdir)
  
  meta_clean <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("cell_id") %>%
    mutate(
      tetramer_clean = str_to_upper(str_trim(as.character(.data[[cfg$tetramer_col]]))),
      virus = clean_virus(.data[[cfg$virus_col]]),
      latency_raw = str_squish(as.character(.data[[cfg$latency_col]])),
      latency_class = case_when(
        latency_raw == "Lytic" ~ "Lytic",
        latency_raw == "Latency I/0" ~ "Latency I/0",
        latency_raw == "Latency II" ~ "Latency II",
        latency_raw == "Latency III" ~ "Latency III",
        TRUE ~ NA_character_
      ),
      latency_class = factor(latency_class, levels = latency_test_order),
      celltype_new = factor(.data[[cfg$baseline_celltype_col]], levels = celltype_order)
    ) %>%
    filter(
      !str_detect(coalesce(tetramer_clean, ""), cfg$exclude_tetramer_regex),
      virus == "EBV",
      !is.na(latency_class),
      !is.na(celltype_new)
    )
  
  rpqg_check <- meta_clean %>%
    summarise(
      remaining_excluded_tetramer_cells = sum(
        str_detect(coalesce(tetramer_clean, ""), cfg$exclude_tetramer_regex)
      ),
      total_cells_after_exclusion = n()
    )
  
  latency_counts <- meta_clean %>%
    count(latency_class, name = "n") %>%
    arrange(latency_class)
  
  cluster_counts <- meta_clean %>%
    count(celltype_new, name = "n") %>%
    arrange(celltype_new)
  
  latency_cluster_counts <- meta_clean %>%
    count(latency_class, celltype_new, name = "n") %>%
    arrange(latency_class, celltype_new)
  
  write_csv(rpqg_check, file.path(outdir, "latency_cluster_RPQG_exclusion_check.csv"))
  write_csv(latency_counts, file.path(outdir, "latency_class_counts_excluding_RPQG.csv"))
  write_csv(cluster_counts, file.path(outdir, "cluster_counts_excluding_RPQG.csv"))
  write_csv(latency_cluster_counts, file.path(outdir, "latency_cluster_observed_counts_excluding_RPQG.csv"))
  
  latency_cluster_table <- table(meta_clean$latency_class, meta_clean$celltype_new)
  
  chisq_check <- suppressWarnings(chisq.test(latency_cluster_table))
  
  if (any(chisq_check$expected < 5)) {
    chisq_res <- chisq.test(
      latency_cluster_table,
      simulate.p.value = TRUE,
      B = 10000
    )
    chisq_method <- "Chi-square test with Monte Carlo simulation"
  } else {
    chisq_res <- chisq_check
    chisq_method <- "Pearson chi-square test"
  }
  
  chisq_df <- (nrow(latency_cluster_table) - 1) * (ncol(latency_cluster_table) - 1)
  chisq_stat <- unname(chisq_res$statistic)
  chisq_p <- chisq_res$p.value
  
  chisq_label <- paste0(
    chisq_method,
    ": chi-square = ",
    round(chisq_stat, 2),
    ", df = ",
    chisq_df,
    ", P = ",
    format.pval(chisq_p, digits = 3, eps = 0.001)
  )
  
  sink(file.path(outdir, "latency_cluster_chisq_result_excluding_RPQG.txt"))
  cat("Association between EBV antigen latency class and transcriptional cluster\n")
  cat("RPQG cells excluded\n\n")
  cat(chisq_label, "\n\n")
  cat("Observed counts:\n")
  print(latency_cluster_table)
  cat("\nExpected counts:\n")
  print(chisq_res$expected)
  cat("\nStandardised residuals:\n")
  print(chisq_res$stdres)
  sink()
  
  resid_df <- as.data.frame(as.table(chisq_res$stdres)) %>%
    rename(
      latency_class = Var1,
      celltype_new = Var2,
      std_residual = Freq
    ) %>%
    left_join(
      as.data.frame(as.table(latency_cluster_table)) %>%
        rename(
          latency_class = Var1,
          celltype_new = Var2,
          observed_n = Freq
        ),
      by = c("latency_class", "celltype_new")
    ) %>%
    left_join(
      as.data.frame(as.table(chisq_res$expected)) %>%
        rename(
          latency_class = Var1,
          celltype_new = Var2,
          expected_n = Freq
        ),
      by = c("latency_class", "celltype_new")
    ) %>%
    mutate(
      latency_class = factor(latency_class, levels = latency_order),
      celltype_new = factor(celltype_new, levels = rev(celltype_order)),
      label = paste0("n=", observed_n, "\nres=", sprintf("%.1f", std_residual))
    )
  
  write_csv(resid_df, file.path(outdir, "latency_cluster_chisq_standardised_residuals_excluding_RPQG.csv"))
  
  max_abs_res <- max(abs(resid_df$std_residual), na.rm = TRUE)
  
  if (is.na(max_abs_res) || max_abs_res == 0) {
    max_abs_res <- 1
  }
  
  p_latency_residuals <- ggplot(
    resid_df,
    aes(x = latency_class, y = celltype_new, fill = std_residual)
  ) +
    geom_tile(colour = "white", linewidth = 0.4) +
    scale_fill_gradientn(
      colours = custom_cols,
      limits = c(-max_abs_res, max_abs_res),
      values = scales::rescale(c(-max_abs_res, 0, max_abs_res)),
      name = "Standardised\nresidual"
    ) +
    labs(
      x = "EBV antigen latency class",
      y = "T cell cluster",
      title = "EBV antigen latency class is associated with transcriptional cluster composition",
      subtitle = chisq_label
    ) +
    theme_classic(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 35, hjust = 1),
      axis.text.y = element_text(size = 10),
      plot.title = element_text(face = "bold")
    )
  
  save_plot_with_pdf(
    p_latency_residuals,
    file.path(outdir, "latency_cluster_chisq_residual_heatmap_excluding_RPQG"),
    width = 8.2,
    height = 5.2,
    dpi = cfg$heatmap_dpi,
    bg = "white",
    save_pdf = cfg$save_pdf
  )
  
  plot_df_latency <- meta_clean %>%
    count(latency_class, celltype_new, name = "n") %>%
    group_by(latency_class) %>%
    mutate(
      total = sum(n),
      prop = n / total
    ) %>%
    ungroup() %>%
    mutate(
      latency_class = factor(latency_class, levels = latency_order),
      celltype_new = factor(celltype_new, levels = celltype_order)
    )
  
  write_csv(
    plot_df_latency,
    file.path(outdir, "latency_cluster_composition_proportions_excluding_RPQG.csv")
  )
  
  p_latency_bar <- ggplot(
    plot_df_latency,
    aes(x = latency_class, y = prop, fill = celltype_new)
  ) +
    geom_col(width = 0.7, colour = "white", linewidth = 0.25) +
    scale_fill_manual(values = celltype_cols, drop = FALSE) +
    scale_y_continuous(labels = percent_format(), expand = expansion(mult = c(0, 0.02))) +
    labs(
      x = "EBV antigen latency class",
      y = "Proportion of EBV-specific CD8+ T cells",
      fill = "T cell cluster",
      title = "Cluster composition across EBV antigen latency classes",
      subtitle = chisq_label
    ) +
    theme_classic(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 35, hjust = 1),
      legend.position = "right",
      plot.title = element_text(face = "bold")
    )
  
  save_plot_with_pdf(
    p_latency_bar,
    file.path(outdir, "latency_cluster_composition_barplot_excluding_RPQG"),
    width = 8.2,
    height = 5.2,
    dpi = cfg$heatmap_dpi,
    bg = "white",
    save_pdf = cfg$save_pdf
  )
  
  message(
    "Manuscript sentence: After excluding RPQG-specific cells, cluster composition differed by EBV antigen latency class (",
    chisq_label,
    ")."
  )
  
  invisible(list(
    meta_clean = meta_clean,
    chisq_result = chisq_res,
    residuals = resid_df,
    composition = plot_df_latency
  ))
}


# ----------------------------- #
# 6. Activated baseline-latent vs stimulated-latent composition
# ----------------------------- #

run_activated_baseline_vs_stimulated <- function(obj, cfg) {
  message("\nRunning activated baseline-latent vs stimulated-latent composition analysis")
  
  require_metadata_columns(
    obj,
    c(
      cfg$sample_col,
      cfg$cohort_col,
      cfg$batch_col,
      cfg$lifecycle_col,
      cfg$activated_cluster_col
    ),
    object_name = "activated object"
  )
  
  outdir <- cfg$activated_output_dir
  create_dir(outdir)
  
  obj <- add_stim_status(obj, cfg)
  
  plot_df <- obj@meta.data %>%
    filter(
      stim_status %in% c("Baseline_latent", "Stimulated_latent"),
      !is.na(.data[[cfg$activated_cluster_col]])
    ) %>%
    mutate(new_cluster = factor(as.character(.data[[cfg$activated_cluster_col]]), levels = cluster_order)) %>%
    count(stim_status, new_cluster, name = "n") %>%
    group_by(stim_status) %>%
    mutate(prop = n / sum(n)) %>%
    ungroup()
  
  p_bar <- ggplot(plot_df, aes(x = stim_status, y = prop, fill = new_cluster)) +
    geom_col(width = 0.65, colour = "white", linewidth = 0.25) +
    scale_fill_manual(values = cluster_cols, drop = FALSE) +
    scale_x_discrete(labels = c(
      "Baseline_latent" = "Baseline latent",
      "Stimulated_latent" = "Stimulated latent"
    )) +
    scale_y_continuous(labels = percent_format(accuracy = 1), expand = c(0, 0)) +
    labs(
      x = NULL,
      y = "Proportion of latent T cells",
      fill = "Cluster"
    ) +
    theme_classic(base_size = 14) +
    theme(
      axis.text.x = element_text(size = 14, colour = "black"),
      axis.text.y = element_text(size = 14, colour = "black"),
      axis.title.y = element_text(size = 16, colour = "black"),
      legend.title = element_text(size = 12),
      legend.text = element_text(size = 11)
    )
  
  save_plot_with_pdf(
    p_bar,
    file.path(outdir, "stacked_barplot_baseline_vs_stimulated_latent"),
    width = 7,
    height = 7,
    dpi = cfg$png_dpi,
    bg = "transparent",
    save_pdf = cfg$save_pdf
  )
  
  write_csv(plot_df, file.path(outdir, "stacked_barplot_baseline_vs_stimulated_latent.csv"))
  
  meta_df <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("cell") %>%
    mutate(
      patient_id = as.character(.data[[cfg$sample_col]]),
      cohort = clean_cohort(.data[[cfg$cohort_col]], ms_label = "MS"),
      cohort = factor(cohort, levels = c("Control", "MS")),
      new_cluster = factor(as.character(.data[[cfg$activated_cluster_col]]), levels = cluster_order)
    ) %>%
    filter(
      stim_status %in% c("Baseline_latent", "Stimulated_latent"),
      cohort %in% c("Control", "MS"),
      !is.na(new_cluster),
      !is.na(patient_id)
    )
  
  patient_prop_df <- meta_df %>%
    count(patient_id, cohort, stim_status, new_cluster, name = "n") %>%
    complete(
      nesting(patient_id, cohort),
      stim_status = factor(
        c("Baseline_latent", "Stimulated_latent"),
        levels = c("Baseline_latent", "Stimulated_latent")
      ),
      new_cluster = factor(cluster_order, levels = cluster_order),
      fill = list(n = 0)
    ) %>%
    group_by(patient_id, cohort, stim_status) %>%
    mutate(
      total_cells = sum(n),
      prop = if_else(total_cells > 0, n / total_cells, NA_real_)
    ) %>%
    ungroup()
  
  prop_wide <- patient_prop_df %>%
    select(patient_id, cohort, stim_status, new_cluster, prop, total_cells) %>%
    pivot_wider(
      names_from = stim_status,
      values_from = c(prop, total_cells),
      names_sep = "_"
    ) %>%
    filter(
      total_cells_Baseline_latent > 0,
      total_cells_Stimulated_latent > 0
    )
  
  stats_df <- prop_wide %>%
    group_by(cohort, new_cluster) %>%
    summarise(
      n_patients = sum(!is.na(prop_Baseline_latent) & !is.na(prop_Stimulated_latent)),
      median_baseline_latent = median(prop_Baseline_latent, na.rm = TRUE),
      median_stimulated_latent = median(prop_Stimulated_latent, na.rm = TRUE),
      median_difference = median(prop_Stimulated_latent - prop_Baseline_latent, na.rm = TRUE),
      p_value = run_paired_wilcox(
        prop_Stimulated_latent,
        prop_Baseline_latent,
        min_n = cfg$min_paired_samples
      ),
      .groups = "drop"
    ) %>%
    group_by(new_cluster) %>%
    mutate(FDR = p.adjust(p_value, method = "BH")) %>%
    ungroup() %>%
    mutate(
      p_label = paste0("FDR=", format_p(FDR)),
      significance = case_when(
        is.na(FDR) ~ "NA",
        FDR < 0.001 ~ "***",
        FDR < 0.01 ~ "**",
        FDR < 0.05 ~ "*",
        TRUE ~ "ns"
      ),
      new_cluster = factor(new_cluster, levels = cluster_order)
    ) %>%
    arrange(cohort, new_cluster)
  
  write_csv(
    stats_df,
    file.path(outdir, "baseline_vs_stimulated_latent_cluster_proportion_stats_paired_wilcox_by_cohort.csv")
  )
  
  write_csv(
    prop_wide,
    file.path(outdir, "baseline_vs_stimulated_latent_cluster_proportion_sample_by_cohort.csv")
  )
  
  scatter_df <- patient_prop_df %>%
    filter(!is.na(prop)) %>%
    semi_join(
      prop_wide %>% distinct(patient_id, cohort),
      by = c("patient_id", "cohort")
    ) %>%
    mutate(
      new_cluster = factor(new_cluster, levels = cluster_order),
      cluster_col = unname(cluster_cols[as.character(new_cluster)]),
      point_fill = if_else(stim_status == "Stimulated_latent", cluster_col, "white"),
      point_outline = cluster_col,
      stim_status = factor(stim_status, levels = c("Baseline_latent", "Stimulated_latent"))
    )
  
  plot_one_cluster <- function(cl) {
    df_cl <- scatter_df %>% filter(new_cluster == cl)
    
    stat_cl <- stats_df %>%
      filter(new_cluster == cl) %>%
      mutate(
        star_label = if_else(significance == "ns", "", significance),
        y_pos = 0.98
      )
    
    cluster_colour <- unname(cluster_cols[as.character(cl)])
    
    ggplot(df_cl, aes(x = stim_status, y = prop, group = patient_id)) +
      geom_line(colour = scales::alpha(cluster_colour, 0.35), linewidth = 0.5) +
      geom_point(
        aes(fill = point_fill, colour = point_outline),
        shape = 21,
        size = 3.2,
        stroke = 0.9,
        alpha = 1
      ) +
      geom_text(
        data = stat_cl,
        aes(x = 1.5, y = y_pos, label = star_label),
        inherit.aes = FALSE,
        size = 12,
        fontface = "bold",
        vjust = 1
      ) +
      facet_wrap(~ cohort, nrow = 1) +
      scale_fill_identity() +
      scale_colour_identity() +
      scale_x_discrete(labels = c(
        "Baseline_latent" = "Baseline",
        "Stimulated_latent" = "Stimulated"
      )) +
      scale_y_continuous(
        limits = c(0, 1),
        breaks = seq(0, 1, by = 0.2),
        labels = percent_format(accuracy = 1),
        expand = expansion(mult = c(0, 0.02))
      ) +
      labs(
        title = paste0("Cluster ", cl),
        x = NULL,
        y = "Proportion of latent T cells"
      ) +
      theme_classic(base_size = 14) +
      theme(
        plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        strip.text = element_blank(),
        strip.background = element_blank(),
        axis.text.x = element_text(size = 12, colour = "black", angle = 30, hjust = 1),
        axis.text.y = element_text(size = 14, colour = "black"),
        axis.title.y = element_text(size = 15, colour = "black"),
        legend.position = "none"
      )
  }
  
  pdf(
    file.path(outdir, "paired_scatter_baseline_vs_stimulated_latent_cluster_proportions_by_cohort_one_page_per_cluster.pdf"),
    width = 7,
    height = 5
  )
  
  for (cl in cluster_order) {
    if (any(scatter_df$new_cluster == cl, na.rm = TRUE)) {
      print(plot_one_cluster(cl))
    }
  }
  
  dev.off()
  
  invisible(list(
    stacked_bar = plot_df,
    paired_stats = stats_df,
    paired_sample_proportions = prop_wide,
    activated_object = obj
  ))
}


# ----------------------------- #
# 7. Activated metadata export
# ----------------------------- #

export_activated_tcr_metadata <- function(obj, cfg) {
  message("\nExporting activated TCR metadata")
  
  outdir <- cfg$activated_output_dir
  create_dir(outdir)
  
  cols_to_export <- c(
    "id",
    "cohort",
    "diagnosis",
    "age",
    "sex",
    "batch",
    "years_since_diagnosis",
    "sample",
    "TRA_v_gene",
    "TRA_d_gene",
    "TRA_j_gene",
    "TRA_c_gene",
    "TRA_cdr3",
    "TRA_cdr3_nt",
    "TRB_v_gene",
    "TRB_d_gene",
    "TRB_j_gene",
    "TRB_c_gene",
    "TRB_cdr3",
    "TRB_cdr3_nt",
    "tetramer",
    "virus",
    "lifecycle",
    "latency",
    "latent_group",
    "antigen",
    "harmony_clusters",
    "matched_cluster",
    "new_cluster",
    "celltype",
    "celltype_new",
    "stim_status"
  )
  
  meta_export <- obj@meta.data %>%
    select(any_of(cols_to_export)) %>%
    rownames_to_column("cell_barcode")
  
  write_csv(meta_export, file.path(outdir, "Activated_TCR_metadata.csv"))
  
  invisible(meta_export)
}


# ----------------------------- #
# 8. Activated tetramer redistribution heatmaps
# ----------------------------- #

prepare_tetramer_proportions <- function(activated_tcr, cfg, split_by_cohort = FALSE) {
  required_cols <- c(cfg$batch_col, cfg$tetramer_col, cfg$activated_matched_cluster_col)
  
  if (isTRUE(split_by_cohort)) {
    required_cols <- c(required_cols, cfg$cohort_col)
  }
  
  missing_cols <- setdiff(required_cols, colnames(activated_tcr))
  
  if (length(missing_cols) > 0) {
    stop("Missing required columns in activated metadata: ", paste(missing_cols, collapse = ", "))
  }
  
  if (isTRUE(split_by_cohort)) {
    prop_df <- activated_tcr %>%
      mutate(
        condition = clean_condition_from_batch(.data[[cfg$batch_col]]),
        cohort = clean_cohort(.data[[cfg$cohort_col]], ms_label = "MS"),
        tetramer = as.character(.data[[cfg$tetramer_col]]),
        matched_cluster = as.character(.data[[cfg$activated_matched_cluster_col]])
      ) %>%
      filter(
        !is.na(condition),
        cohort %in% c("Control", "MS"),
        tetramer %in% tetramer_order,
        matched_cluster %in% matched_cluster_order
      ) %>%
      count(cohort, tetramer, condition, matched_cluster, name = "n") %>%
      complete(
        cohort = c("Control", "MS"),
        tetramer = tetramer_order,
        condition = c("Baseline", "Stimulated"),
        matched_cluster = matched_cluster_order,
        fill = list(n = 0)
      ) %>%
      group_by(cohort, tetramer, condition) %>%
      mutate(
        total_tetramer_cells = sum(n),
        prop = if_else(total_tetramer_cells > 0, n / total_tetramer_cells, 0),
        prop_percent = prop * 100
      ) %>%
      ungroup()
  } else {
    prop_df <- activated_tcr %>%
      mutate(
        condition = clean_condition_from_batch(.data[[cfg$batch_col]]),
        tetramer = as.character(.data[[cfg$tetramer_col]]),
        matched_cluster = as.character(.data[[cfg$activated_matched_cluster_col]])
      ) %>%
      filter(
        !is.na(condition),
        tetramer %in% tetramer_order,
        matched_cluster %in% matched_cluster_order
      ) %>%
      count(tetramer, condition, matched_cluster, name = "n") %>%
      complete(
        tetramer = tetramer_order,
        condition = c("Baseline", "Stimulated"),
        matched_cluster = matched_cluster_order,
        fill = list(n = 0)
      ) %>%
      group_by(tetramer, condition) %>%
      mutate(
        total_tetramer_cells = sum(n),
        prop = if_else(total_tetramer_cells > 0, n / total_tetramer_cells, 0),
        prop_percent = prop * 100
      ) %>%
      ungroup()
  }
  
  prop_df
}

run_tetramer_distribution_heatmap <- function(activated_tcr, cfg) {
  message("\nRunning activated tetramer distribution heatmap")
  
  outdir <- cfg$activated_output_dir
  create_dir(outdir)
  
  plot_df <- prepare_tetramer_proportions(
    activated_tcr = activated_tcr,
    cfg = cfg,
    split_by_cohort = FALSE
  )
  
  row_order <- c(
    rev(paste(tetramer_order, "Baseline", sep = " | ")),
    rev(paste(tetramer_order, "Stimulated", sep = " | "))
  )
  
  plot_df_full <- plot_df %>%
    mutate(
      tetramer = factor(tetramer, levels = tetramer_order),
      condition = factor(condition, levels = c("Baseline", "Stimulated")),
      row_label = paste(tetramer, condition, sep = " | "),
      matched_cluster = factor(matched_cluster, levels = matched_cluster_order)
    ) %>%
    complete(
      row_label = row_order,
      matched_cluster = matched_cluster_order,
      fill = list(n = 0, prop = 0, prop_percent = 0)
    ) %>%
    mutate(
      row_label = factor(row_label, levels = rev(row_order)),
      matched_cluster = factor(matched_cluster, levels = matched_cluster_order)
    )
  
  p_distribution <- ggplot(
    plot_df_full,
    aes(x = matched_cluster, y = row_label, fill = prop)
  ) +
    geom_tile(color = "grey90", linewidth = 0.25) +
    scale_fill_gradient(
      low = "white",
      high = "red",
      labels = percent_format(accuracy = 1),
      name = "Proportion\nwithin tetramer"
    ) +
    labs(
      x = "Matched cluster",
      y = NULL,
      title = "Distribution of EBV-specific tetramer+ cells across matched clusters",
      subtitle = "Rows are normalised within each tetramer and condition"
    ) +
    theme_classic(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.text.y = element_text(size = 9),
      plot.title = element_text(face = "bold"),
      legend.position = "right"
    )
  
  save_plot_with_pdf(
    p_distribution,
    file.path(outdir, "tetramer_cluster_distribution_heatmap"),
    width = 7,
    height = 7,
    dpi = cfg$heatmap_dpi,
    bg = "white",
    save_pdf = cfg$save_pdf
  )
  
  write_csv(plot_df, file.path(outdir, "tetramer_cluster_baseline_stimulated_proportions.csv"))
  
  invisible(list(plot_data = plot_df, plot = p_distribution))
}

run_tetramer_delta_heatmap <- function(activated_tcr, cfg) {
  message("\nRunning activated tetramer redistribution delta heatmap")
  
  outdir <- cfg$activated_output_dir
  create_dir(outdir)
  
  prop_df <- prepare_tetramer_proportions(
    activated_tcr = activated_tcr,
    cfg = cfg,
    split_by_cohort = FALSE
  )
  
  delta_df <- prop_df %>%
    select(tetramer, condition, matched_cluster, n, prop, prop_percent, total_tetramer_cells) %>%
    pivot_wider(
      names_from = condition,
      values_from = c(n, prop, prop_percent, total_tetramer_cells),
      values_fill = 0
    ) %>%
    mutate(
      delta_prop = prop_Stimulated - prop_Baseline,
      delta_percent = delta_prop * 100
    )
  
  global_stats <- prop_df %>%
    select(tetramer, condition, matched_cluster, n) %>%
    group_by(tetramer) %>%
    summarise(
      global_p_value = {
        tab <- xtabs(n ~ condition + matched_cluster)
        tab <- tab[, colSums(tab) > 0, drop = FALSE]
        
        if (nrow(tab) < 2 || ncol(tab) < 2 || any(rowSums(tab) == 0)) {
          NA_real_
        } else {
          suppressWarnings(chisq.test(tab)$p.value)
        }
      },
      .groups = "drop"
    ) %>%
    mutate(
      global_FDR = p.adjust(global_p_value, method = "BH"),
      global_Holm = p.adjust(global_p_value, method = "holm")
    )
  
  stats_df <- delta_df %>%
    rowwise() %>%
    mutate(
      baseline_in_cluster = n_Baseline,
      baseline_out_cluster = total_tetramer_cells_Baseline - n_Baseline,
      stimulated_in_cluster = n_Stimulated,
      stimulated_out_cluster = total_tetramer_cells_Stimulated - n_Stimulated,
      p_value = if (
        total_tetramer_cells_Baseline == 0 ||
        total_tetramer_cells_Stimulated == 0
      ) {
        NA_real_
      } else {
        fisher.test(
          matrix(
            c(
              baseline_in_cluster,
              baseline_out_cluster,
              stimulated_in_cluster,
              stimulated_out_cluster
            ),
            nrow = 2,
            byrow = TRUE
          )
        )$p.value
      }
    ) %>%
    ungroup() %>%
    mutate(
      FDR = p.adjust(p_value, method = "BH"),
      Holm = p.adjust(p_value, method = "holm"),
      Bonferroni = p.adjust(p_value, method = "bonferroni")
    ) %>%
    left_join(global_stats, by = "tetramer") %>%
    mutate(
      sig = case_when(
        global_Holm < cfg$global_alpha &
          Holm < 0.001 &
          abs(delta_percent) >= cfg$min_delta_percent ~ "***",
        global_Holm < cfg$global_alpha &
          Holm < 0.01 &
          abs(delta_percent) >= cfg$min_delta_percent ~ "**",
        global_Holm < cfg$global_alpha &
          Holm < cfg$tile_alpha &
          abs(delta_percent) >= cfg$min_delta_percent ~ "*",
        TRUE ~ ""
      )
    )
  
  plot_df <- stats_df %>%
    mutate(
      tetramer = factor(tetramer, levels = rev(tetramer_order)),
      matched_cluster = factor(matched_cluster, levels = matched_cluster_order)
    )
  
  max_abs <- max(abs(plot_df$delta_percent), na.rm = TRUE)
  
  if (is.na(max_abs) || max_abs == 0) {
    max_abs <- 1
  }
  
  p_delta <- ggplot(
    plot_df,
    aes(x = matched_cluster, y = tetramer, fill = delta_percent)
  ) +
    geom_tile(color = "grey90", linewidth = 0.25) +
    geom_text(aes(label = sig), size = 4.5, fontface = "bold") +
    scale_fill_gradientn(
      colours = custom_cols,
      limits = c(-max_abs, max_abs),
      oob = scales::squish,
      breaks = pretty(c(-max_abs, max_abs), n = 7),
      name = "Change after\nstimulation\n(% points)"
    ) +
    labs(
      x = "Matched cluster",
      y = "Tetramer",
      title = "Redistribution of EBV-specific tetramer+ cells after stimulation",
      subtitle = paste0(
        "Stimulated minus baseline proportion within each tetramer; ",
        "stars require global Holm < 0.05, tile Holm < 0.05, and >=",
        cfg$min_delta_percent,
        " percentage-point shift"
      )
    ) +
    theme_classic(base_size = 12) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.text.y = element_text(size = 10),
      plot.title = element_text(face = "bold"),
      legend.position = "right"
    )
  
  save_plot_with_pdf(
    p_delta,
    file.path(outdir, "tetramer_cluster_redistribution_delta_heatmap"),
    width = 6,
    height = 6.5,
    dpi = cfg$heatmap_dpi,
    bg = "white",
    save_pdf = cfg$save_pdf
  )
  
  write_csv(stats_df, file.path(outdir, "tetramer_cluster_redistribution_delta_stats_conservative.csv"))
  write_csv(global_stats, file.path(outdir, "tetramer_global_redistribution_stats.csv"))
  write_csv(prop_df, file.path(outdir, "tetramer_cluster_baseline_stimulated_proportions_for_delta.csv"))
  
  invisible(list(
    prop_df = prop_df,
    delta_stats = stats_df,
    global_stats = global_stats,
    plot = p_delta
  ))
}

run_tetramer_delta_heatmap_by_cohort <- function(activated_tcr, cfg) {
  message("\nRunning cohort-split tetramer redistribution delta heatmap")
  
  outdir <- cfg$activated_output_dir
  create_dir(outdir)
  
  prop_df <- prepare_tetramer_proportions(
    activated_tcr = activated_tcr,
    cfg = cfg,
    split_by_cohort = TRUE
  )
  
  delta_df <- prop_df %>%
    select(cohort, tetramer, condition, matched_cluster, n, prop, prop_percent, total_tetramer_cells) %>%
    pivot_wider(
      names_from = condition,
      values_from = c(n, prop, prop_percent, total_tetramer_cells),
      values_fill = 0
    ) %>%
    mutate(
      delta_prop = prop_Stimulated - prop_Baseline,
      delta_percent = delta_prop * 100
    )
  
  global_stats <- prop_df %>%
    select(cohort, tetramer, condition, matched_cluster, n) %>%
    group_by(cohort, tetramer) %>%
    summarise(
      global_p_value = {
        tab <- xtabs(n ~ condition + matched_cluster)
        tab <- tab[, colSums(tab) > 0, drop = FALSE]
        
        if (nrow(tab) < 2 || ncol(tab) < 2 || any(rowSums(tab) == 0)) {
          NA_real_
        } else {
          suppressWarnings(chisq.test(tab)$p.value)
        }
      },
      .groups = "drop"
    ) %>%
    mutate(
      global_FDR = p.adjust(global_p_value, method = "BH"),
      global_Holm = p.adjust(global_p_value, method = "holm")
    )
  
  stats_df <- delta_df %>%
    rowwise() %>%
    mutate(
      baseline_in_cluster = n_Baseline,
      baseline_out_cluster = total_tetramer_cells_Baseline - n_Baseline,
      stimulated_in_cluster = n_Stimulated,
      stimulated_out_cluster = total_tetramer_cells_Stimulated - n_Stimulated,
      p_value = if (
        total_tetramer_cells_Baseline == 0 ||
        total_tetramer_cells_Stimulated == 0
      ) {
        NA_real_
      } else {
        fisher.test(
          matrix(
            c(
              baseline_in_cluster,
              baseline_out_cluster,
              stimulated_in_cluster,
              stimulated_out_cluster
            ),
            nrow = 2,
            byrow = TRUE
          )
        )$p.value
      }
    ) %>%
    ungroup() %>%
    mutate(
      FDR = p.adjust(p_value, method = "BH"),
      Holm = p.adjust(p_value, method = "holm"),
      Bonferroni = p.adjust(p_value, method = "bonferroni")
    ) %>%
    left_join(global_stats, by = c("cohort", "tetramer")) %>%
    mutate(
      sig = case_when(
        global_Holm < cfg$global_alpha &
          Holm < 0.001 &
          abs(delta_percent) >= cfg$min_delta_percent ~ "***",
        global_Holm < cfg$global_alpha &
          Holm < 0.01 &
          abs(delta_percent) >= cfg$min_delta_percent ~ "**",
        global_Holm < cfg$global_alpha &
          Holm < cfg$tile_alpha &
          abs(delta_percent) >= cfg$min_delta_percent ~ "*",
        TRUE ~ ""
      )
    )
  
  plot_df <- stats_df %>%
    mutate(
      cohort = factor(cohort, levels = c("Control", "MS")),
      tetramer = factor(tetramer, levels = rev(tetramer_order)),
      matched_cluster = factor(matched_cluster, levels = matched_cluster_order)
    )
  
  max_abs <- max(abs(plot_df$delta_percent), na.rm = TRUE)
  
  if (is.na(max_abs) || max_abs == 0) {
    max_abs <- 1
  }
  
  p_delta_split <- ggplot(
    plot_df,
    aes(x = matched_cluster, y = tetramer, fill = delta_percent)
  ) +
    geom_tile(color = "grey90", linewidth = 0.25) +
    geom_text(aes(label = sig), size = 4, fontface = "bold") +
    facet_grid(. ~ cohort) +
    scale_fill_gradientn(
      colours = custom_cols,
      limits = c(-max_abs, max_abs),
      oob = scales::squish,
      breaks = pretty(c(-max_abs, max_abs), n = 7),
      name = "Stimulated - baseline\n(percentage points)"
    ) +
    labs(
      x = "Matched cluster",
      y = "Tetramer",
      title = "Cohort-stratified redistribution of EBV-specific tetramer+ cells after stimulation",
      subtitle = paste0(
        "Rows are normalised within tetramer, cohort and condition; ",
        "stars require global Holm < 0.05, tile Holm < 0.05, and >=",
        cfg$min_delta_percent,
        " percentage-point shift"
      )
    ) +
    theme_classic(base_size = 12) +
    theme(
      strip.background = element_blank(),
      strip.text = element_text(face = "bold", size = 12),
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.text.y = element_text(size = 10),
      plot.title = element_text(face = "bold"),
      legend.position = "right"
    )
  
  save_plot_with_pdf(
    p_delta_split,
    file.path(outdir, "tetramer_cluster_redistribution_delta_heatmap_split_by_cohort"),
    width = 10,
    height = 6,
    dpi = cfg$heatmap_dpi,
    bg = "white",
    save_pdf = cfg$save_pdf
  )
  
  write_csv(stats_df, file.path(outdir, "tetramer_cluster_redistribution_delta_stats_split_by_cohort.csv"))
  write_csv(global_stats, file.path(outdir, "tetramer_global_redistribution_stats_split_by_cohort.csv"))
  write_csv(prop_df, file.path(outdir, "tetramer_cluster_baseline_stimulated_proportions_split_by_cohort.csv"))
  
  invisible(list(
    prop_df = prop_df,
    delta_stats = stats_df,
    global_stats = global_stats,
    plot = p_delta_split
  ))
}


# ----------------------------- #
# 9. Run full script
# ----------------------------- #

main <- function(cfg = config) {
  create_dir(cfg$baseline_output_dir)
  create_dir(cfg$activated_output_dir)
  
  baseline_obj <- load_seurat(cfg$baseline_rds)
  activated_obj <- load_seurat(cfg$activated_rds)
  
  activated_obj <- annotate_activated_clusters_if_needed(activated_obj, cfg)
  activated_obj <- add_stim_status(activated_obj, cfg)
  
  baseline_ebv_results <- run_baseline_ebv_vs_negative(baseline_obj, cfg)
  baseline_latency_results <- run_baseline_latency_cluster_composition(baseline_obj, cfg)
  
  activated_composition_results <- run_activated_baseline_vs_stimulated(activated_obj, cfg)
  
  # Use the activated object returned from the composition function because it
  # contains stim_status and any reconstructed annotations.
  activated_obj <- activated_composition_results$activated_object
  
  activated_tcr <- export_activated_tcr_metadata(activated_obj, cfg)
  
  tetramer_distribution_results <- run_tetramer_distribution_heatmap(activated_tcr, cfg)
  tetramer_delta_results <- run_tetramer_delta_heatmap(activated_tcr, cfg)
  tetramer_delta_split_results <- run_tetramer_delta_heatmap_by_cohort(activated_tcr, cfg)
  writeLines(
    c(
      "Baseline and activated EBV TCR composition script complete.",
      "",
      "Configuration:",
      capture.output(str(cfg)),
      "",
      "Session information:",
      capture.output(sessionInfo())
    ),
    file.path(cfg$activated_output_dir, "sessionInfo_baseline_activated_composition_figures.txt")
  )
  
  invisible(list(
    baseline_ebv = baseline_ebv_results,
    baseline_latency = baseline_latency_results,
    activated_composition = activated_composition_results,
    activated_tcr = activated_tcr,
    tetramer_distribution = tetramer_distribution_results,
    tetramer_delta = tetramer_delta_results,
    tetramer_delta_split = tetramer_delta_split_results
  ))
}

main(config)
