#!/usr/bin/env Rscript

# ==============================================================================
# Cluster and cytotoxicity UMAPs for baseline and activated EBV TCR objects
# ==============================================================================
#
# Purpose:
#   This script generates:
#     1. baseline EBV cluster UMAP,
#     2. baseline EBV cytotoxicity-score UMAP, and
#     3. activated EBV cluster UMAP.
#
#   It starts from the final publication-ready RDS objects generated by the
#   baseline/activated integration workflow:
#     - 5_baseline_EBV_cluster_reannotated.rds
#     - 3_activated_EBV_reannotated.rds
#
# Notes:
#   - Paths are intentionally generic for GitHub.
#   - Update the config block before running.
#   - The script is robust to either `new_cluster` or `cluster_new` being present
#     in the baseline object.
#   - Activated cluster annotations are rebuilt only if required.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tibble)
  library(stringr)
  library(ggplot2)
  library(scales)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  
  # Input RDS files
  baseline_input_rds = "path/to/Publication_RDS/Baseline_EBV_integrated_seurat.rds",
  activated_input_rds = "path/to/Publication_RDS/Activated_EBV_integrated_seurat.rds",
  
  # Output directories
  baseline_output_dir = "path/to/Publication_data/EBV_baseline/Clustering",
  activated_output_dir = "path/to/Publication_data/EBV_activated/Clustering",
  
  # Common UMAP settings
  reduction = "umap.harmony",
  assay = "SCT",
  
  # Baseline cluster column options.
  # The script will use the first one found.
  baseline_cluster_col_options = c("cluster_new", "new_cluster"),
  
  # Activated annotation columns
  harmony_cluster_col = "harmony_clusters",
  activated_matched_cluster_col = "matched_cluster",
  activated_new_cluster_col = "new_cluster",
  activated_celltype_col = "celltype",
  
  # Cytotoxicity score column
  cytotoxicity_col = "Cytotoxicity_score",
  
  # Output plot names
  baseline_cluster_umap_file = "umap_new_clusters.png",
  baseline_cytotoxicity_umap_file = "umap_cytotoxicity.png",
  activated_cluster_umap_file = "umap_new_clusters.png",
  
  # Plot dimensions
  cluster_umap_width = 9,
  cluster_umap_height = 8,
  cytotoxicity_umap_width = 9,
  cytotoxicity_umap_height = 8,
  
  cluster_umap_dpi = 500,
  cytotoxicity_umap_dpi = 300,
  background = "transparent",
  
  session_info_file = "path/to/Publication_data/cluster_cytotoxicity_umaps_sessionInfo.txt"
)


# ----------------------------- #
# 2. Colours and annotation maps
# ----------------------------- #

baseline_cluster_cols <- c(
  "0" = "#D89000",
  "1" = "#4DAFE8",
  "2" = "#009A70",
  "3" = "#E6D800",
  "4" = "#006FB0",
  "5" = "#D84A00",
  "6" = "#C76AA3"
)

activated_cluster_cols <- c(
  "0" = "#D89000",
  "1" = "#4DAFE8",
  "8" = "#c599ef",
  "2" = "#009A70",
  "3" = "#E6D800",
  "5" = "#D84A00",
  "4" = "#006FB0",
  "7" = "#9acd84",
  "6" = "#C76AA3"
)

cytotoxicity_cols <- c(
  "#E6F2FF",
  "#B3D9FF",
  "#7FB3FF",
  "#9B6EDB",
  "#D65DB1",
  "#F768A1",
  "#F89540",
  "#D7301F"
)

# Activated mapping from harmony_clusters to matched_cluster.
activated_harmony_to_matched <- c(
  "0" = "0",
  "1" = "2",
  "2" = "1",
  "3" = "7",
  "4" = "3",
  "5" = "5",
  "6" = "6",
  "7" = "4",
  "8" = "8"
)

# Activated mapping from matched_cluster to new_cluster.
activated_matched_to_new <- c(
  "2" = "0",
  "0" = "1",
  "8" = "8",
  "1" = "2",
  "3" = "3",
  "4" = "4",
  "6" = "5",
  "7" = "7",
  "5" = "6"
)

# Activated matched cluster labels.
activated_matched_to_celltype <- c(
  "0" = "Naive/early TCM",
  "1" = "TEM",
  "8" = "TEM",
  "7" = "T activated EM",
  "4" = "T activated CM",
  "6" = "T activated EM",
  "2" = "T Late EM",
  "3" = "CTL",
  "5" = "T innate-like"
)


# ----------------------------- #
# 3. Helper functions
# ----------------------------- #

create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}


create_parent_dir <- function(path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
}


load_seurat_object <- function(path) {
  
  if (!file.exists(path)) {
    stop("Input RDS file does not exist: ", path)
  }
  
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS does not contain a Seurat object: ", path)
  }
  
  obj
}


check_reduction <- function(obj, reduction, dataset_label) {
  
  if (!reduction %in% Reductions(obj)) {
    stop(
      "Reduction '", reduction, "' not found in ", dataset_label,
      " object. Available reductions: ",
      paste(Reductions(obj), collapse = ", ")
    )
  }
  
  invisible(TRUE)
}


check_assay <- function(obj, assay, dataset_label) {
  
  if (!assay %in% Assays(obj)) {
    stop(
      "Assay '", assay, "' not found in ", dataset_label,
      " object. Available assays: ",
      paste(Assays(obj), collapse = ", ")
    )
  }
  
  invisible(TRUE)
}


get_first_existing_metadata_col <- function(obj, candidate_cols, dataset_label) {
  
  existing_cols <- intersect(candidate_cols, colnames(obj@meta.data))
  
  if (length(existing_cols) == 0) {
    stop(
      "None of the candidate cluster columns were found in the ",
      dataset_label,
      " object: ",
      paste(candidate_cols, collapse = ", ")
    )
  }
  
  existing_cols[1]
}


plot_cluster_umap <- function(
    obj,
    group_col,
    cluster_cols,
    reduction,
    output_file,
    title = NULL,
    alpha = 0.7,
    point_size = 0.1,
    label_size = 5,
    width = 9,
    height = 8,
    dpi = 500,
    background = "transparent"
) {
  
  if (!group_col %in% colnames(obj@meta.data)) {
    stop("Cluster column not found in object metadata: ", group_col)
  }
  
  obj@meta.data[[group_col]] <- factor(
    as.character(obj@meta.data[[group_col]]),
    levels = names(cluster_cols)
  )
  
  p <- DimPlot(
    object = obj,
    reduction = reduction,
    group.by = group_col,
    label = TRUE,
    pt.size = point_size,
    raster = FALSE,
    label.box = TRUE,
    alpha = alpha,
    stroke.size = 0.4,
    repel = TRUE,
    cols = cluster_cols,
    label.size = label_size
  )
  
  if (!is.null(title)) {
    p <- p + ggtitle(title)
  }
  
  ggsave(
    filename = output_file,
    plot = p,
    height = height,
    width = width,
    dpi = dpi,
    bg = background
  )
  
  message("Saved: ", output_file)
  
  invisible(p)
}


summarise_cytotoxicity_score <- function(obj, cytotoxicity_col) {
  
  score <- obj@meta.data[[cytotoxicity_col]]
  
  tibble(
    column = cytotoxicity_col,
    class = paste(class(score), collapse = ", "),
    n_unique = length(unique(score)),
    min = min(score, na.rm = TRUE),
    median = median(score, na.rm = TRUE),
    mean = mean(score, na.rm = TRUE),
    max = max(score, na.rm = TRUE),
    sd = sd(score, na.rm = TRUE)
  )
}


plot_cytotoxicity_umap <- function(
    obj,
    cytotoxicity_col,
    assay,
    reduction,
    output_file,
    width = 9,
    height = 8,
    dpi = 300,
    background = "transparent"
) {
  
  if (!cytotoxicity_col %in% colnames(obj@meta.data)) {
    stop("Cytotoxicity score column not found: ", cytotoxicity_col)
  }
  
  check_assay(obj, assay, "baseline")
  
  DefaultAssay(obj) <- assay
  
  cyto_range <- range(obj@meta.data[[cytotoxicity_col]], na.rm = TRUE)
  
  p <- FeaturePlot(
    object = obj,
    features = cytotoxicity_col,
    reduction = reduction,
    order = FALSE,
    min.cutoff = NA,
    max.cutoff = NA
  )
  
  p <- p +
    scale_color_gradientn(
      colours = cytotoxicity_cols,
      limits = cyto_range,
      oob = scales::squish
    )
  
  ggsave(
    filename = output_file,
    plot = p,
    height = height,
    width = width,
    dpi = dpi,
    bg = background
  )
  
  message("Saved: ", output_file)
  
  invisible(p)
}


annotate_activated_clusters_if_needed <- function(obj, cfg) {
  
  harmony_col <- cfg$harmony_cluster_col
  matched_col <- cfg$activated_matched_cluster_col
  new_col <- cfg$activated_new_cluster_col
  celltype_col <- cfg$activated_celltype_col
  
  if (!harmony_col %in% colnames(obj@meta.data)) {
    stop("Activated object is missing required column: ", harmony_col)
  }
  
  # Rebuild matched_cluster only if missing.
  if (!matched_col %in% colnames(obj@meta.data)) {
    obj@meta.data[[matched_col]] <- unname(
      activated_harmony_to_matched[
        as.character(obj@meta.data[[harmony_col]])
      ]
    )
  }
  
  # Rebuild new_cluster only if missing.
  if (!new_col %in% colnames(obj@meta.data)) {
    obj@meta.data[[new_col]] <- unname(
      activated_matched_to_new[
        as.character(obj@meta.data[[matched_col]])
      ]
    )
  }
  
  obj@meta.data[[new_col]] <- factor(
    as.character(obj@meta.data[[new_col]]),
    levels = names(activated_cluster_cols)
  )
  
  # Rebuild celltype labels only if missing.
  if (!celltype_col %in% colnames(obj@meta.data)) {
    obj@meta.data[[celltype_col]] <- unname(
      activated_matched_to_celltype[
        as.character(obj@meta.data[[matched_col]])
      ]
    )
  }
  
  obj
}


# ----------------------------- #
# 4. Run baseline plots
# ----------------------------- #

create_dir(config$baseline_output_dir)
create_dir(config$activated_output_dir)
create_parent_dir(config$session_info_file)

baseline_obj <- load_seurat_object(config$baseline_input_rds)

check_reduction(
  obj = baseline_obj,
  reduction = config$reduction,
  dataset_label = "baseline"
)

baseline_cluster_col <- get_first_existing_metadata_col(
  obj = baseline_obj,
  candidate_cols = config$baseline_cluster_col_options,
  dataset_label = "baseline"
)

baseline_cluster_umap_path <- file.path(
  config$baseline_output_dir,
  config$baseline_cluster_umap_file
)

baseline_cluster_plot <- plot_cluster_umap(
  obj = baseline_obj,
  group_col = baseline_cluster_col,
  cluster_cols = baseline_cluster_cols,
  reduction = config$reduction,
  output_file = baseline_cluster_umap_path,
  title = NULL,
  alpha = 0.7,
  point_size = 0.1,
  label_size = 5,
  width = config$cluster_umap_width,
  height = config$cluster_umap_height,
  dpi = config$cluster_umap_dpi,
  background = config$background
)

cytotoxicity_summary <- summarise_cytotoxicity_score(
  obj = baseline_obj,
  cytotoxicity_col = config$cytotoxicity_col
)

message("\nCytotoxicity score summary:")
print(cytotoxicity_summary)

baseline_cytotoxicity_umap_path <- file.path(
  config$baseline_output_dir,
  config$baseline_cytotoxicity_umap_file
)

baseline_cytotoxicity_plot <- plot_cytotoxicity_umap(
  obj = baseline_obj,
  cytotoxicity_col = config$cytotoxicity_col,
  assay = config$assay,
  reduction = config$reduction,
  output_file = baseline_cytotoxicity_umap_path,
  width = config$cytotoxicity_umap_width,
  height = config$cytotoxicity_umap_height,
  dpi = config$cytotoxicity_umap_dpi,
  background = config$background
)


# ----------------------------- #
# 5. Run activated cluster plot
# ----------------------------- #

activated_obj <- load_seurat_object(config$activated_input_rds)

check_reduction(
  obj = activated_obj,
  reduction = config$reduction,
  dataset_label = "activated"
)

activated_obj <- annotate_activated_clusters_if_needed(
  obj = activated_obj,
  cfg = config
)

activated_cluster_umap_path <- file.path(
  config$activated_output_dir,
  config$activated_cluster_umap_file
)

activated_cluster_plot <- plot_cluster_umap(
  obj = activated_obj,
  group_col = config$activated_new_cluster_col,
  cluster_cols = activated_cluster_cols,
  reduction = config$reduction,
  output_file = activated_cluster_umap_path,
  title = NULL,
  alpha = 0.5,
  point_size = 0.1,
  label_size = 5,
  width = config$cluster_umap_width,
  height = config$cluster_umap_height,
  dpi = config$cluster_umap_dpi,
  background = config$background
)


# ----------------------------- #
# 6. Save session information
# ----------------------------- #

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Baseline cluster column used:",
    baseline_cluster_col,
    "",
    "Baseline cytotoxicity summary:",
    capture.output(print(cytotoxicity_summary)),
    "",
    "Activated cluster table:",
    capture.output(
      print(
        table(
          activated_obj@meta.data[[config$activated_matched_cluster_col]],
          activated_obj@meta.data[[config$activated_celltype_col]],
          useNA = "ifany"
        )
      )
    ),
    "",
    "Output files:",
    baseline_cluster_umap_path,
    baseline_cytotoxicity_umap_path,
    activated_cluster_umap_path,
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nCluster and cytotoxicity UMAP workflow complete.")
message("Baseline cluster UMAP: ", baseline_cluster_umap_path)
message("Baseline cytotoxicity UMAP: ", baseline_cytotoxicity_umap_path)
message("Activated cluster UMAP: ", activated_cluster_umap_path)
message("Session info: ", config$session_info_file)
