#!/usr/bin/env Rscript

# ==============================================================================
# Canonical marker FeaturePlots for baseline and activated EBV TCR objects
# ==============================================================================
#
# Purpose:
#   This script generates canonical marker UMAP FeaturePlots for:
#     1. baseline EBV TCR object, and
#     2. activated EBV TCR object.
#
#   It starts from the final publication-ready RDS objects generated by the
#   baseline/activated integration workflow:
#     - 5_baseline_EBV_cluster_reannotated.rds
#     - 3_activated_EBV_reannotated.rds
#
#   It saves one PNG per object showing the same canonical marker panel:
#     CCR7, IL7R, TCF7, CD28, GZMK, CD69, IL2RA, GZMB
#
# Notes:
#   - Paths are intentionally generic for GitHub.
#   - Update the config block before running.
#   - The script checks that the requested assay, reduction, and marker genes
#     are available before plotting.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(stringr)
  library(ggplot2)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  
  # Input RDS files
  baseline_input_rds = "path/to/Publication_RDS/Baseline_EBV_integrated_seurat.rds",
  activated_input_rds = "path/to/Publication_RDS/Activated_EBV_integrated_seurat.rds",
  
  # Output directories
  baseline_output_dir = "path/to/Publication_data/EBV_baseline/Clustering",
  activated_output_dir = "path/to/Publication_data/EBV_activated/Clustering",
  
  # FeaturePlot settings
  assay = "SCT",
  reduction = "umap.harmony",
  
  markers = c(
    "CCR7",
    "IL7R",
    "TCF7",
    "CD28",
    "GZMK",
    "CD69",
    "IL2RA",
    "GZMB"
  ),
  
  ncol = 4,
  point_size = 0.1,
  low_colour = "#F2F2F2",
  high_colour = "#D7301F",
  
  plot_width = 20,
  plot_height = 8,
  dpi = 300,
  background = "transparent",
  
  session_info_file = "path/to/Publication_data/canonical_marker_featureplots_sessionInfo.txt"
)


# ----------------------------- #
# 2. Helper functions
# ----------------------------- #

create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}


create_parent_dir <- function(path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
}


load_seurat_object <- function(path) {
  
  if (!file.exists(path)) {
    stop("Input RDS file does not exist: ", path)
  }
  
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS does not contain a Seurat object: ", path)
  }
  
  obj
}


check_assay_and_reduction <- function(obj, assay, reduction, dataset_label) {
  
  if (!assay %in% Assays(obj)) {
    stop(
      "Assay '", assay, "' not found in ", dataset_label, " object. Available assays: ",
      paste(Assays(obj), collapse = ", ")
    )
  }
  
  if (!reduction %in% Reductions(obj)) {
    stop(
      "Reduction '", reduction, "' not found in ", dataset_label, " object. Available reductions: ",
      paste(Reductions(obj), collapse = ", ")
    )
  }
  
  invisible(TRUE)
}


get_available_markers <- function(obj, markers, assay, dataset_label) {
  
  DefaultAssay(obj) <- assay
  
  available_markers <- intersect(markers, rownames(obj[[assay]]))
  missing_markers <- setdiff(markers, available_markers)
  
  if (length(missing_markers) > 0) {
    warning(
      "The following markers were not found in the ", dataset_label,
      " object and will be skipped: ",
      paste(missing_markers, collapse = ", ")
    )
  }
  
  if (length(available_markers) == 0) {
    stop("None of the requested markers were found in the ", dataset_label, " object.")
  }
  
  available_markers
}


plot_canonical_markers <- function(
    input_rds,
    output_dir,
    output_filename,
    dataset_label,
    cfg
) {
  
  message("\n========================================")
  message("Generating canonical marker FeaturePlot: ", dataset_label)
  message("========================================")
  
  create_dir(output_dir)
  
  obj <- load_seurat_object(input_rds)
  
  check_assay_and_reduction(
    obj = obj,
    assay = cfg$assay,
    reduction = cfg$reduction,
    dataset_label = dataset_label
  )
  
  available_markers <- get_available_markers(
    obj = obj,
    markers = cfg$markers,
    assay = cfg$assay,
    dataset_label = dataset_label
  )
  
  DefaultAssay(obj) <- cfg$assay
  
  p <- FeaturePlot(
    object = obj,
    features = available_markers,
    reduction = cfg$reduction,
    ncol = cfg$ncol,
    cols = c(cfg$low_colour, cfg$high_colour),
    pt.size = cfg$point_size,
    order = TRUE
  )
  
  output_file <- file.path(output_dir, output_filename)
  
  ggsave(
    filename = output_file,
    plot = p,
    height = cfg$plot_height,
    width = cfg$plot_width,
    dpi = cfg$dpi,
    bg = cfg$background
  )
  
  message("Saved: ", output_file)
  
  invisible(list(
    object = obj,
    plot = p,
    output_file = output_file,
    markers_plotted = available_markers
  ))
}


# ----------------------------- #
# 3. Run plotting workflow
# ----------------------------- #

create_dir(config$baseline_output_dir)
create_dir(config$activated_output_dir)
create_parent_dir(config$session_info_file)

baseline_result <- plot_canonical_markers(
  input_rds = config$baseline_input_rds,
  output_dir = config$baseline_output_dir,
  output_filename = "canonical_subset_markers_umap.png",
  dataset_label = "baseline",
  cfg = config
)

activated_result <- plot_canonical_markers(
  input_rds = config$activated_input_rds,
  output_dir = config$activated_output_dir,
  output_filename = "canonical_subset_markers_umap.png",
  dataset_label = "activated",
  cfg = config
)


# ----------------------------- #
# 4. Save session information
# ----------------------------- #

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Baseline markers plotted:",
    paste(baseline_result$markers_plotted, collapse = ", "),
    "",
    "Activated markers plotted:",
    paste(activated_result$markers_plotted, collapse = ", "),
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nCanonical marker FeaturePlots complete.")
message("Baseline plot: ", baseline_result$output_file)
message("Activated plot: ", activated_result$output_file)
message("Session info: ", config$session_info_file)
