#!/usr/bin/env Rscript

# ==============================================================================
# Merge all processed Seurat objects and add sample metadata
# ==============================================================================
#
# Purpose:
#   This script combines the merged outputs from 6_VDJ_merge.R into one final
#   Seurat object. It:
#     1. loads multiple merged Seurat objects,
#     2. harmonises ADT assay features across objects,
#     3. normalises the harmonised ADT assays,
#     4. preserves or optionally recalculates tetramer metadata,
#     5. removes unwanted metadata columns,
#     6. optionally drops assays that make merging difficult, such as SCT,
#     7. merges all objects into one final Seurat object,
#     8. joins external sample-level metadata, and
#     9. saves summaries, logs and session information.
#
# Expected input:
#   RDS files generated by 6_VDJ_merge.R, usually named:
#     - 6_SCT_merged_all_samples.rds
#     - 6_SCT_merged_all_samples_EBV2.rds
#     - 6_SCT_merged_all_samples_GEM11.rds
#
# Notes:
#   - Tetramer calls are expected to already exist from the ADT/tetramer calling
#     script and should have been carried forward by 6_VDJ_merge.R.
#   - Global PBMC objects are assigned tetramer = "negative" by default.
#   - If you really want to re-call tetramers after ADT harmonisation, set
#     recalculate_tetramer_from_adt = TRUE for the relevant dataset.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(Matrix)
  library(dplyr)
  library(tibble)
  library(readxl)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

# Update these paths for your own project/repository.
# These inputs should be the merged outputs from 6_VDJ_merge.R.

datasets <- list(
  
  list(
    dataset_id = "global_pbmc_batch1",
    input_rds = "path/to/Global_PBMC_RDS/6_SCT_merged_all_samples.rds",
    force_tetramer_negative = TRUE,
    recalculate_tetramer_from_adt = FALSE
  ),
  
  list(
    dataset_id = "ebv_baseline_batch1",
    input_rds = "path/to/EBV_baseline_RDS/6_SCT_merged_all_samples.rds",
    force_tetramer_negative = FALSE,
    recalculate_tetramer_from_adt = FALSE
  ),
  
  list(
    dataset_id = "ebv_baseline_batch2",
    input_rds = "path/to/EBV_baseline_RDS/6_SCT_merged_all_samples_EBV2.rds",
    force_tetramer_negative = FALSE,
    recalculate_tetramer_from_adt = FALSE
  ),
  
  list(
    dataset_id = "global_pbmc_batch2",
    input_rds = "path/to/Global_PBMC_RDS/6_SCT_merged_all_samples_GEM11.rds",
    force_tetramer_negative = TRUE,
    recalculate_tetramer_from_adt = FALSE
  ),
  
  list(
    dataset_id = "ebv_activated",
    input_rds = "path/to/EBV_activated_RDS/6_SCT_merged_all_samples.rds",
    force_tetramer_negative = FALSE,
    recalculate_tetramer_from_adt = FALSE
  )
)


config <- list(
  
  output_dir = "path/to/Combined_RDS",
  output_rds = "path/to/Combined_RDS/7_merged_all_objects_final.rds",
  
  object_summary_csv = "path/to/Combined_RDS/7_object_merge_summary.csv",
  metadata_join_summary_csv = "path/to/Combined_RDS/7_sample_metadata_join_summary.csv",
  missing_sample_metadata_csv = "path/to/Combined_RDS/7_missing_sample_metadata.csv",
  session_info_file = "path/to/Combined_RDS/7_sessionInfo_merging_all_metadata.txt",
  
  sample_metadata_file = "path/to/Sample_information.xlsx",
  sample_metadata_sheet = 1,
  sample_metadata_join_col = "id",
  
  # Existing metadata columns with the same names as columns in the sample
  # metadata file will be removed before joining, so the sample metadata version
  # becomes the final version.
  overwrite_existing_metadata = TRUE,
  
  adt_assay = "ADT",
  harmonise_adt_assay = TRUE,
  normalise_adt_after_harmonising = TRUE,
  adt_normalization_method = "CLR",
  adt_clr_margin = 2,
  
  tetramer_col = "tetramer",
  tetramer_clr_col = "tetramer_CLR",
  negative_tetramer_label = "negative",
  
  # Used only if recalculate_tetramer_from_adt = TRUE for a dataset.
  tetramer_exclude_patterns = c(
    "HTO",
    "Hashtag",
    "^HTO_",
    "CD69",
    "CD137",
    "anti"
  ),
  
  # Optional inclusion pattern for tetramer features if re-calling tetramers.
  # Leave NULL unless you want to restrict calling to features matching specific
  # epitope/HLA names.
  tetramer_include_regex = NULL,
  
  # Metadata cleanup.
  metadata_cols_to_drop = c("old.ident", "cohort"),
  metadata_regex_to_drop = c("^DF\\.class", "^pANN"),
  
  # Drop assays that can make the final merge awkward or unnecessarily large.
  assays_to_drop_before_merge = c("SCT"),
  
  # Prefix final cell names by object source before merging all major datasets.
  # This avoids duplicate cell names when the same donor appears in different
  # experiments.
  prefix_cells_with_dataset_id = TRUE,
  object_source_col = "object_source",
  
  verbose = TRUE
)


# ----------------------------- #
# 2. Helper functions
# ----------------------------- #

create_parent_dir <- function(path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
}


create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}


load_seurat_object <- function(path) {
  
  if (!file.exists(path)) {
    stop("Input RDS file does not exist: ", path)
  }
  
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS must contain a merged Seurat object: ", path)
  }
  
  obj
}


join_assay_layers_if_possible <- function(obj, assay_name) {
  
  if (!assay_name %in% Assays(obj)) {
    return(obj)
  }
  
  obj[[assay_name]] <- tryCatch(
    {
      JoinLayers(obj[[assay_name]])
    },
    error = function(e) {
      message("Could not JoinLayers for assay ", assay_name, ": ", e$message)
      obj[[assay_name]]
    }
  )
  
  obj
}


get_assay_counts <- function(obj, assay_name) {
  
  tryCatch(
    {
      GetAssayData(obj, assay = assay_name, layer = "counts")
    },
    error = function(e) {
      suppressWarnings(
        GetAssayData(obj, assay = assay_name, slot = "counts")
      )
    }
  )
}


get_assay_data_layer <- function(obj, assay_name, layer_name) {
  
  tryCatch(
    {
      GetAssayData(obj, assay = assay_name, layer = layer_name)
    },
    error = function(e) {
      suppressWarnings(
        GetAssayData(obj, assay = assay_name, slot = layer_name)
      )
    }
  )
}


get_assay_features <- function(obj, assay_name) {
  
  if (!assay_name %in% Assays(obj)) {
    return(character())
  }
  
  rownames(obj[[assay_name]])
}


fill_missing_assay_features <- function(obj, assay_name, all_features) {
  
  if (!assay_name %in% Assays(obj)) {
    zero_counts <- Matrix(
      0,
      nrow = length(all_features),
      ncol = ncol(obj),
      sparse = TRUE,
      dimnames = list(all_features, Cells(obj))
    )
    
    obj[[assay_name]] <- CreateAssayObject(counts = zero_counts)
    return(obj)
  }
  
  counts <- get_assay_counts(obj, assay_name)
  
  current_features <- rownames(counts)
  missing_features <- setdiff(all_features, current_features)
  
  if (length(missing_features) > 0) {
    zero_counts <- Matrix(
      0,
      nrow = length(missing_features),
      ncol = ncol(counts),
      sparse = TRUE,
      dimnames = list(missing_features, colnames(counts))
    )
    
    counts <- rbind(counts, zero_counts)
  }
  
  counts <- counts[all_features, , drop = FALSE]
  
  obj[[assay_name]] <- CreateAssayObject(counts = counts)
  
  obj
}


normalise_adt <- function(obj, cfg) {
  
  if (!cfg$adt_assay %in% Assays(obj)) {
    return(obj)
  }
  
  obj <- NormalizeData(
    object = obj,
    assay = cfg$adt_assay,
    normalization.method = cfg$adt_normalization_method,
    margin = cfg$adt_clr_margin,
    verbose = cfg$verbose
  )
  
  obj
}


add_or_force_negative_tetramer <- function(obj, cfg, force = FALSE) {
  
  if (isTRUE(force) || !cfg$tetramer_col %in% colnames(obj@meta.data)) {
    obj@meta.data[[cfg$tetramer_col]] <- cfg$negative_tetramer_label
  }
  
  if (isTRUE(force) || !cfg$tetramer_clr_col %in% colnames(obj@meta.data)) {
    obj@meta.data[[cfg$tetramer_clr_col]] <- 0
  }
  
  obj
}


assign_tetramer_from_adt <- function(obj, cfg) {
  
  if (!cfg$adt_assay %in% Assays(obj)) {
    stop("ADT assay not found: ", cfg$adt_assay)
  }
  
  adt_mat <- get_assay_data_layer(
    obj = obj,
    assay_name = cfg$adt_assay,
    layer_name = "data"
  )
  
  features <- rownames(adt_mat)
  
  exclude_idx <- rep(FALSE, length(features))
  
  if (!is.null(cfg$tetramer_exclude_patterns) && length(cfg$tetramer_exclude_patterns) > 0) {
    for (pat in cfg$tetramer_exclude_patterns) {
      exclude_idx <- exclude_idx | grepl(pat, features, ignore.case = TRUE)
    }
  }
  
  keep_features <- features[!exclude_idx]
  
  if (!is.null(cfg$tetramer_include_regex) && nzchar(cfg$tetramer_include_regex)) {
    keep_features <- keep_features[
      grepl(cfg$tetramer_include_regex, keep_features, ignore.case = TRUE)
    ]
  }
  
  if (length(keep_features) == 0) {
    stop("No ADT features left for tetramer calling.")
  }
  
  sub_mat <- as.matrix(adt_mat[keep_features, , drop = FALSE])
  
  all_zero <- colSums(sub_mat != 0, na.rm = TRUE) == 0
  
  max_idx <- max.col(t(sub_mat), ties.method = "first")
  tetramer_names <- keep_features[max_idx]
  tetramer_clr <- sub_mat[cbind(max_idx, seq_len(ncol(sub_mat)))]
  
  tetramer_names[all_zero] <- cfg$negative_tetramer_label
  tetramer_clr[all_zero] <- 0
  
  obj@meta.data[[cfg$tetramer_col]] <- tetramer_names
  obj@meta.data[[cfg$tetramer_clr_col]] <- tetramer_clr
  
  obj
}


remove_metadata_columns <- function(obj, cfg) {
  
  meta_cols <- colnames(obj@meta.data)
  
  regex_cols <- unique(unlist(lapply(
    cfg$metadata_regex_to_drop,
    function(pattern) grep(pattern, meta_cols, value = TRUE)
  )))
  
  cols_to_remove <- unique(c(cfg$metadata_cols_to_drop, regex_cols))
  cols_to_remove <- intersect(cols_to_remove, colnames(obj@meta.data))
  
  if (length(cols_to_remove) > 0) {
    obj@meta.data <- obj@meta.data[, !colnames(obj@meta.data) %in% cols_to_remove, drop = FALSE]
  }
  
  obj
}


drop_assays <- function(obj, assays_to_drop) {
  
  for (assay_name in assays_to_drop) {
    if (assay_name %in% Assays(obj)) {
      obj[[assay_name]] <- NULL
    }
  }
  
  obj
}


prefix_cells_if_needed <- function(obj, dataset_id, cfg) {
  
  if (!isTRUE(cfg$prefix_cells_with_dataset_id)) {
    return(obj)
  }
  
  expected_prefix <- paste0(dataset_id, "_")
  
  if (!all(startsWith(Cells(obj), expected_prefix))) {
    obj <- RenameCells(obj, add.cell.id = dataset_id)
  }
  
  obj
}


add_object_source <- function(obj, dataset_id, cfg) {
  
  obj@meta.data[[cfg$object_source_col]] <- dataset_id
  
  obj
}


harmonise_metadata_columns <- function(obj_list) {
  
  all_cols <- Reduce(union, lapply(obj_list, function(obj) colnames(obj@meta.data)))
  
  obj_list <- lapply(obj_list, function(obj) {
    
    missing_cols <- setdiff(all_cols, colnames(obj@meta.data))
    
    if (length(missing_cols) > 0) {
      for (col in missing_cols) {
        obj@meta.data[[col]] <- NA
      }
    }
    
    obj@meta.data <- obj@meta.data[, all_cols, drop = FALSE]
    
    obj
  })
  
  obj_list
}


make_object_summary <- function(obj, dataset_id, input_rds, cfg) {
  
  tibble(
    dataset_id = dataset_id,
    input_rds = input_rds,
    n_cells = ncol(obj),
    n_features_RNA = if ("RNA" %in% Assays(obj)) nrow(obj[["RNA"]]) else NA_integer_,
    n_features_ADT = if (cfg$adt_assay %in% Assays(obj)) nrow(obj[[cfg$adt_assay]]) else NA_integer_,
    has_tetramer_col = cfg$tetramer_col %in% colnames(obj@meta.data),
    has_tetramer_clr_col = cfg$tetramer_clr_col %in% colnames(obj@meta.data),
    n_metadata_cols = ncol(obj@meta.data)
  )
}


process_one_object <- function(dataset_cfg, cfg) {
  
  dataset_id <- dataset_cfg$dataset_id
  
  message("\nLoading object: ", dataset_id)
  
  obj <- load_seurat_object(dataset_cfg$input_rds)
  
  obj <- add_object_source(obj, dataset_id, cfg)
  
  if (isTRUE(cfg$harmonise_adt_assay)) {
    obj <- join_assay_layers_if_possible(obj, cfg$adt_assay)
  }
  
  obj <- add_or_force_negative_tetramer(
    obj = obj,
    cfg = cfg,
    force = isTRUE(dataset_cfg$force_tetramer_negative)
  )
  
  if (isTRUE(dataset_cfg$recalculate_tetramer_from_adt)) {
    obj <- assign_tetramer_from_adt(obj, cfg)
  }
  
  obj <- remove_metadata_columns(obj, cfg)
  obj <- drop_assays(obj, cfg$assays_to_drop_before_merge)
  
  obj <- prefix_cells_if_needed(
    obj = obj,
    dataset_id = dataset_id,
    cfg = cfg
  )
  
  list(
    obj = obj,
    summary = make_object_summary(
      obj = obj,
      dataset_id = dataset_id,
      input_rds = dataset_cfg$input_rds,
      cfg = cfg
    )
  )
}


harmonise_adt_features_across_objects <- function(obj_list, cfg) {
  
  if (!isTRUE(cfg$harmonise_adt_assay)) {
    return(obj_list)
  }
  
  adt_features <- lapply(obj_list, get_assay_features, assay_name = cfg$adt_assay)
  adt_union <- Reduce(union, adt_features)
  
  if (length(adt_union) == 0) {
    message("No ADT features found across objects; skipping ADT harmonisation.")
    return(obj_list)
  }
  
  message("Harmonising ADT features across objects. Total ADT features: ", length(adt_union))
  
  obj_list <- lapply(
    obj_list,
    fill_missing_assay_features,
    assay_name = cfg$adt_assay,
    all_features = adt_union
  )
  
  if (isTRUE(cfg$normalise_adt_after_harmonising)) {
    obj_list <- lapply(obj_list, normalise_adt, cfg = cfg)
  }
  
  obj_list
}


merge_all_objects <- function(obj_list) {
  
  if (length(obj_list) == 0) {
    stop("No objects supplied for merging.")
  }
  
  if (length(obj_list) == 1) {
    return(obj_list[[1]])
  }
  
  merge(
    x = obj_list[[1]],
    y = obj_list[-1],
    add.cell.ids = NULL
  )
}


read_sample_metadata <- function(cfg) {
  
  if (!file.exists(cfg$sample_metadata_file)) {
    stop("Sample metadata file does not exist: ", cfg$sample_metadata_file)
  }
  
  sample_df <- readxl::read_xlsx(
    path = cfg$sample_metadata_file,
    sheet = cfg$sample_metadata_sheet
  ) %>%
    as.data.frame()
  
  if (!cfg$sample_metadata_join_col %in% colnames(sample_df)) {
    stop(
      "Sample metadata file does not contain join column: ",
      cfg$sample_metadata_join_col
    )
  }
  
  sample_df <- sample_df %>%
    group_by(.data[[cfg$sample_metadata_join_col]]) %>%
    slice(1) %>%
    ungroup()
  
  sample_df
}


join_sample_metadata <- function(obj, sample_df, cfg) {
  
  join_col <- cfg$sample_metadata_join_col
  
  if (!join_col %in% colnames(obj@meta.data)) {
    stop("Seurat metadata does not contain join column: ", join_col)
  }
  
  meta <- obj@meta.data %>%
    rownames_to_column("cell")
  
  existing_overlap <- intersect(colnames(meta), colnames(sample_df))
  existing_overlap <- setdiff(existing_overlap, c("cell", join_col))
  
  if (isTRUE(cfg$overwrite_existing_metadata) && length(existing_overlap) > 0) {
    meta <- meta %>%
      select(-all_of(existing_overlap))
  }
  
  sample_ids_before <- sort(unique(as.character(meta[[join_col]])))
  sample_ids_in_sheet <- sort(unique(as.character(sample_df[[join_col]])))
  
  missing_from_sheet <- setdiff(sample_ids_before, sample_ids_in_sheet)
  
  meta_joined <- meta %>%
    left_join(sample_df, by = join_col) %>%
    column_to_rownames("cell")
  
  obj@meta.data <- meta_joined
  
  join_summary <- tibble(
    n_cells = ncol(obj),
    n_unique_object_ids = length(sample_ids_before),
    n_unique_metadata_ids = length(sample_ids_in_sheet),
    n_object_ids_missing_from_metadata = length(missing_from_sheet),
    metadata_file = cfg$sample_metadata_file,
    join_col = join_col
  )
  
  missing_df <- tibble(
    missing_id = missing_from_sheet
  )
  
  list(
    obj = obj,
    join_summary = join_summary,
    missing_metadata = missing_df
  )
}


# ----------------------------- #
# 3. Run pipeline
# ----------------------------- #

create_dir(config$output_dir)
create_parent_dir(config$output_rds)
create_parent_dir(config$object_summary_csv)
create_parent_dir(config$metadata_join_summary_csv)
create_parent_dir(config$missing_sample_metadata_csv)
create_parent_dir(config$session_info_file)

processed <- lapply(
  datasets,
  process_one_object,
  cfg = config
)

obj_list <- lapply(processed, `[[`, "obj")
names(obj_list) <- vapply(datasets, `[[`, character(1), "dataset_id")

object_summary_df <- bind_rows(lapply(processed, `[[`, "summary"))

# Harmonise ADT assays across all objects after all objects are loaded.
obj_list <- harmonise_adt_features_across_objects(
  obj_list = obj_list,
  cfg = config
)

# Rebuild the summary after ADT harmonisation.
object_summary_df_after_adt <- bind_rows(
  Map(
    function(obj, dataset_cfg) {
      make_object_summary(
        obj = obj,
        dataset_id = dataset_cfg$dataset_id,
        input_rds = dataset_cfg$input_rds,
        cfg = config
      ) %>%
        mutate(summary_stage = "after_adt_harmonisation")
    },
    obj_list,
    datasets
  )
)

object_summary_df <- object_summary_df %>%
  mutate(summary_stage = "before_adt_harmonisation") %>%
  bind_rows(object_summary_df_after_adt)

# Make metadata columns consistent before final merge.
obj_list <- harmonise_metadata_columns(obj_list)

message("\nMerging all processed objects...")
merged_obj <- merge_all_objects(obj_list)

message("Merged object contains ", ncol(merged_obj), " cells.")

# Join sample-level metadata.
message("\nReading and joining sample metadata...")
sample_df <- read_sample_metadata(config)

metadata_join <- join_sample_metadata(
  obj = merged_obj,
  sample_df = sample_df,
  cfg = config
)

merged_obj <- metadata_join$obj

# Save outputs.
saveRDS(merged_obj, config$output_rds)

write.csv(
  object_summary_df,
  config$object_summary_csv,
  row.names = FALSE
)

write.csv(
  metadata_join$join_summary,
  config$metadata_join_summary_csv,
  row.names = FALSE
)

write.csv(
  metadata_join$missing_metadata,
  config$missing_sample_metadata_csv,
  row.names = FALSE
)

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Datasets:",
    capture.output(str(datasets)),
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nSaved final merged object to: ", config$output_rds)
message("Saved object summary to: ", config$object_summary_csv)
message("Saved metadata join summary to: ", config$metadata_join_summary_csv)
message("Saved missing metadata IDs to: ", config$missing_sample_metadata_csv)
message("Saved session info to: ", config$session_info_file)

message("\nAll object merging and sample metadata integration complete.")