#!/usr/bin/env Rscript

# ==============================================================================
# Generate combined TCR/VDJ files and EBV CD8-only Seurat RDS
# ==============================================================================
#
# Purpose:
#   This script starts from the final combined Seurat object generated by
#   7_Merging_all_metadata.R. It:
#     1. scans Cell Ranger VDJ-T output folders,
#     2. combines filtered_contig_annotations.csv files across samples,
#     3. creates a stable VDJ barcode key for matching VDJ rows to Seurat cells,
#     4. optionally plots tetramer CLR distributions for multimer-positive cells,
#     5. applies tetramer-specific CLR cutoffs to remove weak/sticky staining,
#     6. subsets EBV CD8 samples while excluding CD4 batches,
#     7. exports combined and EBV-only VDJ CSV files, and
#     8. saves final filtered Seurat RDS objects.
#
# Expected input:
#   - Combined Seurat object from 7_Merging_all_metadata.R.
#   - Cell Ranger VDJ-T output directories containing:
#       filtered_contig_annotations.csv
#
# Notes:
#   - This script assumes the Seurat metadata contains an `id` column identifying
#     the original sample ID.
#   - The final Seurat cell names may have extra dataset prefixes from script 7.
#     Therefore, VDJ matching is done using `vdj_barcode_key`, not directly from
#     colnames(merged_obj).
#   - Tetramer calls are expected to already exist from earlier ADT processing.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(readr)
  library(readxl)
  library(stringr)
  library(ggplot2)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  
  # Input from script 7.
  input_rds = "path/to/Combined_RDS/7_merged_all_objects_final.rds",
  
  # Optional sample metadata file. This is only used to fill the sample column
  # if it is missing or partially empty.
  sample_metadata_file = "path/to/Sample_information.xlsx",
  sample_metadata_sheet = 1,
  
  output_dir = "path/to/Combined",
  output_rds_dir = "path/to/Combined_RDS",
  output_vdj_dir = "path/to/VDJ_analysis",
  output_plot_dir = "path/to/Combined/tetramer_CLR_QC",
  
  output_all_with_vdj_key_rds = "path/to/Combined_RDS/8_merged_all_objects_with_vdj_key.rds",
  output_all_filtered_rds = "path/to/Combined_RDS/8_merged_all_objects_final_filtered.rds",
  output_ebv_cd8_rds = "path/to/Combined_RDS/8_merged_EBV_CD8_samples_only.rds",
  
  output_all_vdj_csv = "path/to/VDJ_analysis/8_merged_all_vdjs.csv",
  output_ebv_vdj_csv = "path/to/VDJ_analysis/8_merged_ebv_vdjs.csv",
  
  output_vdj_scan_summary_csv = "path/to/VDJ_analysis/8_vdj_scan_summary.csv",
  output_tetramer_cutoff_summary_csv = "path/to/VDJ_analysis/8_tetramer_cutoff_summary.csv",
  output_missing_vdj_csv = "path/to/VDJ_analysis/8_samples_without_vdj.csv",
  session_info_file = "path/to/VDJ_analysis/8_sessionInfo_generate_TCR_combined_rds.txt",
  
  # Metadata columns.
  id_col = "id",
  sample_col = "sample",
  batch_col = "batch",
  multimer_col = "multimer",
  
  tetramer_col = "tetramer",
  tetramer_clr_col = "tetramer_CLR",
  tetramer_raw_col = "tetramer_raw",
  tetramer_pre_cutoff_col = "tetramer_pre_cutoff",
  tetramer_cutoff_col = "tetramer_cutoff",
  tetramer_pass_cutoff_col = "tetramer_pass_cutoff",
  
  vdj_barcode_key_col = "vdj_barcode_key",
  raw_cell_barcode_col = "raw_cell_barcode",
  
  negative_tetramer_label = "negative",
  
  # VDJ scanning. Add or remove sources as needed.
  # The search patterns should point to folders ending in /vdj_t.
  vdj_sources = list(
    list(
      source_id = "main_gem",
      base_dir = "path/to/cellranger/main_base",
      search_patterns = c(
        "GEM*/GEM*/outs/per_sample_outs/*/vdj_t"
      )
    ),
    list(
      source_id = "new_global_batches",
      base_dir = "path/to/cellranger/New_global_batches",
      search_patterns = c(
        "*/outs/per_sample_outs/*/vdj_t",
        "*/*/outs/per_sample_outs/*/vdj_t"
      )
    ),
    list(
      source_id = "ebv_data",
      base_dir = "path/to/cellranger/EBV_data",
      search_patterns = c(
        "*/outs/per_sample_outs/*/vdj_t",
        "*/*/outs/per_sample_outs/*/vdj_t"
      )
    ),
    list(
      source_id = "new_ebv_data",
      base_dir = "path/to/cellranger/new_EBV_data",
      search_patterns = c(
        "*/outs/per_sample_outs/*/vdj_t",
        "*/*/outs/per_sample_outs/*/vdj_t"
      )
    ),
    list(
      source_id = "lcl_t_cell_data",
      base_dir = "path/to/cellranger/LCL_T_cell_data",
      search_patterns = c(
        "*/outs/per_sample_outs/*/vdj_t",
        "*/*/outs/per_sample_outs/*/vdj_t"
      )
    )
  ),
  
  vdj_file = "filtered_contig_annotations.csv",
  vdj_barcode_col = "barcode",
  
  # Remove duplicated VDJ rows if the same Cell Ranger output is found more than
  # once through overlapping search paths.
  deduplicate_vdj_rows = TRUE,
  
  # Tetramer naming fixes.
  tetramer_replacements = c(
    "^RPPK" = "RPQK"
  ),
  
  # Plotting.
  make_tetramer_clr_plots = TRUE,
  plot_only_multimer_positive = TRUE,
  multimer_positive_label = "positive",
  plot_tetramers_per_page = 6,
  plot_width = 25,
  plot_height = 20,
  plot_dpi = 300,
  
  tetramer_order = c(
    "GLCT", "CLGG", "FLYA", "YLQQ", "LLDF", "GILG", "SSCS*", "AVFD*",
    "ATIG", "PYLF", "TYGP", "TYSA", "TYPV", "RYGF", "RPQG", "RPQK*",
    "RPPI", "LPRR", "YNLR*", "FLRG", "QAKW", "RAKF", "ELRS", "HPVG",
    "MGSL", "YPLH*", "EPLP*", "LPFE", "LEKA", "FENI", "IEDP", "VEDL", "QEIR"
  ),
  
  # EBV CD8 subset.
  # This reproduces the original logic:
  #   1. identify samples where batch contains GEMEBV,
  #   2. keep all cells from those samples,
  #   3. remove cells from batches containing CD4.
  ebv_batch_regex = "GEMEBV",
  exclude_batch_regex = "CD4",
  subset_ebv_by_sample = TRUE,
  
  verbose = TRUE
)


# ----------------------------- #
# 2. Tetramer cutoff table
# ----------------------------- #

cutoff_df <- tribble(
  ~tetramer, ~cutoff,
  "GLCT",    2.5,
  "CLGG",    2.5,
  "FLYA",    3,
  "YLQQ",    2,
  "LLDF",    2.5,
  "GILG",    3,
  "SSCS*",   2.5,
  "AVFD*",   3,
  "ATIG",    2,
  "PYLF",    3,
  "TYGP",    2.5,
  "TYSA",    2,
  "TYPV",    4,
  "RYGF",    1,
  "RPQG",    3,
  "RPQK*",   2.5,
  "RPPK*",   1.5,
  "RPPI",    2.5,
  "LPRR",    3,
  "YNLR*",   3,
  "FLRG",    3,
  "QAKW",    3,
  "RAKF",    3,
  "ELRS",    4,
  "HPVG",    2,
  "MGSL",    2,
  "YPLH*",   2,
  "EPLP*",   3,
  "LPFE",    2,
  "LEKA",    2,
  "FENI",    2,
  "IEDP",    5,
  "VEDL",    4.5,
  "QEIR",    5
)


# ----------------------------- #
# 3. Helper functions
# ----------------------------- #

create_dir <- function(path) {
  dir.create(path, recursive = TRUE, showWarnings = FALSE)
}


create_parent_dir <- function(path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
}


escape_regex <- function(x) {
  gsub("([][{}()+*^$|\\\\?.])", "\\\\\\1", x)
}


load_combined_object <- function(input_rds) {
  
  if (!file.exists(input_rds)) {
    stop("Input RDS file does not exist: ", input_rds)
  }
  
  obj <- readRDS(input_rds)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS must contain a Seurat object.")
  }
  
  obj
}


apply_tetramer_replacements_vector <- function(x, replacements) {
  
  x <- as.character(x)
  
  if (is.null(replacements) || length(replacements) == 0) {
    return(x)
  }
  
  for (pattern in names(replacements)) {
    replacement <- replacements[[pattern]]
    
    x <- ifelse(
      !is.na(x) & grepl(pattern, x),
      sub(pattern, replacement, x),
      x
    )
  }
  
  x
}


ensure_sample_column <- function(obj, cfg) {
  
  meta <- obj@meta.data
  
  if (!cfg$id_col %in% colnames(meta)) {
    stop("Metadata does not contain required id column: ", cfg$id_col)
  }
  
  sample_missing <- !cfg$sample_col %in% colnames(meta) ||
    all(is.na(meta[[cfg$sample_col]]))
  
  if (!sample_missing) {
    return(obj)
  }
  
  if (!file.exists(cfg$sample_metadata_file)) {
    message(
      "Sample column is missing/empty, but sample metadata file was not found. ",
      "Using id as sample."
    )
    
    obj@meta.data[[cfg$sample_col]] <- obj@meta.data[[cfg$id_col]]
    return(obj)
  }
  
  message("Filling sample column from sample metadata file.")
  
  sample_df <- readxl::read_xlsx(
    path = cfg$sample_metadata_file,
    sheet = cfg$sample_metadata_sheet
  ) %>%
    as.data.frame()
  
  required_cols <- c(cfg$id_col, cfg$sample_col)
  
  if (!all(required_cols %in% colnames(sample_df))) {
    message(
      "Sample metadata file does not contain both id and sample columns. ",
      "Using id as sample."
    )
    
    obj@meta.data[[cfg$sample_col]] <- obj@meta.data[[cfg$id_col]]
    return(obj)
  }
  
  sample_map <- sample_df %>%
    select(all_of(required_cols)) %>%
    distinct(.data[[cfg$id_col]], .keep_all = TRUE)
  
  meta_joined <- meta %>%
    rownames_to_column("cell") %>%
    left_join(sample_map, by = cfg$id_col) %>%
    column_to_rownames("cell")
  
  obj@meta.data <- meta_joined
  
  obj
}


extract_raw_cell_barcode <- function(cell, sample_id) {
  
  cell <- as.character(cell)
  sample_id <- as.character(sample_id)
  
  if (is.na(sample_id) || !nzchar(sample_id)) {
    return(sub("^.*_", "", cell))
  }
  
  # This handles both:
  #   sample_barcode
  #   dataset_sample_barcode
  pattern <- paste0("^.*", escape_regex(sample_id), "_")
  raw <- sub(pattern, "", cell)
  
  raw
}


add_vdj_barcode_key <- function(obj, cfg) {
  
  meta <- obj@meta.data
  
  if (!cfg$id_col %in% colnames(meta)) {
    stop("Cannot create VDJ barcode key because id column is missing: ", cfg$id_col)
  }
  
  cells <- rownames(meta)
  sample_ids <- as.character(meta[[cfg$id_col]])
  
  raw_barcodes <- mapply(
    FUN = extract_raw_cell_barcode,
    cell = cells,
    sample_id = sample_ids,
    USE.NAMES = FALSE
  )
  
  valid_sample <- !is.na(sample_ids) & nzchar(sample_ids)
  
  vdj_keys <- ifelse(
    valid_sample,
    paste0(sample_ids, "_", raw_barcodes),
    NA_character_
  )
  
  obj@meta.data[[cfg$raw_cell_barcode_col]] <- raw_barcodes
  obj@meta.data[[cfg$vdj_barcode_key_col]] <- vdj_keys
  
  obj
}


extract_batch_from_path <- function(vdj_dir, base_dir) {
  
  vdj_dir <- normalizePath(vdj_dir, winslash = "/", mustWork = FALSE)
  base_dir <- normalizePath(base_dir, winslash = "/", mustWork = FALSE)
  base_dir <- sub("/+$", "", base_dir)
  
  rel <- sub(
    pattern = paste0("^", escape_regex(base_dir), "/?"),
    replacement = "",
    x = vdj_dir
  )
  
  batch <- strsplit(rel, "/", fixed = TRUE)[[1]][1]
  
  if (is.na(batch) || batch == "") {
    batch <- NA_character_
  }
  
  batch
}


find_vdj_dirs_for_source <- function(source_cfg) {
  
  base_dir <- source_cfg$base_dir
  patterns <- source_cfg$search_patterns
  
  search_paths <- file.path(base_dir, patterns)
  
  vdj_dirs <- unique(unlist(
    lapply(search_paths, Sys.glob),
    use.names = FALSE
  ))
  
  vdj_dirs <- vdj_dirs[dir.exists(vdj_dirs)]
  
  vdj_dirs
}


read_one_vdj_dir <- function(vdj_dir, source_cfg, sample_names, cfg) {
  
  sample_name <- basename(dirname(vdj_dir))
  
  if (!sample_name %in% sample_names) {
    return(NULL)
  }
  
  vdj_file <- file.path(vdj_dir, cfg$vdj_file)
  
  if (!file.exists(vdj_file)) {
    return(list(
      data = NULL,
      summary = tibble(
        source_id = source_cfg$source_id,
        sample = sample_name,
        batch = extract_batch_from_path(vdj_dir, source_cfg$base_dir),
        vdj_dir = vdj_dir,
        status = "missing_vdj_file",
        n_rows = NA_integer_,
        n_unique_vdj_barcodes = NA_integer_,
        error_message = paste("Missing file:", vdj_file)
      )
    ))
  }
  
  dat <- tryCatch(
    readr::read_csv(vdj_file, show_col_types = FALSE),
    error = function(e) e
  )
  
  if (inherits(dat, "error")) {
    return(list(
      data = NULL,
      summary = tibble(
        source_id = source_cfg$source_id,
        sample = sample_name,
        batch = extract_batch_from_path(vdj_dir, source_cfg$base_dir),
        vdj_dir = vdj_dir,
        status = "read_failed",
        n_rows = NA_integer_,
        n_unique_vdj_barcodes = NA_integer_,
        error_message = dat$message
      )
    ))
  }
  
  if (nrow(dat) == 0) {
    return(list(
      data = NULL,
      summary = tibble(
        source_id = source_cfg$source_id,
        sample = sample_name,
        batch = extract_batch_from_path(vdj_dir, source_cfg$base_dir),
        vdj_dir = vdj_dir,
        status = "empty_file",
        n_rows = 0L,
        n_unique_vdj_barcodes = 0L,
        error_message = NA_character_
      )
    ))
  }
  
  if (!cfg$vdj_barcode_col %in% colnames(dat)) {
    return(list(
      data = NULL,
      summary = tibble(
        source_id = source_cfg$source_id,
        sample = sample_name,
        batch = extract_batch_from_path(vdj_dir, source_cfg$base_dir),
        vdj_dir = vdj_dir,
        status = "missing_barcode_column",
        n_rows = nrow(dat),
        n_unique_vdj_barcodes = NA_integer_,
        error_message = paste("Missing barcode column:", cfg$vdj_barcode_col)
      )
    ))
  }
  
  batch <- extract_batch_from_path(vdj_dir, source_cfg$base_dir)
  raw_barcodes <- as.character(dat[[cfg$vdj_barcode_col]])
  
  dat <- dat %>%
    mutate(
      raw_barcode = raw_barcodes,
      barcode = paste0(sample_name, "_", raw_barcodes),
      id = sample_name,
      batch = batch,
      source_id = source_cfg$source_id,
      source_base = source_cfg$base_dir,
      vdj_dir = vdj_dir
    )
  
  list(
    data = dat,
    summary = tibble(
      source_id = source_cfg$source_id,
      sample = sample_name,
      batch = batch,
      vdj_dir = vdj_dir,
      status = "loaded",
      n_rows = nrow(dat),
      n_unique_vdj_barcodes = n_distinct(dat$barcode),
      error_message = NA_character_
    )
  )
}


scan_all_vdj_sources <- function(obj, cfg) {
  
  sample_names <- obj@meta.data[[cfg$id_col]] %>%
    as.character() %>%
    unique() %>%
    na.omit()
  
  vdj_entries <- list()
  scan_summaries <- list()
  
  message("Scanning VDJ sources for ", length(sample_names), " sample IDs.")
  
  counter <- 1
  
  for (source_cfg in cfg$vdj_sources) {
    
    message("Scanning source: ", source_cfg$source_id)
    
    vdj_dirs <- find_vdj_dirs_for_source(source_cfg)
    
    if (length(vdj_dirs) == 0) {
      scan_summaries[[counter]] <- tibble(
        source_id = source_cfg$source_id,
        sample = NA_character_,
        batch = NA_character_,
        vdj_dir = NA_character_,
        status = "no_vdj_dirs_found",
        n_rows = NA_integer_,
        n_unique_vdj_barcodes = NA_integer_,
        error_message = NA_character_
      )
      counter <- counter + 1
      next
    }
    
    for (vdj_dir in vdj_dirs) {
      
      result <- read_one_vdj_dir(
        vdj_dir = vdj_dir,
        source_cfg = source_cfg,
        sample_names = sample_names,
        cfg = cfg
      )
      
      if (is.null(result)) {
        next
      }
      
      scan_summaries[[counter]] <- result$summary
      
      if (!is.null(result$data)) {
        key <- paste(
          source_cfg$source_id,
          result$summary$sample,
          vdj_dir,
          sep = "||"
        )
        vdj_entries[[key]] <- result$data
      }
      
      counter <- counter + 1
    }
  }
  
  final_vdj <- if (length(vdj_entries) > 0) {
    bind_rows(vdj_entries)
  } else {
    tibble()
  }
  
  if (isTRUE(cfg$deduplicate_vdj_rows) && nrow(final_vdj) > 0) {
    
    dedup_cols <- intersect(
      c(
        "id", "barcode", "raw_barcode", "chain", "cdr3", "cdr3_nt",
        "v_gene", "d_gene", "j_gene", "c_gene", "productive",
        "full_length", "contig_id"
      ),
      colnames(final_vdj)
    )
    
    if (length(dedup_cols) > 0) {
      final_vdj <- final_vdj %>%
        distinct(across(all_of(dedup_cols)), .keep_all = TRUE)
    }
  }
  
  scan_summary <- if (length(scan_summaries) > 0) {
    bind_rows(scan_summaries)
  } else {
    tibble(
      source_id = character(),
      sample = character(),
      batch = character(),
      vdj_dir = character(),
      status = character(),
      n_rows = integer(),
      n_unique_vdj_barcodes = integer(),
      error_message = character()
    )
  }
  
  list(
    vdj = final_vdj,
    summary = scan_summary
  )
}


make_samples_without_vdj <- function(obj, final_vdj, cfg) {
  
  sample_ids <- obj@meta.data[[cfg$id_col]] %>%
    as.character() %>%
    unique() %>%
    na.omit()
  
  vdj_samples <- if (nrow(final_vdj) > 0 && "id" %in% colnames(final_vdj)) {
    unique(final_vdj$id)
  } else {
    character()
  }
  
  tibble(
    sample = setdiff(sample_ids, vdj_samples)
  )
}


plot_tetramer_clr_pages <- function(obj, cfg) {
  
  if (!isTRUE(cfg$make_tetramer_clr_plots)) {
    return(invisible(NULL))
  }
  
  required_cols <- c(cfg$tetramer_col, cfg$tetramer_clr_col)
  missing_cols <- setdiff(required_cols, colnames(obj@meta.data))
  
  if (length(missing_cols) > 0) {
    message(
      "Skipping tetramer CLR plots because required metadata columns are missing: ",
      paste(missing_cols, collapse = ", ")
    )
    return(invisible(NULL))
  }
  
  create_dir(cfg$output_plot_dir)
  
  plot_df <- obj@meta.data %>%
    rownames_to_column("cell") %>%
    as_tibble()
  
  if (!cfg$sample_col %in% colnames(plot_df)) {
    plot_df[[cfg$sample_col]] <- plot_df[[cfg$id_col]]
  }
  
  plot_df <- plot_df %>%
    mutate(
      !!cfg$tetramer_col := as.character(.data[[cfg$tetramer_col]]),
      !!cfg$tetramer_clr_col := as.numeric(.data[[cfg$tetramer_clr_col]])
    ) %>%
    filter(
      !is.na(.data[[cfg$tetramer_col]]),
      !is.na(.data[[cfg$tetramer_clr_col]]),
      !is.na(.data[[cfg$sample_col]])
    )
  
  if (
    isTRUE(cfg$plot_only_multimer_positive) &&
    cfg$multimer_col %in% colnames(plot_df)
  ) {
    plot_df <- plot_df %>%
      filter(.data[[cfg$multimer_col]] == cfg$multimer_positive_label)
  } else {
    plot_df <- plot_df %>%
      filter(.data[[cfg$tetramer_col]] != cfg$negative_tetramer_label)
  }
  
  plot_df <- plot_df %>%
    mutate(
      !!cfg$tetramer_col := apply_tetramer_replacements_vector(
        .data[[cfg$tetramer_col]],
        cfg$tetramer_replacements
      )
    ) %>%
    filter(.data[[cfg$tetramer_col]] %in% cfg$tetramer_order)
  
  present_tetramers <- cfg$tetramer_order[
    cfg$tetramer_order %in% unique(plot_df[[cfg$tetramer_col]])
  ]
  
  if (length(present_tetramers) == 0) {
    message("No tetramers available for plotting after filtering.")
    return(invisible(NULL))
  }
  
  tetramer_chunks <- split(
    present_tetramers,
    ceiling(seq_along(present_tetramers) / cfg$plot_tetramers_per_page)
  )
  
  for (i in seq_along(tetramer_chunks)) {
    
    tet_group <- tetramer_chunks[[i]]
    
    subset_df <- plot_df %>%
      filter(.data[[cfg$tetramer_col]] %in% tet_group) %>%
      mutate(
        !!cfg$tetramer_col := factor(.data[[cfg$tetramer_col]], levels = tet_group)
      )
    
    if (nrow(subset_df) == 0) {
      next
    }
    
    p <- ggplot(
      subset_df,
      aes(
        x = .data[[cfg$sample_col]],
        y = .data[[cfg$tetramer_clr_col]],
        fill = .data[[cfg$sample_col]]
      )
    ) +
      geom_violin(scale = "width", trim = FALSE) +
      geom_jitter(width = 0.2, size = 0.6, alpha = 0.6) +
      facet_wrap(as.formula(paste("~", cfg$tetramer_col)), scales = "free_y") +
      theme_minimal(base_size = 16) +
      labs(
        title = paste("Multimer-positive tetramer CLR expression - page", i),
        x = "Sample",
        y = "Tetramer CLR"
      ) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14, face = "bold"),
        strip.text = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
        legend.position = "none"
      )
    
    ggsave(
      filename = file.path(
        cfg$output_plot_dir,
        paste0("Multimer_positive_tetramer_CLR_page_", i, ".jpeg")
      ),
      plot = p,
      width = cfg$plot_width,
      height = cfg$plot_height,
      dpi = cfg$plot_dpi,
      limitsize = FALSE
    )
  }
  
  invisible(NULL)
}


apply_tetramer_cutoffs <- function(obj, cutoff_df, cfg) {
  
  required_cols <- c(cfg$tetramer_col, cfg$tetramer_clr_col)
  missing_cols <- setdiff(required_cols, colnames(obj@meta.data))
  
  if (length(missing_cols) > 0) {
    stop(
      "Cannot apply tetramer cutoffs because required columns are missing: ",
      paste(missing_cols, collapse = ", ")
    )
  }
  
  meta <- obj@meta.data %>%
    rownames_to_column("cell") %>%
    as_tibble() %>%
    mutate(
      !!cfg$tetramer_col := as.character(.data[[cfg$tetramer_col]]),
      !!cfg$tetramer_clr_col := as.numeric(.data[[cfg$tetramer_clr_col]])
    )
  
  if (!cfg$tetramer_raw_col %in% colnames(meta)) {
    meta[[cfg$tetramer_raw_col]] <- meta[[cfg$tetramer_col]]
  }
  
  meta[[cfg$tetramer_pre_cutoff_col]] <- apply_tetramer_replacements_vector(
    meta[[cfg$tetramer_col]],
    cfg$tetramer_replacements
  )
  
  meta[[cfg$tetramer_col]] <- meta[[cfg$tetramer_pre_cutoff_col]]
  
  cutoff_df <- cutoff_df %>%
    mutate(tetramer = as.character(tetramer))
  
  meta_cut <- meta %>%
    left_join(cutoff_df, by = setNames("tetramer", cfg$tetramer_col)) %>%
    rename(!!cfg$tetramer_cutoff_col := cutoff) %>%
    mutate(
      below_cutoff = !is.na(.data[[cfg$tetramer_cutoff_col]]) &
        !is.na(.data[[cfg$tetramer_clr_col]]) &
        .data[[cfg$tetramer_col]] != cfg$negative_tetramer_label &
        .data[[cfg$tetramer_clr_col]] < .data[[cfg$tetramer_cutoff_col]],
      
      !!cfg$tetramer_pass_cutoff_col := case_when(
        .data[[cfg$tetramer_col]] == cfg$negative_tetramer_label ~ FALSE,
        is.na(.data[[cfg$tetramer_cutoff_col]]) ~ NA,
        below_cutoff ~ FALSE,
        TRUE ~ TRUE
      ),
      
      !!cfg$tetramer_col := ifelse(
        below_cutoff,
        cfg$negative_tetramer_label,
        .data[[cfg$tetramer_col]]
      )
    ) %>%
    select(-below_cutoff) %>%
    column_to_rownames("cell") %>%
    as.data.frame()
  
  obj@meta.data <- meta_cut
  
  obj
}


make_cutoff_summary <- function(obj, cfg) {
  
  obj@meta.data %>%
    as_tibble() %>%
    mutate(
      tetramer_raw = as.character(.data[[cfg$tetramer_raw_col]]),
      tetramer_pre_cutoff = as.character(.data[[cfg$tetramer_pre_cutoff_col]]),
      tetramer_final = as.character(.data[[cfg$tetramer_col]]),
      tetramer_pass_cutoff = .data[[cfg$tetramer_pass_cutoff_col]]
    ) %>%
    count(
      tetramer_raw,
      tetramer_pre_cutoff,
      tetramer_final,
      tetramer_pass_cutoff,
      name = "n_cells"
    ) %>%
    arrange(tetramer_pre_cutoff, tetramer_final)
}


subset_ebv_cd8_object <- function(obj, cfg) {
  
  meta <- obj@meta.data %>%
    rownames_to_column("cell") %>%
    as_tibble()
  
  if (!cfg$batch_col %in% colnames(meta)) {
    stop("Cannot subset EBV samples because batch column is missing: ", cfg$batch_col)
  }
  
  if (!cfg$sample_col %in% colnames(meta)) {
    meta[[cfg$sample_col]] <- meta[[cfg$id_col]]
  }
  
  if (isTRUE(cfg$subset_ebv_by_sample)) {
    
    ebv_samples <- meta %>%
      filter(
        !is.na(.data[[cfg$batch_col]]),
        grepl(cfg$ebv_batch_regex, .data[[cfg$batch_col]])
      ) %>%
      pull(.data[[cfg$sample_col]]) %>%
      unique()
    
    cells_keep <- meta %>%
      filter(.data[[cfg$sample_col]] %in% ebv_samples) %>%
      pull(cell)
    
  } else {
    
    cells_keep <- meta %>%
      filter(
        !is.na(.data[[cfg$batch_col]]),
        grepl(cfg$ebv_batch_regex, .data[[cfg$batch_col]])
      ) %>%
      pull(cell)
  }
  
  ebv_obj <- subset(obj, cells = cells_keep)
  
  ebv_meta <- ebv_obj@meta.data %>%
    rownames_to_column("cell") %>%
    as_tibble()
  
  cells_keep_no_excluded <- ebv_meta %>%
    filter(
      is.na(.data[[cfg$batch_col]]) |
        !grepl(cfg$exclude_batch_regex, .data[[cfg$batch_col]], ignore.case = TRUE)
    ) %>%
    pull(cell)
  
  ebv_obj <- subset(ebv_obj, cells = cells_keep_no_excluded)
  
  ebv_obj
}


subset_vdj_to_seurat_cells <- function(vdj_df, obj, cfg) {
  
  if (nrow(vdj_df) == 0) {
    return(vdj_df)
  }
  
  if (!cfg$vdj_barcode_key_col %in% colnames(obj@meta.data)) {
    stop("Seurat object does not contain VDJ barcode key column: ", cfg$vdj_barcode_key_col)
  }
  
  keys_keep <- obj@meta.data[[cfg$vdj_barcode_key_col]] %>%
    as.character() %>%
    unique() %>%
    na.omit()
  
  vdj_df %>%
    filter(.data$barcode %in% keys_keep)
}


# ----------------------------- #
# 4. Run pipeline
# ----------------------------- #

create_dir(config$output_dir)
create_dir(config$output_rds_dir)
create_dir(config$output_vdj_dir)
create_dir(config$output_plot_dir)

create_parent_dir(config$output_all_with_vdj_key_rds)
create_parent_dir(config$output_all_filtered_rds)
create_parent_dir(config$output_ebv_cd8_rds)
create_parent_dir(config$output_all_vdj_csv)
create_parent_dir(config$output_ebv_vdj_csv)
create_parent_dir(config$output_vdj_scan_summary_csv)
create_parent_dir(config$output_tetramer_cutoff_summary_csv)
create_parent_dir(config$output_missing_vdj_csv)
create_parent_dir(config$session_info_file)

message("Loading combined Seurat object...")
merged_obj <- load_combined_object(config$input_rds)

message("Ensuring sample metadata column exists...")
merged_obj <- ensure_sample_column(merged_obj, config)

message("Creating stable VDJ barcode key...")
merged_obj <- add_vdj_barcode_key(merged_obj, config)

saveRDS(merged_obj, config$output_all_with_vdj_key_rds)

message("Scanning and combining VDJ files...")
vdj_result <- scan_all_vdj_sources(merged_obj, config)

final_merged_vdj <- vdj_result$vdj
vdj_scan_summary <- vdj_result$summary

samples_without_vdj <- make_samples_without_vdj(
  obj = merged_obj,
  final_vdj = final_merged_vdj,
  cfg = config
)

message("Combined VDJ rows: ", nrow(final_merged_vdj))

readr::write_csv(final_merged_vdj, config$output_all_vdj_csv)
readr::write_csv(vdj_scan_summary, config$output_vdj_scan_summary_csv)
readr::write_csv(samples_without_vdj, config$output_missing_vdj_csv)

message("Generating tetramer CLR QC plots...")
plot_tetramer_clr_pages(merged_obj, config)

message("Applying tetramer CLR cutoffs...")
merged_obj <- apply_tetramer_cutoffs(
  obj = merged_obj,
  cutoff_df = cutoff_df,
  cfg = config
)

cutoff_summary <- make_cutoff_summary(merged_obj, config)

readr::write_csv(
  cutoff_summary,
  config$output_tetramer_cutoff_summary_csv
)

message("Subsetting EBV CD8 samples...")
merged_ebv_cd8 <- subset_ebv_cd8_object(
  obj = merged_obj,
  cfg = config
)

message("Subsetting VDJ table to EBV CD8 object...")
vdj_ebv_subset <- subset_vdj_to_seurat_cells(
  vdj_df = final_merged_vdj,
  obj = merged_ebv_cd8,
  cfg = config
)

readr::write_csv(vdj_ebv_subset, config$output_ebv_vdj_csv)

saveRDS(merged_obj, config$output_all_filtered_rds)
saveRDS(merged_ebv_cd8, config$output_ebv_cd8_rds)

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Tetramer cutoff table:",
    capture.output(print(cutoff_df)),
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nSaved object with VDJ key to: ", config$output_all_with_vdj_key_rds)
message("Saved filtered full object to: ", config$output_all_filtered_rds)
message("Saved EBV CD8-only object to: ", config$output_ebv_cd8_rds)
message("Saved combined VDJ CSV to: ", config$output_all_vdj_csv)
message("Saved EBV-only VDJ CSV to: ", config$output_ebv_vdj_csv)
message("Saved VDJ scan summary to: ", config$output_vdj_scan_summary_csv)
message("Saved tetramer cutoff summary to: ", config$output_tetramer_cutoff_summary_csv)
message("Saved missing VDJ sample list to: ", config$output_missing_vdj_csv)
message("Saved session info to: ", config$session_info_file)

message("\nTCR/VDJ combined RDS generation complete.")