#!/usr/bin/env Rscript

# ==============================================================================
# TCR multimer QC and final EBV CD8 TCR object generation
# ==============================================================================
#
# Purpose:
#   This script takes the EBV-only VDJ CSV and EBV CD8 Seurat object generated by
#   8_generate_TCR_combined_rds.R and performs TCR/multimer QC.
#
#   It:
#     1. collapses VDJ contig rows into one row per cell,
#     2. resolves cells with multiple TRA/TRB chains using UMI counts,
#     3. joins Seurat metadata onto the TCR table,
#     4. performs within-sample tetramer conflict QC,
#     5. optionally applies manual VDJdb-resolved within-sample calls,
#     6. performs global/public-clone tetramer conflict QC,
#     7. optionally applies manual VDJdb-resolved global calls,
#     8. removes HLA-mismatched tetramer calls,
#     9. projects baseline GEM tetramer calls onto activated/non-GEM cells,
#    10. adds final TCR/tetramer metadata back to the Seurat object,
#    11. annotates tetramers with EBV antigen/lifecycle information,
#    12. performs CD8 gating for global PBMC cells, and
#    13. saves final publication-ready RDS files.
#
# Expected inputs:
#   - 8_merged_ebv_vdjs.csv
#   - 8_merged_EBV_CD8_samples_only.rds
#   - EBV_multimer_information.xlsx (available on 10.5281/zenodo.21231183)
#   - Tetramer_HLA_match.xlsx (available on 10.5281/zenodo.21231183)
#   - HLA_information.xlsx (available on 10.5281/zenodo.21231183)
#
# Manual QC inputs (available in Supplementary_inputs_for_scripts on 10.5281/zenodo.21231183):
#   - Conflicting_clones_per_sample_post_vdjdb.xlsx
#   - global_conflicting_TCRs_post_vdjdb.csv
#
# Notes:
#   - Manual VDJdb files are optional. If they are not present, the script uses
#     automatic majority rules when unambiguous and leaves unresolved conflicts
#     flagged in the output CSVs.
#   - Clone definition is TRB-based:
#       within-sample clone = sample + TRB_v_gene + TRB_j_gene + TRB_cdr3
#       global clone        = TRB_v_gene + TRB_j_gene + TRB_cdr3
#   - TCR rows are matched back to Seurat using the stable VDJ barcode key created
#     in 8_generate_TCR_combined_rds.R.
#
# ==============================================================================


# ----------------------------- #
# 0. Load packages
# ----------------------------- #

suppressPackageStartupMessages({
  library(Seurat)
  library(dplyr)
  library(tidyr)
  library(tibble)
  library(readr)
  library(readxl)
  library(stringr)
  library(ggplot2)
})


# ----------------------------- #
# 1. User configuration
# ----------------------------- #

config <- list(
  
  # Inputs from script 8.
  input_ebv_vdj_csv = "path/to/VDJ_analysis/8_merged_ebv_vdjs.csv",
  input_ebv_cd8_rds = "path/to/Combined_RDS/8_merged_EBV_CD8_samples_only.rds",
  
  # Reference files.
  ebv_multimer_info_file = "path/to/EBV_multimer_information.xlsx",
  tetramer_hla_file = "path/to/Tetramer_HLA_match.xlsx",
  hla_info_file = "path/to/HLA_information.xlsx",
  
  # Optional manual VDJdb-resolved files.
  # Set to NULL if not used.
  manual_within_sample_file = "path/to/VDJ_analysis/Conflicting_clones_per_sample_post_vdjdb.xlsx",
  manual_global_file = "path/to/VDJ_analysis/global_conflicting_TCRs_post_vdjdb.csv",
  
  # Output directories.
  output_vdj_dir = "path/to/VDJ_analysis",
  output_rds_dir = "path/to/EBV_activated_RDS",
  output_publication_rds_dir = "path/to/Publication_RDS",
  
  # Intermediate/output CSVs.
  output_collapsed_multi_trb_csv = "path/to/VDJ_analysis/9_collapsed_CD8_EBV_cells_with_multiple_TRBs_labeled.csv",
  output_chain_resolution_summary_csv = "path/to/VDJ_analysis/9_chain_resolution_summary.csv",
  output_gem_tcr_csv = "path/to/VDJ_analysis/9_EBV_TCR_filtered_GEM_only.csv",
  
  output_within_conflicts_csv = "path/to/VDJ_analysis/9_conflicting_clones_one_row_WITHIN_SAMPLE.csv",
  output_within_conflicts_auto_csv = "path/to/VDJ_analysis/9_conflicting_clones_one_row_WITHIN_SAMPLE_AUTO.csv",
  output_qc1_csv = "path/to/VDJ_analysis/9_EBV_TCR_filtered_GEM_only_TETRAMER_FINAL_QC1.csv",
  
  output_global_conflicts_csv = "path/to/VDJ_analysis/9_global_conflicting_TCRs.csv",
  output_global_auto_calls_csv = "path/to/VDJ_analysis/9_QC2_global_clone_calls_highest_or_vdjdbflag.csv",
  output_qc2_csv = "path/to/VDJ_analysis/9_EBV_TCR_filtered_GEM_only_TETRAMER_FINAL_QC2.csv",
  
  output_hla_removed_csv = "path/to/VDJ_analysis/9_HLA_mismatched_cells_removed.csv",
  output_hla_filtered_csv = "path/to/VDJ_analysis/9_EBV_TCR_filtered_GEM_only_TETRAMER_FINAL_QC2_HLA.csv",
  output_projected_tcr_csv = "path/to/VDJ_analysis/9_EBV_TCR_all_GEM_and_nonGEM_projected.csv",
  
  output_merged_vdj_ebv_cd8_rds = "path/to/EBV_activated_RDS/9_merged_VDJ_EBV_CD8_samples_only.rds",
  output_annotated_vdj_ebv_cd8_rds = "path/to/EBV_activated_RDS/9_merged_VDJ_EBV_CD8_samples_only_annotated.rds",
  
  output_publication_combined_rds = "path/to/Publication_RDS/1_EBV_CD8_combined_TCR.rds",
  output_publication_baseline_rds = "path/to/Publication_RDS/1_EBV_baseline_TCR.rds",
  output_publication_activated_rds = "path/to/Publication_RDS/1_EBV_LCL_activated_TCR.rds",
  
  session_info_file = "path/to/VDJ_analysis/9_sessionInfo_TCR_multimer_QC.txt",
  
  # Metadata columns.
  id_col = "id",
  sample_col = "sample",
  batch_col = "batch",
  barcode_col = "barcode",
  vdj_barcode_key_col = "vdj_barcode_key",
  
  tetramer_col = "tetramer",
  tetramer_clr_col = "tetramer_CLR",
  negative_tetramer_label = "negative",
  
  # VDJ columns.
  tcr_columns = c("cdr3", "v_gene", "d_gene", "j_gene", "c_gene", "cdr3_nt"),
  chain_col = "chain",
  umi_col = "umis",
  reads_col = "reads",
  
  # Manual mapping columns.
  manual_within_tetramer_col = "tetramer_final",
  manual_global_tetramer_col = "new_tetramer",
  
  # If manual files are missing, use unambiguous automatic calls.
  use_auto_qc_when_manual_missing = TRUE,
  
  # Batch logic.
  gem_batch_regex = "^GEM",
  ebv_baseline_batch_regex = "^GEMEBV",
  ebv_activated_batch_regex = "^EBVLCL",
  dex_batch_regex = "EBVLCL1DEX|EBVLCL2DEX",
  cd8_batch_regex = "EBVLCL1CD8|EBVLCL2CD8",
  cd4_batch_regex = "EBVLCL1CD4|EBVLCL2CD4",
  
  # Labels for activated inferred populations.
  enriched_label = "enriched",
  lcl_responsive_label = "LCL-responsive",
  
  # ADT gating.
  adt_assay = "ADT",
  adt_marker_features = c("CD4.1", "CD8", "CD3"),
  adt_marker_output_cols = c("ADT_CD4.1_norm", "ADT_CD8_norm", "ADT_CD3_norm"),
  
  global_cd3_min = 2.5,
  global_cd4_max = 3,
  global_cd8_min = 2,
  
  # Metadata cleanup after final VDJ metadata is added.
  metadata_cols_to_remove = c(
    "sample.x", "sample_id", "seurat_clusters", "clonotype_id",
    "is_cell", "contig_id", "high_confidence", "length", "multimer",
    "chain", "v_gene", "d_gene", "j_gene", "c_gene", "full_length",
    "productive", "fwr1", "fwr1_nt", "cdr1", "cdr1_nt",
    "fwr2", "fwr2_nt", "cdr2", "cdr2_nt",
    "fwr3", "fwr3_nt", "cdr3", "cdr3_nt",
    "fwr4", "fwr4_nt", "reads", "umis",
    "raw_consensus_id", "exact_subclonotype_id", "cdr3s_aa",
    "sample.y", "tetramer_raw"
  ),
  
  verbose = TRUE
)


# ----------------------------- #
# 2. Helper functions
# ----------------------------- #

create_parent_dir <- function(path) {
  if (!is.null(path) && nzchar(path)) {
    dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  }
}


create_dir <- function(path) {
  if (!is.null(path) && nzchar(path)) {
    dir.create(path, recursive = TRUE, showWarnings = FALSE)
  }
}


path_exists <- function(path) {
  !is.null(path) && nzchar(path) && file.exists(path)
}


read_table_auto <- function(path, sheet = 1) {
  
  if (!path_exists(path)) {
    stop("File does not exist: ", path)
  }
  
  ext <- tolower(tools::file_ext(path))
  
  if (ext %in% c("xlsx", "xls")) {
    readxl::read_xlsx(path, sheet = sheet) %>%
      as.data.frame()
  } else if (ext %in% c("csv", "txt")) {
    readr::read_csv(path, show_col_types = FALSE) %>%
      as.data.frame()
  } else {
    stop("Unsupported file extension: ", ext)
  }
}


load_seurat_object <- function(path) {
  
  if (!path_exists(path)) {
    stop("Input RDS file does not exist: ", path)
  }
  
  obj <- readRDS(path)
  
  if (!inherits(obj, "Seurat")) {
    stop("Input RDS does not contain a Seurat object: ", path)
  }
  
  obj
}


get_assay_data_compat <- function(obj, assay, layer_or_slot) {
  
  tryCatch(
    {
      GetAssayData(obj, assay = assay, layer = layer_or_slot)
    },
    error = function(e) {
      suppressWarnings(
        GetAssayData(obj, assay = assay, slot = layer_or_slot)
      )
    }
  )
}


safe_select_existing <- function(df, cols) {
  df %>% select(any_of(cols))
}


make_clone_key <- function(df, group_col = "sample") {
  
  required <- c(group_col, "TRB_v_gene", "TRB_j_gene", "TRB_cdr3")
  
  if (!all(required %in% colnames(df))) {
    stop(
      "Cannot build clone_key. Missing columns: ",
      paste(setdiff(required, colnames(df)), collapse = ", ")
    )
  }
  
  df %>%
    mutate(
      clone_key = paste(
        .data[[group_col]],
        TRB_v_gene,
        TRB_j_gene,
        TRB_cdr3,
        sep = "|"
      )
    )
}


make_global_clone_key <- function(df) {
  
  required <- c("TRB_v_gene", "TRB_j_gene", "TRB_cdr3")
  
  if (!all(required %in% colnames(df))) {
    stop(
      "Cannot build clone_key_global. Missing columns: ",
      paste(setdiff(required, colnames(df)), collapse = ", ")
    )
  }
  
  df %>%
    mutate(
      clone_key_global = if_else(
        !is.na(TRB_cdr3) & TRB_cdr3 != "" &
          !is.na(TRB_v_gene) & TRB_v_gene != "" &
          !is.na(TRB_j_gene) & TRB_j_gene != "",
        paste(TRB_v_gene, TRB_j_gene, TRB_cdr3, sep = "|"),
        NA_character_
      )
    )
}


normalise_tetramer_name <- function(x) {
  x <- as.character(x)
  x <- ifelse(grepl("^RPPK", x), sub("^RPPK", "RPQK", x), x)
  x
}


# ----------------------------- #
# 3. Collapse VDJ contigs
# ----------------------------- #

collapse_vdj_to_one_row_per_cell <- function(vdj_df, cfg) {
  
  required_cols <- c(
    cfg$barcode_col,
    cfg$chain_col,
    cfg$tcr_columns,
    cfg$umi_col,
    cfg$reads_col
  )
  
  missing_cols <- setdiff(required_cols, colnames(vdj_df))
  
  if (length(missing_cols) > 0) {
    stop("VDJ table is missing required columns: ", paste(missing_cols, collapse = ", "))
  }
  
  meta_columns <- setdiff(
    colnames(vdj_df),
    c(
      cfg$tcr_columns,
      cfg$chain_col,
      cfg$barcode_col,
      "contig_id",
      cfg$umi_col,
      cfg$reads_col,
      "length",
      "productive"
    )
  )
  
  vdj_labeled <- vdj_df %>%
    filter(.data[[cfg$chain_col]] %in% c("TRA", "TRB")) %>%
    mutate(across(all_of(cfg$tcr_columns), as.character)) %>%
    group_by(.data[[cfg$barcode_col]], .data[[cfg$chain_col]]) %>%
    mutate(chain_index = row_number()) %>%
    ungroup() %>%
    mutate(chain_label = paste0(.data[[cfg$chain_col]], chain_index))
  
  vdj_wide <- vdj_labeled %>%
    select(
      all_of(cfg$barcode_col),
      chain_label,
      all_of(cfg$tcr_columns),
      all_of(c(cfg$umi_col, cfg$reads_col))
    ) %>%
    pivot_wider(
      names_from = chain_label,
      values_from = c(all_of(cfg$tcr_columns), all_of(c(cfg$umi_col, cfg$reads_col))),
      names_glue = "{chain_label}_{.value}"
    )
  
  meta_df <- vdj_df %>%
    select(all_of(cfg$barcode_col), all_of(meta_columns)) %>%
    distinct(.data[[cfg$barcode_col]], .keep_all = TRUE)
  
  collapsed <- vdj_wide %>%
    left_join(meta_df, by = cfg$barcode_col)
  
  collapsed
}


save_multi_trb_table <- function(df_collapsed, cfg) {
  
  if (!all(c("TRB1_cdr3", "TRB2_cdr3") %in% colnames(df_collapsed))) {
    multi_trb <- tibble()
  } else {
    multi_trb <- df_collapsed %>%
      filter(!is.na(TRB1_cdr3) & !is.na(TRB2_cdr3))
  }
  
  readr::write_csv(multi_trb, cfg$output_collapsed_multi_trb_csv)
  
  invisible(multi_trb)
}


resolve_double_chain_by_umi <- function(df, chain = "TRB", barcode_col = "barcode") {
  
  chain1_prefix <- paste0(chain, "1_")
  chain2_prefix <- paste0(chain, "2_")
  
  chain1_cdr3 <- paste0(chain, "1_cdr3")
  chain2_cdr3 <- paste0(chain, "2_cdr3")
  chain1_umis <- paste0(chain, "1_umis")
  chain2_umis <- paste0(chain, "2_umis")
  
  if (!all(c(chain1_cdr3, chain2_cdr3, chain1_umis, chain2_umis) %in% colnames(df))) {
    return(list(
      df = df,
      summary = tibble(
        chain = chain,
        n_double_chain_cells = 0L,
        n_dropped_tied_or_missing_umi = 0L,
        n_kept_chain1 = 0L,
        n_moved_chain2_to_chain1 = 0L
      )
    ))
  }
  
  chain1_cols <- grep(paste0("^", chain1_prefix), colnames(df), value = TRUE)
  chain2_cols <- grep(paste0("^", chain2_prefix), colnames(df), value = TRUE)
  
  suffix1 <- sub(paste0("^", chain1_prefix), "", chain1_cols)
  suffix2 <- sub(paste0("^", chain2_prefix), "", chain2_cols)
  shared_suffix <- intersect(suffix1, suffix2)
  
  chain1_shared_cols <- paste0(chain1_prefix, shared_suffix)
  chain2_shared_cols <- paste0(chain2_prefix, shared_suffix)
  
  multi_idx <- !is.na(df[[chain1_cdr3]]) & !is.na(df[[chain2_cdr3]])
  
  drop_idx <- multi_idx & (
    is.na(df[[chain1_umis]]) |
      is.na(df[[chain2_umis]]) |
      df[[chain1_umis]] == df[[chain2_umis]]
  )
  
  keep_chain1_idx <- multi_idx & !drop_idx & df[[chain1_umis]] > df[[chain2_umis]]
  move_chain2_idx <- multi_idx & !drop_idx & df[[chain2_umis]] > df[[chain1_umis]]
  
  if (any(move_chain2_idx)) {
    df[move_chain2_idx, chain1_shared_cols] <- df[move_chain2_idx, chain2_shared_cols]
  }
  
  if (any(multi_idx & !drop_idx)) {
    df[multi_idx & !drop_idx, chain2_shared_cols] <- NA
  }
  
  dropped_barcodes <- df[[barcode_col]][drop_idx]
  
  df <- df %>%
    filter(!.data[[barcode_col]] %in% dropped_barcodes)
  
  summary <- tibble(
    chain = chain,
    n_double_chain_cells = sum(multi_idx, na.rm = TRUE),
    n_dropped_tied_or_missing_umi = length(dropped_barcodes),
    n_kept_chain1 = sum(keep_chain1_idx, na.rm = TRUE),
    n_moved_chain2_to_chain1 = sum(move_chain2_idx, na.rm = TRUE)
  )
  
  list(df = df, summary = summary)
}


collapse_resolved_chain_columns <- function(df) {
  
  # Collapse TRB1/TRB2 into TRB_*.
  df <- df %>%
    mutate(
      TRB_cdr3    = coalesce(TRB1_cdr3,    TRB2_cdr3),
      TRB_v_gene  = coalesce(TRB1_v_gene,  TRB2_v_gene),
      TRB_d_gene  = coalesce(TRB1_d_gene,  TRB2_d_gene),
      TRB_j_gene  = coalesce(TRB1_j_gene,  TRB2_j_gene),
      TRB_c_gene  = coalesce(TRB1_c_gene,  TRB2_c_gene),
      TRB_cdr3_nt = coalesce(TRB1_cdr3_nt, TRB2_cdr3_nt),
      TRB_umis    = coalesce(TRB1_umis,    TRB2_umis),
      TRB_reads   = coalesce(TRB1_reads,   TRB2_reads)
    )
  
  # Collapse TRA1/TRA2 into TRA_*.
  df <- df %>%
    mutate(
      TRA_cdr3    = coalesce(TRA1_cdr3,    TRA2_cdr3),
      TRA_v_gene  = coalesce(TRA1_v_gene,  TRA2_v_gene),
      TRA_d_gene  = coalesce(TRA1_d_gene,  TRA2_d_gene),
      TRA_j_gene  = coalesce(TRA1_j_gene,  TRA2_j_gene),
      TRA_c_gene  = coalesce(TRA1_c_gene,  TRA2_c_gene),
      TRA_cdr3_nt = coalesce(TRA1_cdr3_nt, TRA2_cdr3_nt),
      TRA_umis    = coalesce(TRA1_umis,    TRA2_umis),
      TRA_reads   = coalesce(TRA1_reads,   TRA2_reads)
    ) %>%
    select(
      -starts_with("TRB1_"),
      -starts_with("TRB2_"),
      -starts_with("TRA1_"),
      -starts_with("TRA2_")
    ) %>%
    filter(!is.na(TRB_cdr3), TRB_cdr3 != "")
  
  df
}


prepare_collapsed_tcr_table <- function(vdj_df, cfg) {
  
  message("Collapsing VDJ table to one row per cell...")
  
  df_collapsed <- collapse_vdj_to_one_row_per_cell(vdj_df, cfg)
  
  save_multi_trb_table(df_collapsed, cfg)
  
  trb_resolved <- resolve_double_chain_by_umi(
    df = df_collapsed,
    chain = "TRB",
    barcode_col = cfg$barcode_col
  )
  
  tra_resolved <- resolve_double_chain_by_umi(
    df = trb_resolved$df,
    chain = "TRA",
    barcode_col = cfg$barcode_col
  )
  
  chain_summary <- bind_rows(
    trb_resolved$summary,
    tra_resolved$summary
  )
  
  df_final <- collapse_resolved_chain_columns(tra_resolved$df)
  
  list(
    tcr = df_final,
    summary = chain_summary
  )
}


# ----------------------------- #
# 4. Join Seurat metadata
# ----------------------------- #

ensure_barcode_key_in_metadata <- function(obj, cfg) {
  
  meta <- obj@meta.data
  
  if (cfg$vdj_barcode_key_col %in% colnames(meta)) {
    return(obj)
  }
  
  if (!cfg$id_col %in% colnames(meta)) {
    stop("Cannot create VDJ barcode key because metadata lacks: ", cfg$id_col)
  }
  
  raw_barcode <- sub("^.*_", "", rownames(meta))
  
  obj@meta.data[[cfg$vdj_barcode_key_col]] <- paste0(
    obj@meta.data[[cfg$id_col]],
    "_",
    raw_barcode
  )
  
  obj
}


join_tcr_with_seurat_metadata <- function(tcr_df, obj, cfg) {
  
  obj <- ensure_barcode_key_in_metadata(obj, cfg)
  
  meta <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("seurat_cell")
  
  needed_meta <- c(
    "seurat_cell",
    cfg$vdj_barcode_key_col,
    cfg$sample_col,
    "age",
    "sex",
    "diagnosis",
    "years_since_diagnosis",
    "cohort",
    cfg$tetramer_col,
    cfg$tetramer_clr_col
  )
  
  meta_to_add <- meta %>%
    select(any_of(needed_meta)) %>%
    distinct(.data[[cfg$vdj_barcode_key_col]], .keep_all = TRUE)
  
  joined <- tcr_df %>%
    left_join(
      meta_to_add,
      by = setNames(cfg$vdj_barcode_key_col, cfg$barcode_col)
    )
  
  if (cfg$sample_col %in% colnames(joined)) {
    joined[[cfg$sample_col]] <- as.character(joined[[cfg$sample_col]])
  }
  
  joined <- joined %>%
    mutate(
      !!cfg$tetramer_col := normalise_tetramer_name(.data[[cfg$tetramer_col]]),
      !!cfg$tetramer_col := if_else(
        is.na(.data[[cfg$tetramer_col]]) | .data[[cfg$tetramer_col]] == "",
        cfg$negative_tetramer_label,
        .data[[cfg$tetramer_col]]
      ),
      !!cfg$tetramer_clr_col := if_else(
        is.na(as.numeric(.data[[cfg$tetramer_clr_col]])),
        0,
        as.numeric(.data[[cfg$tetramer_clr_col]])
      )
    )
  
  joined %>%
    filter(!is.na(.data[[cfg$sample_col]]), .data[[cfg$sample_col]] != "")
}


reorder_tcr_columns <- function(df, cfg) {
  
  preferred_cols <- c(
    cfg$barcode_col,
    cfg$batch_col,
    cfg$id_col,
    "seurat_cell",
    cfg$tetramer_col,
    cfg$tetramer_clr_col,
    "TRA_v_gene",
    "TRA_d_gene",
    "TRA_j_gene",
    "TRA_c_gene",
    "TRA_cdr3",
    "TRA_cdr3_nt",
    "TRB_v_gene",
    "TRB_d_gene",
    "TRB_j_gene",
    "TRB_c_gene",
    "TRB_cdr3",
    "TRB_cdr3_nt",
    cfg$sample_col,
    "cohort",
    "diagnosis",
    "age",
    "sex",
    "years_since_diagnosis"
  )
  
  df %>%
    select(any_of(preferred_cols), everything())
}


# ----------------------------- #
# 5. Within-sample QC
# ----------------------------- #

make_within_sample_conflict_tables <- function(df, cfg) {
  
  df2 <- df %>%
    filter(
      !is.na(TRB_cdr3), TRB_cdr3 != "",
      !is.na(TRB_v_gene), TRB_v_gene != "",
      !is.na(TRB_j_gene), TRB_j_gene != "",
      !is.na(.data[[cfg$tetramer_col]]), .data[[cfg$tetramer_col]] != ""
    ) %>%
    make_clone_key(group_col = cfg$sample_col)
  
  conflict_keys <- df2 %>%
    group_by(clone_key) %>%
    summarise(n_tetramers = n_distinct(.data[[cfg$tetramer_col]]), .groups = "drop") %>%
    filter(n_tetramers > 1) %>%
    pull(clone_key)
  
  df_conflict <- df2 %>%
    filter(clone_key %in% conflict_keys)
  
  if (nrow(df_conflict) == 0) {
    empty_summary <- tibble()
    empty_auto <- tibble()
    return(list(
      df_with_key = df2,
      conflict_cells = df_conflict,
      conflict_summary = empty_summary,
      auto_calls = empty_auto
    ))
  }
  
  tet_counts <- df_conflict %>%
    count(clone_key, tetramer = .data[[cfg$tetramer_col]], name = "n_cells") %>%
    group_by(clone_key) %>%
    summarise(
      tetramer_counts = paste0(tetramer, "=", n_cells, collapse = "; "),
      .groups = "drop"
    )
  
  id_counts <- df_conflict %>%
    count(clone_key, id = .data[[cfg$id_col]], name = "n_cells") %>%
    group_by(clone_key) %>%
    summarise(
      id_counts = paste0(id, "=", n_cells, collapse = "; "),
      .groups = "drop"
    )
  
  tet_by_id <- df_conflict %>%
    count(clone_key, id = .data[[cfg$id_col]], tetramer = .data[[cfg$tetramer_col]], name = "n_cells") %>%
    arrange(clone_key, id, desc(n_cells)) %>%
    group_by(clone_key, id) %>%
    summarise(
      tet_counts_in_id = paste0(tetramer, "=", n_cells, collapse = ", "),
      .groups = "drop"
    ) %>%
    group_by(clone_key) %>%
    summarise(
      tetramer_by_id = paste0(id, ": ", tet_counts_in_id, collapse = " | "),
      .groups = "drop"
    )
  
  conflict_summary <- df_conflict %>%
    group_by(clone_key) %>%
    summarise(
      sample = first(.data[[cfg$sample_col]]),
      TRB_v_gene = first(TRB_v_gene),
      TRB_j_gene = first(TRB_j_gene),
      TRB_cdr3 = first(TRB_cdr3),
      n_cells_total = n(),
      n_tetramers = n_distinct(.data[[cfg$tetramer_col]]),
      .groups = "drop"
    ) %>%
    left_join(tet_counts, by = "clone_key") %>%
    left_join(id_counts, by = "clone_key") %>%
    left_join(tet_by_id, by = "clone_key") %>%
    arrange(desc(n_cells_total), desc(n_tetramers))
  
  clone_stats <- df_conflict %>%
    count(clone_key, tet = .data[[cfg$tetramer_col]], name = "n") %>%
    group_by(clone_key) %>%
    summarise(
      tetramer_counts = paste0(tet, "=", n, collapse = "; "),
      n_neg = sum(n[tet == cfg$negative_tetramer_label], na.rm = TRUE),
      top_nonneg_n = ifelse(
        any(tet != cfg$negative_tetramer_label),
        max(n[tet != cfg$negative_tetramer_label], na.rm = TRUE),
        NA_integer_
      ),
      top_nonneg_tets = ifelse(
        any(tet != cfg$negative_tetramer_label),
        paste(
          tet[
            tet != cfg$negative_tetramer_label &
              n == max(n[tet != cfg$negative_tetramer_label], na.rm = TRUE)
          ],
          collapse = "|"
        ),
        NA_character_
      ),
      n_top_nonneg_tets = ifelse(
        any(tet != cfg$negative_tetramer_label),
        sum(
          tet != cfg$negative_tetramer_label &
            n == max(n[tet != cfg$negative_tetramer_label], na.rm = TRUE)
        ),
        NA_integer_
      ),
      second_nonneg_n = {
        nn <- n[tet != cfg$negative_tetramer_label]
        if (length(nn) >= 2) sort(nn, decreasing = TRUE)[2] else 0
      },
      .groups = "drop"
    ) %>%
    mutate(
      neg_ties_top_nonneg = !is.na(top_nonneg_n) &
        n_neg == top_nonneg_n &
        top_nonneg_n > 0,
      
      tetramer_auto = case_when(
        !is.na(top_nonneg_n) & n_neg > top_nonneg_n ~ cfg$negative_tetramer_label,
        is.na(top_nonneg_n) & n_neg > 0 ~ cfg$negative_tetramer_label,
        neg_ties_top_nonneg ~ NA_character_,
        !is.na(top_nonneg_n) &
          n_top_nonneg_tets == 1 &
          top_nonneg_n > n_neg &
          top_nonneg_n > second_nonneg_n ~ str_split_i(top_nonneg_tets, "\\|", 1),
        !is.na(top_nonneg_n) & n_top_nonneg_tets > 1 ~ NA_character_,
        TRUE ~ cfg$negative_tetramer_label
      ),
      
      needs_vdjdb = neg_ties_top_nonneg |
        (!is.na(top_nonneg_n) & n_top_nonneg_tets > 1),
      
      rule_used = case_when(
        !is.na(top_nonneg_n) & n_neg > top_nonneg_n ~ "negatives_dominate",
        is.na(top_nonneg_n) & n_neg > 0 ~ "negatives_only",
        neg_ties_top_nonneg ~ "neg_vs_nonneg_tie_needs_vdjdb",
        !is.na(top_nonneg_n) &
          n_top_nonneg_tets == 1 &
          top_nonneg_n > n_neg &
          top_nonneg_n > second_nonneg_n ~ "majority_nonneg",
        !is.na(top_nonneg_n) & n_top_nonneg_tets > 1 ~ "tie_needs_vdjdb",
        TRUE ~ "fallback_negative"
      )
    )
  
  conflict_summary_auto <- conflict_summary %>%
    left_join(
      clone_stats %>%
        select(clone_key, tetramer_auto, needs_vdjdb, rule_used),
      by = "clone_key"
    ) %>%
    arrange(desc(n_cells_total), desc(n_tetramers))
  
  list(
    df_with_key = df2,
    conflict_cells = df_conflict,
    conflict_summary = conflict_summary,
    auto_calls = conflict_summary_auto
  )
}


load_within_manual_map <- function(path, cfg) {
  
  if (!path_exists(path)) {
    return(tibble(
      clone_key = character(),
      tetramer_final = character(),
      qc1_source = character()
    ))
  }
  
  message("Loading within-sample manual VDJdb calls: ", path)
  
  conf <- read_table_auto(path)
  
  if (!"clone_key" %in% colnames(conf)) {
    needed <- c(cfg$sample_col, "TRB_v_gene", "TRB_j_gene", "TRB_cdr3")
    
    if (!all(needed %in% colnames(conf))) {
      stop(
        "Manual within-sample file needs either clone_key or columns: ",
        paste(needed, collapse = ", ")
      )
    }
    
    conf <- make_clone_key(conf, group_col = cfg$sample_col)
  }
  
  if (!cfg$manual_within_tetramer_col %in% colnames(conf)) {
    stop(
      "Manual within-sample file does not contain tetramer column: ",
      cfg$manual_within_tetramer_col
    )
  }
  
  conf_map <- conf %>%
    filter(
      !is.na(.data[[cfg$manual_within_tetramer_col]]),
      .data[[cfg$manual_within_tetramer_col]] != ""
    ) %>%
    transmute(
      clone_key = as.character(clone_key),
      tetramer_final = as.character(.data[[cfg$manual_within_tetramer_col]]),
      qc1_source = "manual_vdjdb_within_sample"
    ) %>%
    distinct(clone_key, .keep_all = TRUE)
  
  duplicated_keys <- conf_map %>%
    count(clone_key) %>%
    filter(n > 1)
  
  if (nrow(duplicated_keys) > 0) {
    stop("Manual within-sample file contains duplicated clone_key values.")
  }
  
  conf_map
}


apply_within_sample_qc <- function(df, conflict_result, cfg) {
  
  df_full <- df %>%
    make_clone_key(group_col = cfg$sample_col)
  
  manual_map <- load_within_manual_map(
    path = cfg$manual_within_sample_file,
    cfg = cfg
  )
  
  auto_map <- conflict_result$auto_calls %>%
    filter(!is.na(tetramer_auto)) %>%
    transmute(
      clone_key = as.character(clone_key),
      tetramer_final = as.character(tetramer_auto),
      qc1_source = paste0("auto_", rule_used)
    )
  
  if (nrow(manual_map) > 0) {
    qc1_map <- bind_rows(
      manual_map,
      auto_map %>% filter(!clone_key %in% manual_map$clone_key)
    )
  } else if (isTRUE(cfg$use_auto_qc_when_manual_missing)) {
    qc1_map <- auto_map
  } else {
    qc1_map <- tibble(
      clone_key = character(),
      tetramer_final = character(),
      qc1_source = character()
    )
  }
  
  df_full %>%
    left_join(qc1_map, by = "clone_key") %>%
    mutate(
      tetramer_final_call = if_else(
        !is.na(tetramer_final),
        tetramer_final,
        .data[[cfg$tetramer_col]]
      ),
      tetramer_final_call = if_else(
        is.na(tetramer_final_call) | tetramer_final_call == "",
        cfg$negative_tetramer_label,
        tetramer_final_call
      ),
      tetramer_was_overridden = !is.na(tetramer_final),
      qc1_source = if_else(is.na(qc1_source), "unchanged", qc1_source)
    )
}


# ----------------------------- #
# 6. Global QC
# ----------------------------- #

make_global_conflict_tables <- function(df, cfg) {
  
  df_qc2 <- df %>%
    mutate(
      tetramer = tetramer_final_call,
      tetramer = if_else(is.na(tetramer) | tetramer == "", cfg$negative_tetramer_label, tetramer)
    ) %>%
    filter(
      !is.na(TRB_cdr3), TRB_cdr3 != "",
      !is.na(TRB_v_gene), TRB_v_gene != "",
      !is.na(TRB_j_gene), TRB_j_gene != "",
      !is.na(tetramer), tetramer != ""
    ) %>%
    make_global_clone_key()
  
  conflict_keys <- df_qc2 %>%
    group_by(clone_key_global) %>%
    summarise(n_tetramers = n_distinct(tetramer), .groups = "drop") %>%
    filter(n_tetramers > 1) %>%
    pull(clone_key_global)
  
  df_global_conflict <- df_qc2 %>%
    filter(clone_key_global %in% conflict_keys)
  
  if (nrow(df_global_conflict) == 0) {
    return(list(
      df_qc2 = df_qc2,
      conflict_summary = tibble(),
      qc2_calls = tibble()
    ))
  }
  
  tet_counts_global <- df_global_conflict %>%
    count(clone_key_global, tetramer, name = "n_cells") %>%
    group_by(clone_key_global) %>%
    summarise(
      tetramer_counts = paste0(tetramer, "=", n_cells, collapse = "; "),
      .groups = "drop"
    )
  
  sample_counts_global <- df_global_conflict %>%
    count(clone_key_global, sample, name = "n_cells") %>%
    group_by(clone_key_global) %>%
    summarise(
      sample_counts = paste0(sample, "=", n_cells, collapse = "; "),
      .groups = "drop"
    )
  
  tet_by_sample <- df_global_conflict %>%
    count(clone_key_global, sample, tetramer, name = "n_cells") %>%
    arrange(clone_key_global, sample, desc(n_cells)) %>%
    group_by(clone_key_global, sample) %>%
    summarise(
      tet_counts_in_sample = paste0(tetramer, "=", n_cells, collapse = ", "),
      .groups = "drop"
    ) %>%
    group_by(clone_key_global) %>%
    summarise(
      tetramer_by_sample = paste0(sample, ": ", tet_counts_in_sample, collapse = " | "),
      .groups = "drop"
    )
  
  conflict_summary <- df_global_conflict %>%
    group_by(clone_key_global) %>%
    summarise(
      TRB_v_gene = first(TRB_v_gene),
      TRB_j_gene = first(TRB_j_gene),
      TRB_cdr3 = first(TRB_cdr3),
      n_cells_total = n(),
      n_tetramers = n_distinct(tetramer),
      n_samples = n_distinct(sample),
      .groups = "drop"
    ) %>%
    left_join(tet_counts_global, by = "clone_key_global") %>%
    left_join(sample_counts_global, by = "clone_key_global") %>%
    left_join(tet_by_sample, by = "clone_key_global") %>%
    arrange(desc(n_cells_total), desc(n_samples), desc(n_tetramers))
  
  qc2_calls <- df_global_conflict %>%
    count(clone_key_global, tetramer, name = "n_cells") %>%
    group_by(clone_key_global) %>%
    summarise(
      tetramer_counts = paste0(tetramer, "=", n_cells, collapse = "; "),
      top_n = max(n_cells),
      n_top = sum(n_cells == max(n_cells)),
      top_tets = paste(tetramer[n_cells == max(n_cells)], collapse = "|"),
      tetramer_qc2 = ifelse(n_top == 1, str_split_i(top_tets, "\\|", 1), NA_character_),
      qc2_needs_vdjdb = n_top > 1,
      qc2_rule = ifelse(n_top == 1, "qc2_highest_unique", "qc2_tie_needs_vdjdb"),
      .groups = "drop"
    )
  
  list(
    df_qc2 = df_qc2,
    conflict_summary = conflict_summary,
    qc2_calls = qc2_calls
  )
}


load_global_manual_map <- function(path, cfg) {
  
  if (!path_exists(path)) {
    return(tibble(
      clone_key_global = character(),
      new_tetramer = character(),
      qc2_source = character()
    ))
  }
  
  message("Loading global manual VDJdb calls: ", path)
  
  global_map_raw <- read_table_auto(path)
  
  if (!"clone_key_global" %in% colnames(global_map_raw)) {
    needed <- c("TRB_v_gene", "TRB_j_gene", "TRB_cdr3")
    
    if (!all(needed %in% colnames(global_map_raw))) {
      stop(
        "Manual global file needs either clone_key_global or columns: ",
        paste(needed, collapse = ", ")
      )
    }
    
    global_map_raw <- make_global_clone_key(global_map_raw)
  }
  
  if (!cfg$manual_global_tetramer_col %in% colnames(global_map_raw)) {
    stop(
      "Manual global file does not contain tetramer column: ",
      cfg$manual_global_tetramer_col
    )
  }
  
  global_map <- global_map_raw %>%
    filter(
      !is.na(.data[[cfg$manual_global_tetramer_col]]),
      .data[[cfg$manual_global_tetramer_col]] != ""
    ) %>%
    transmute(
      clone_key_global = as.character(clone_key_global),
      new_tetramer = as.character(.data[[cfg$manual_global_tetramer_col]]),
      qc2_source = "manual_vdjdb_global"
    ) %>%
    distinct(clone_key_global, .keep_all = TRUE)
  
  duplicated_keys <- global_map %>%
    count(clone_key_global) %>%
    filter(n > 1)
  
  if (nrow(duplicated_keys) > 0) {
    stop("Manual global file contains duplicated clone_key_global values.")
  }
  
  global_map
}


apply_global_qc <- function(df_qc1, global_result, cfg) {
  
  df_final2 <- df_qc1 %>%
    mutate(
      tetramer = tetramer_final_call,
      tetramer = if_else(is.na(tetramer) | tetramer == "", cfg$negative_tetramer_label, tetramer)
    ) %>%
    make_global_clone_key()
  
  manual_map <- load_global_manual_map(
    path = cfg$manual_global_file,
    cfg = cfg
  )
  
  auto_map <- global_result$qc2_calls %>%
    filter(!is.na(tetramer_qc2)) %>%
    transmute(
      clone_key_global = as.character(clone_key_global),
      new_tetramer = as.character(tetramer_qc2),
      qc2_source = qc2_rule
    )
  
  if (nrow(manual_map) > 0) {
    qc2_map <- bind_rows(
      manual_map,
      auto_map %>% filter(!clone_key_global %in% manual_map$clone_key_global)
    )
  } else if (isTRUE(cfg$use_auto_qc_when_manual_missing)) {
    qc2_map <- auto_map
  } else {
    qc2_map <- tibble(
      clone_key_global = character(),
      new_tetramer = character(),
      qc2_source = character()
    )
  }
  
  df_final2 %>%
    left_join(qc2_map, by = "clone_key_global") %>%
    mutate(
      tetramer_qc2_final = if_else(!is.na(new_tetramer), new_tetramer, tetramer),
      tetramer_qc2_final = if_else(
        is.na(tetramer_qc2_final) | tetramer_qc2_final == "",
        cfg$negative_tetramer_label,
        tetramer_qc2_final
      ),
      qc2_was_overridden = !is.na(new_tetramer),
      qc2_source = if_else(is.na(qc2_source), "unchanged", qc2_source)
    )
}


# ----------------------------- #
# 7. HLA mismatch filtering
# ----------------------------- #

apply_hla_filter <- function(df, cfg) {
  
  if (!path_exists(cfg$tetramer_hla_file) || !path_exists(cfg$hla_info_file)) {
    message("Skipping HLA filtering because HLA reference files are missing.")
    
    return(list(
      df_filtered = df,
      bad_calls = tibble()
    ))
  }
  
  message("Applying HLA mismatch filter...")
  
  tetramer_hla <- readxl::read_xlsx(cfg$tetramer_hla_file) %>%
    as.data.frame()
  
  hla <- readxl::read_xlsx(cfg$hla_info_file) %>%
    as.data.frame()
  
  if (!"tetramer" %in% colnames(tetramer_hla)) {
    stop("Tetramer HLA file must contain a 'tetramer' column.")
  }
  
  if (!cfg$sample_col %in% colnames(hla)) {
    stop("HLA information file must contain a sample column: ", cfg$sample_col)
  }
  
  tetramer_long <- tetramer_hla %>%
    pivot_longer(
      cols = -tetramer,
      names_to = "allele",
      values_to = "tetramer_hla_status"
    ) %>%
    filter(tetramer_hla_status == "positive") %>%
    transmute(
      tetramer = as.character(tetramer),
      allele = as.character(allele)
    ) %>%
    distinct()
  
  hla_long <- hla %>%
    pivot_longer(
      cols = -all_of(cfg$sample_col),
      names_to = "allele",
      values_to = "sample_hla_status"
    ) %>%
    filter(sample_hla_status == "positive") %>%
    transmute(
      sample = as.character(.data[[cfg$sample_col]]),
      allele = as.character(allele)
    ) %>%
    distinct()
  
  valid_pairs <- tetramer_long %>%
    inner_join(hla_long, by = "allele") %>%
    distinct(tetramer, sample)
  
  known_tetramers <- unique(valid_pairs$tetramer)
  known_samples <- unique(valid_pairs$sample)
  
  df2 <- df %>%
    mutate(
      tetramer_raw_final = tetramer_qc2_final,
      tetramer_key = str_replace(str_trim(tetramer_qc2_final), "\\*$", "")
    )
  
  bad_calls <- df2 %>%
    filter(
      !is.na(tetramer_key),
      tetramer_key != cfg$negative_tetramer_label,
      tetramer_key %in% known_tetramers,
      .data[[cfg$sample_col]] %in% known_samples
    ) %>%
    anti_join(
      valid_pairs,
      by = c("tetramer_key" = "tetramer", "sample" = "sample")
    )
  
  df_filtered <- df2 %>%
    anti_join(
      bad_calls %>%
        select(all_of(cfg$barcode_col)) %>%
        distinct(),
      by = cfg$barcode_col
    )
  
  list(
    df_filtered = df_filtered,
    bad_calls = bad_calls
  )
}


# ----------------------------- #
# 8. Project GEM tetramer calls onto non-GEM cells
# ----------------------------- #

project_gem_tetramers_to_non_gem <- function(df_gem_qc, df_non_gem, cfg) {
  
  gem_tet_col <- "tetramer_qc2_final"
  
  df_gem <- df_gem_qc %>%
    filter(
      !is.na(.data[[cfg$sample_col]]), .data[[cfg$sample_col]] != "",
      !is.na(TRB_v_gene), TRB_v_gene != "",
      !is.na(TRB_j_gene), TRB_j_gene != "",
      !is.na(TRB_cdr3), TRB_cdr3 != "",
      !is.na(.data[[gem_tet_col]]), .data[[gem_tet_col]] != ""
    ) %>%
    mutate(
      clone_key = paste(.data[[cfg$sample_col]], TRB_v_gene, TRB_j_gene, TRB_cdr3, sep = "|")
    )
  
  df_non <- df_non_gem %>%
    filter(
      !is.na(.data[[cfg$sample_col]]), .data[[cfg$sample_col]] != "",
      !is.na(TRB_v_gene), TRB_v_gene != "",
      !is.na(TRB_j_gene), TRB_j_gene != "",
      !is.na(TRB_cdr3), TRB_cdr3 != ""
    ) %>%
    mutate(
      clone_key = paste(.data[[cfg$sample_col]], TRB_v_gene, TRB_j_gene, TRB_cdr3, sep = "|")
    )
  
  gem_map_check <- df_gem %>%
    group_by(.data[[cfg$sample_col]], clone_key) %>%
    summarise(n_tet = n_distinct(.data[[gem_tet_col]]), .groups = "drop") %>%
    filter(n_tet > 1)
  
  if (nrow(gem_map_check) > 0) {
    print(head(gem_map_check, 50))
    stop("Baseline GEM still has >1 tetramer call for some sample-level clones.")
  }
  
  gem_clone_map <- df_gem %>%
    distinct(
      .data[[cfg$sample_col]],
      clone_key,
      .data[[gem_tet_col]]
    ) %>%
    rename(tetramer_from_GEM = !!gem_tet_col)
  
  df_non_projected <- df_non %>%
    left_join(
      gem_clone_map,
      by = c(cfg$sample_col, "clone_key")
    ) %>%
    mutate(
      tetramer = case_when(
        !is.na(tetramer_from_GEM) ~ tetramer_from_GEM,
        str_detect(.data[[cfg$batch_col]], cfg$dex_batch_regex) ~ cfg$enriched_label,
        str_detect(.data[[cfg$batch_col]], cfg$cd8_batch_regex) ~ cfg$lcl_responsive_label,
        TRUE ~ cfg$negative_tetramer_label
      ),
      tetramer_source = case_when(
        !is.na(tetramer_from_GEM) ~ "projected_from_GEM_same_sample",
        str_detect(.data[[cfg$batch_col]], cfg$dex_batch_regex) ~ "batch_inferred",
        str_detect(.data[[cfg$batch_col]], cfg$cd8_batch_regex) ~ "batch_inferred",
        TRUE ~ "negative"
      ),
      data_source = "nonGEM_activated"
    ) %>%
    select(-tetramer_from_GEM)
  
  df_gem_final <- df_gem_qc %>%
    mutate(
      tetramer = tetramer_qc2_final,
      tetramer = if_else(is.na(tetramer) | tetramer == "", cfg$negative_tetramer_label, tetramer),
      data_source = "GEM_baseline",
      tetramer_source = "GEM_measured_QC1_QC2_HLA"
    )
  
  bind_rows(df_gem_final, df_non_projected)
}


# ----------------------------- #
# 9. Add VDJ metadata back to Seurat object
# ----------------------------- #

add_vdj_metadata_to_seurat <- function(obj, df_all, cfg) {
  
  obj <- ensure_barcode_key_in_metadata(obj, cfg)
  
  meta <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("seurat_cell") %>%
    mutate(
      key = as.character(.data[[cfg$vdj_barcode_key_col]])
    )
  
  vdj_to_add <- df_all %>%
    transmute(
      key = as.character(.data[[cfg$barcode_col]]),
      tetramer = as.character(tetramer),
      data_source = as.character(data_source),
      tetramer_source = as.character(tetramer_source),
      TRA_v_gene,
      TRA_d_gene,
      TRA_j_gene,
      TRA_c_gene,
      TRA_cdr3,
      TRA_cdr3_nt,
      TRB_v_gene,
      TRB_d_gene,
      TRB_j_gene,
      TRB_c_gene,
      TRB_cdr3,
      TRB_cdr3_nt
    ) %>%
    distinct(key, .keep_all = TRUE)
  
  meta_matched <- meta %>%
    inner_join(vdj_to_add %>% select(key), by = "key")
  
  cells_keep <- intersect(meta_matched$seurat_cell, colnames(obj))
  
  obj_vdj <- subset(obj, cells = cells_keep)
  
  vdj_meta_for_seurat <- meta_matched %>%
    select(seurat_cell, key) %>%
    left_join(vdj_to_add, by = "key") %>%
    select(-key) %>%
    distinct(seurat_cell, .keep_all = TRUE) %>%
    column_to_rownames("seurat_cell")
  
  vdj_meta_for_seurat <- vdj_meta_for_seurat[colnames(obj_vdj), , drop = FALSE]
  
  AddMetaData(
    object = obj_vdj,
    metadata = vdj_meta_for_seurat
  )
}


# ----------------------------- #
# 10. Virus/antigen annotation
# ----------------------------- #

add_multimer_information <- function(obj, cfg) {
  
  if (!path_exists(cfg$ebv_multimer_info_file)) {
    stop("EBV multimer information file does not exist: ", cfg$ebv_multimer_info_file)
  }
  
  multimer_info <- readxl::read_xlsx(cfg$ebv_multimer_info_file) %>%
    as.data.frame()
  
  required_cols <- c("tetramer", "virus", "lifecycle", "latency", "antigen")
  
  if (!all(required_cols %in% colnames(multimer_info))) {
    stop(
      "EBV multimer information file is missing columns: ",
      paste(setdiff(required_cols, colnames(multimer_info)), collapse = ", ")
    )
  }
  
  multimer_info <- multimer_info %>%
    add_row(
      tetramer = cfg$enriched_label,
      virus = cfg$enriched_label,
      lifecycle = cfg$enriched_label,
      latency = cfg$enriched_label,
      antigen = cfg$enriched_label
    ) %>%
    add_row(
      tetramer = cfg$lcl_responsive_label,
      virus = cfg$lcl_responsive_label,
      lifecycle = cfg$lcl_responsive_label,
      latency = cfg$lcl_responsive_label,
      antigen = cfg$lcl_responsive_label
    ) %>%
    add_row(
      tetramer = cfg$negative_tetramer_label,
      virus = cfg$negative_tetramer_label,
      lifecycle = cfg$negative_tetramer_label,
      latency = cfg$negative_tetramer_label,
      antigen = cfg$negative_tetramer_label
    ) %>%
    distinct(tetramer, .keep_all = TRUE)
  
  meta <- obj@meta.data %>%
    as.data.frame() %>%
    rownames_to_column("cell_barcode")
  
  # Remove old annotation columns before joining.
  meta <- meta %>%
    select(-any_of(c("virus", "lifecycle", "latency", "antigen")))
  
  meta2 <- meta %>%
    left_join(
      multimer_info %>%
        select(tetramer, virus, lifecycle, latency, antigen),
      by = "tetramer"
    )
  
  # CD19.1 is treated as negative.
  is_cd19 <- !is.na(meta2$tetramer) & meta2$tetramer == "CD19.1"
  
  meta2$tetramer[is_cd19] <- cfg$negative_tetramer_label
  meta2$virus[is_cd19] <- cfg$negative_tetramer_label
  meta2$lifecycle[is_cd19] <- cfg$negative_tetramer_label
  meta2$latency[is_cd19] <- cfg$negative_tetramer_label
  meta2$antigen[is_cd19] <- cfg$negative_tetramer_label
  
  # For GEMEBV/DEX cells, negative/NA annotations are considered enriched.
  is_gemebv_or_dex <- str_detect(meta2[[cfg$batch_col]], "GEMEBV|DEX")
  
  # For CD8 activated batches, negative/NA annotations are LCL-responsive.
  is_cd8_batch <- str_detect(meta2[[cfg$batch_col]], "CD8")
  
  meta2 <- meta2 %>%
    mutate(
      tetramer = case_when(
        tetramer == cfg$negative_tetramer_label & is_gemebv_or_dex ~ cfg$enriched_label,
        tetramer == cfg$negative_tetramer_label & is_cd8_batch ~ cfg$lcl_responsive_label,
        TRUE ~ tetramer
      ),
      virus = case_when(
        (is.na(virus) | virus == cfg$negative_tetramer_label) & is_gemebv_or_dex ~ cfg$enriched_label,
        (is.na(virus) | virus == cfg$negative_tetramer_label) & is_cd8_batch ~ cfg$lcl_responsive_label,
        TRUE ~ virus
      ),
      lifecycle = case_when(
        (is.na(lifecycle) | lifecycle == cfg$negative_tetramer_label) & is_gemebv_or_dex ~ cfg$enriched_label,
        (is.na(lifecycle) | lifecycle == cfg$negative_tetramer_label) & is_cd8_batch ~ cfg$lcl_responsive_label,
        TRUE ~ lifecycle
      ),
      latency = case_when(
        (is.na(latency) | latency == cfg$negative_tetramer_label) & is_gemebv_or_dex ~ cfg$enriched_label,
        (is.na(latency) | latency == cfg$negative_tetramer_label) & is_cd8_batch ~ cfg$lcl_responsive_label,
        TRUE ~ latency
      ),
      antigen = case_when(
        (is.na(antigen) | antigen == cfg$negative_tetramer_label) & is_gemebv_or_dex ~ cfg$enriched_label,
        (is.na(antigen) | antigen == cfg$negative_tetramer_label) & is_cd8_batch ~ cfg$lcl_responsive_label,
        TRUE ~ antigen
      )
    ) %>%
    column_to_rownames("cell_barcode")
  
  obj@meta.data <- meta2
  
  obj
}


cleanup_metadata <- function(obj, cfg) {
  
  obj@meta.data <- obj@meta.data %>%
    select(-any_of(cfg$metadata_cols_to_remove))
  
  obj
}


# ----------------------------- #
# 11. ADT CD8 gating and final subsets
# ----------------------------- #

add_adt_marker_metadata <- function(obj, cfg) {
  
  if (!cfg$adt_assay %in% Assays(obj)) {
    stop("ADT assay not found in object: ", cfg$adt_assay)
  }
  
  adt_features <- rownames(obj[[cfg$adt_assay]])
  missing_features <- setdiff(cfg$adt_marker_features, adt_features)
  
  if (length(missing_features) > 0) {
    stop(
      "Missing ADT marker features required for gating: ",
      paste(missing_features, collapse = ", ")
    )
  }
  
  adt_mat <- get_assay_data_compat(
    obj = obj,
    assay = cfg$adt_assay,
    layer_or_slot = "data"
  )[cfg$adt_marker_features, , drop = FALSE]
  
  adt_df <- t(as.matrix(adt_mat)) %>%
    as.data.frame()
  
  colnames(adt_df) <- cfg$adt_marker_output_cols
  
  AddMetaData(obj, adt_df)
}


gate_final_cd8_object <- function(obj, cfg) {
  
  meta <- obj@meta.data
  
  required_cols <- c(
    cfg$batch_col,
    "ADT_CD3_norm",
    "ADT_CD4.1_norm",
    "ADT_CD8_norm"
  )
  
  missing_cols <- setdiff(required_cols, colnames(meta))
  
  if (length(missing_cols) > 0) {
    stop("Cannot gate CD8 object. Missing columns: ", paste(missing_cols, collapse = ", "))
  }
  
  is_gemebv_or_ebvlcl <- grepl(cfg$ebv_baseline_batch_regex, meta[[cfg$batch_col]]) |
    grepl(cfg$ebv_activated_batch_regex, meta[[cfg$batch_col]])
  
  is_other_cd8_gated <- !is_gemebv_or_ebvlcl &
    meta$ADT_CD3_norm > cfg$global_cd3_min &
    meta$ADT_CD4.1_norm < cfg$global_cd4_max &
    meta$ADT_CD8_norm > cfg$global_cd8_min
  
  keep_cells <- rownames(meta)[is_gemebv_or_ebvlcl | is_other_cd8_gated]
  
  gated <- subset(obj, cells = keep_cells)
  
  gated <- subset(
    gated,
    subset = !grepl(cd4_batch_regex, batch)
  )
  
  gated
}


make_publication_subsets <- function(obj, cfg) {
  
  baseline <- subset(
    obj,
    subset = grepl(gem_batch_regex, batch)
  )
  
  meta <- obj@meta.data
  
  ebvlcl_samples <- unique(meta[[cfg$sample_col]][grepl(cfg$ebv_activated_batch_regex, meta[[cfg$batch_col]])])
  gem_like_samples <- unique(meta[[cfg$sample_col]][grepl(cfg$gem_batch_regex, meta[[cfg$batch_col]])])
  
  shared_samples <- intersect(ebvlcl_samples, gem_like_samples)
  
  activated_counterpart <- subset(
    obj,
    subset = sample %in% shared_samples
  )
  
  list(
    combined = obj,
    baseline = baseline,
    activated_counterpart = activated_counterpart,
    shared_samples = shared_samples
  )
}


# ----------------------------- #
# 12. Run pipeline
# ----------------------------- #

create_dir(config$output_vdj_dir)
create_dir(config$output_rds_dir)
create_dir(config$output_publication_rds_dir)

output_paths <- unlist(config[grepl("^output_|session_info_file", names(config))])

for (path in output_paths) {
  if (is.character(path) && length(path) == 1 && nzchar(path)) {
    create_parent_dir(path)
  }
}

message("Loading EBV-only VDJ CSV...")
vdj_df <- readr::read_csv(config$input_ebv_vdj_csv, show_col_types = FALSE)

message("Loading EBV CD8 Seurat object...")
merged_ebv_cd8 <- load_seurat_object(config$input_ebv_cd8_rds)

merged_ebv_cd8 <- ensure_barcode_key_in_metadata(merged_ebv_cd8, config)

message("Preparing collapsed TCR table...")
collapsed_result <- prepare_collapsed_tcr_table(vdj_df, config)

tcr_collapsed <- collapsed_result$tcr
chain_resolution_summary <- collapsed_result$summary

readr::write_csv(
  chain_resolution_summary,
  config$output_chain_resolution_summary_csv
)

message("Joining Seurat metadata onto TCR table...")
tcr_with_meta <- join_tcr_with_seurat_metadata(
  tcr_df = tcr_collapsed,
  obj = merged_ebv_cd8,
  cfg = config
) %>%
  reorder_tcr_columns(config)

# Split baseline GEM/GEMEBV from activated/non-GEM.
df_gem <- tcr_with_meta %>%
  filter(grepl(config$gem_batch_regex, .data[[config$batch_col]]))

df_non_gem <- tcr_with_meta %>%
  filter(!grepl(config$gem_batch_regex, .data[[config$batch_col]]))

readr::write_csv(df_gem, config$output_gem_tcr_csv)

message("Running within-sample multimer QC...")
within_result <- make_within_sample_conflict_tables(df_gem, config)

readr::write_csv(
  within_result$conflict_summary,
  config$output_within_conflicts_csv
)

readr::write_csv(
  within_result$auto_calls,
  config$output_within_conflicts_auto_csv
)

df_qc1 <- apply_within_sample_qc(
  df = df_gem,
  conflict_result = within_result,
  cfg = config
)

readr::write_csv(df_qc1, config$output_qc1_csv)

message("Running global/public-clone multimer QC...")
global_result <- make_global_conflict_tables(df_qc1, config)

readr::write_csv(
  global_result$conflict_summary,
  config$output_global_conflicts_csv
)

readr::write_csv(
  global_result$qc2_calls,
  config$output_global_auto_calls_csv
)

df_qc2 <- apply_global_qc(
  df_qc1 = df_qc1,
  global_result = global_result,
  cfg = config
)

readr::write_csv(df_qc2, config$output_qc2_csv)

message("Applying HLA mismatch filtering...")
hla_result <- apply_hla_filter(df_qc2, config)

df_hla_filtered <- hla_result$df_filtered
bad_hla_calls <- hla_result$bad_calls

readr::write_csv(bad_hla_calls, config$output_hla_removed_csv)
readr::write_csv(df_hla_filtered, config$output_hla_filtered_csv)

message("Projecting GEM tetramer calls onto activated/non-GEM TCRs...")
df_all <- project_gem_tetramers_to_non_gem(
  df_gem_qc = df_hla_filtered,
  df_non_gem = df_non_gem,
  cfg = config
)

readr::write_csv(df_all, config$output_projected_tcr_csv)

message("Adding final VDJ/tetramer metadata back to Seurat...")
merged_ebv_cd8_vdj <- add_vdj_metadata_to_seurat(
  obj = merged_ebv_cd8,
  df_all = df_all,
  cfg = config
)

saveRDS(
  merged_ebv_cd8_vdj,
  config$output_merged_vdj_ebv_cd8_rds
)

message("Adding EBV multimer/antigen information...")
merged_ebv_cd8_vdj <- add_multimer_information(
  obj = merged_ebv_cd8_vdj,
  cfg = config
)

merged_ebv_cd8_vdj <- cleanup_metadata(
  obj = merged_ebv_cd8_vdj,
  cfg = config
)

saveRDS(
  merged_ebv_cd8_vdj,
  config$output_annotated_vdj_ebv_cd8_rds
)

message("Adding ADT marker metadata and gating final CD8 object...")
merged_ebv_cd8_vdj <- add_adt_marker_metadata(
  obj = merged_ebv_cd8_vdj,
  cfg = config
)

merged_cd8_final <- gate_final_cd8_object(
  obj = merged_ebv_cd8_vdj,
  cfg = config
)

message("Creating publication subsets...")
publication_objects <- make_publication_subsets(
  obj = merged_cd8_final,
  cfg = config
)

saveRDS(
  publication_objects$combined,
  config$output_publication_combined_rds
)

saveRDS(
  publication_objects$baseline,
  config$output_publication_baseline_rds
)

saveRDS(
  publication_objects$activated_counterpart,
  config$output_publication_activated_rds
)

writeLines(
  c(
    "Configuration:",
    capture.output(str(config)),
    "",
    "Chain resolution summary:",
    capture.output(print(chain_resolution_summary)),
    "",
    "Final object summaries:",
    paste0("Combined cells: ", ncol(publication_objects$combined)),
    paste0("Baseline cells: ", ncol(publication_objects$baseline)),
    paste0("Activated/counterpart cells: ", ncol(publication_objects$activated_counterpart)),
    paste0("Shared activated samples: ", paste(publication_objects$shared_samples, collapse = ", ")),
    "",
    "Session information:",
    capture.output(sessionInfo())
  ),
  config$session_info_file
)

message("\nSaved final combined publication object to: ", config$output_publication_combined_rds)
message("Saved baseline publication object to: ", config$output_publication_baseline_rds)
message("Saved activated/counterpart publication object to: ", config$output_publication_activated_rds)
message("Saved projected TCR table to: ", config$output_projected_tcr_csv)
message("Saved session info to: ", config$session_info_file)

message("\nTCR multimer QC complete.")
